## 기본 실행 코드
### 이것들은 실행시켜야 어느 단계든 원활하게 돌아감

In [ ]:
# 코랩을 시작할 때 아래코드를 한 번 돌려줍니다.
!pip install selenium
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
!pip install webdriver_manager

Requirement already satisfied: selenium in /usr/local/lib/python3.10/dist-packages (4.14.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in /usr/local/lib/python3.10/dist-packages (from selenium) (2.0.6)
Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.10/dist-packages (from selenium) (0.22.2)
Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.10/dist-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /usr/local/lib/python3.10/dist-packages (from selenium) (2023.7.22)
Requirement already satisfied: attrs>=20.1.0 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (23.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.1.3)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.10/dist-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:7 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
chromium-chromedriver is already the newest version (1:85.0.4183.83-0ubuntu2.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
cp: '/usr/lib/chromium-browser/chromedriver' and '/usr/bin/chromedriver' are the same file
Requirement already satisfied: webdriver_manager in /usr/local/lib/python3.10/dist-packages (4.0.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from webdriver_manager) (2.31.0)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.10/dist-packages (from webdriver_manager) (1.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from webdriver_manager) (23.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->webdriver_manager) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->webdriver_manager) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->webdriver_manager) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->webdriver_manager) (2023.7.22)

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import sys
sys.path.insert(0, '/usr/lib/chromium-browser/chromedriver')

In [ ]:
from urllib3.util.retry import Retry
from requests.adapters import HTTPAdapter
from openpyxl import Workbook
from bs4 import BeautifulSoup
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys
import time
import datetime
import requests

In [ ]:
service = Service(executable_path=r'chromedriver')
options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome(options=options)

In [ ]:
# url
url = 'https://m.place.naver.com/restaurant/1085956231/review/visitor?entry=ple&reviewSort=recent'

# BS4 setting for secondary access
session = requests.Session()
headers = {
    "User-Agent": "user value"}

retries = Retry(total=5,
                backoff_factor=0.1,
                status_forcelist=[500, 502, 503, 504])

session.mount('http://', HTTPAdapter(max_retries=retries))

In [ ]:
# New xlsx file
now = datetime.datetime.now()
xlsx = Workbook()
list_sheet = xlsx.create_sheet('output')
list_sheet.append(['nickname', 'content', 'date', 'revisit'])

In [ ]:
# Start crawling/scraping!
try:
    res = driver.get(url)
    driver.implicitly_wait(30)

    # Pagedown
    driver.find_element(By.TAG_NAME, 'body').send_keys(Keys.PAGE_DOWN)

    try:
        while True:
            driver.find_element(By.XPATH, '//*[@id="app-root"]/div/div/div/div[7]/div[2]/div[3]/div[2]').click()
            time.sleep(0.4)
    except Exception as e:
        print('finish')

    time.sleep(25)
    html = driver.page_source
    bs = BeautifulSoup(html, 'lxml')
    reviews = bs.select('li.YeINN')

    for r in reviews:
        nickname = r.select_one('div.sBWyy')
        content = r.select_one('div.ZZ4OK.IwhtZ')
        date = r.select('span.P1zUJ>span.place_blind')[1]
        revisit = r.select('div.sb8UA>span.P1zUJ')[1]

        # exception handling
        nickname = nickname.text if nickname else ''
        content = content.text if content else ''
        date = date.text if date else ''
        revisit = revisit.text if revisit else ''
        time.sleep(0.06)

        print(nickname, '/', content, '/', date, '/', revisit)
        list_sheet.append([nickname, content, date, revisit])
        time.sleep(0.06)
    # Save the file
    file_name = '/data/raw/naver_review_' + now.strftime('%Y-%m-%d_%H-%M-%S') + '.xlsx'
    xlsx.save(file_name)

except Exception as e:
    print(e)
    # Save the file(temp)
    file_name = 'naver_review_' + now.strftime('%Y-%m-%d_%H-%M-%S') + '.xlsx'
    xlsx.save(file_name)

finish
list index out of range

## 연극 월간 랭킹 가져오기

In [ ]:
driver.maximize_window()
driver.get("http://ticket.interpark.com/TPGoodsList.asp?Ca=Dra&Sort=3")
time.sleep(3)
driver.implicitly_wait(1)
time.sleep(3)
text = []
place = []
date = []
entire = []

rows=driver.find_elements(By.CLASS_NAME, 'fw_bold')
for i, row in enumerate(rows):
    text.append(row.text)

play_place=driver.find_elements(By.CLASS_NAME, 'Rkdate')
for i, p in enumerate(play_place):
  entire.append(p.text)

place = entire[0::2]
date = entire[1::2]

In [ ]:
import pandas as pd
now = datetime.datetime.now()
play_rank = pd.DataFrame({"연극 이름":text, "공연장": place, "기간": date})
play_rank.to_csv("/data/raw/play_rank" + now.strftime('%Y-%m-%d') + ".csv", encoding='utf-8')

In [ ]:
driver.maximize_window()
driver.get("http://ticket.interpark.com/TPGoodsList.asp?Ca=Mus&Sort=3")
time.sleep(3)
driver.implicitly_wait(1)
time.sleep(3)
text = []
place = []
date = []
entire = []

rows=driver.find_elements(By.CLASS_NAME, 'fw_bold')
for i, row in enumerate(rows):
    text.append(row.text)

play_place=driver.find_elements(By.CLASS_NAME, 'Rkdate')
for i, p in enumerate(play_place):
  entire.append(p.text)

place = entire[0::2]
date = entire[1::2]

In [ ]:
import pandas as pd
now = datetime.datetime.now()
play_rank = pd.DataFrame({"뮤지컬 이름":text, "공연장": place, "기간": date})
play_rank.to_csv("/data/raw/musical_rank" + now.strftime('%Y-%m-%d') + ".csv", encoding='utf-8')

## 크롤링 된 데이터 정제

In [ ]:
import pandas as pd
play_rank = pd.read_csv('/data/raw/play_rank_sample.csv', encoding='utf-8')
play_rank = pd.DataFrame(play_rank[:156])
play_rank

,Unnamed: 0,연극 이름,공연장,기간
0,0,연극 너의 목소리가 들려,도토리씨어터,2023.04.03~\n2023.10.31
1,1,대학로 1위 연극 〈쉬어매드니스〉,콘텐츠박스(KONTENTZ BOX),2015.11.12~\n2023.10.31
2,2,행오버,정극장,2023.05.01~\n2023.10.31
3,3,연극 〈바닷마을 다이어리〉,예술의전당 자유소극장,2023.10.08~\n2023.11.19
4,4,연극 한뼘사이,라온아트홀,2017.03.01~\n2023.10.31
...,...,...,...,...
151,151,섹시코미디연극 나의PS파트너 (청주),소명아트홀,2023.12.01~\n2023.12.31
152,152,쇼팔다 미친 유령 극단,수유연극실험실,2023.09.01~\n2023.10.15
153,153,스쁘라브카-열람,예술공간 혜화,2023.11.25~\n2023.11.26
154,154,스위치 - 대전,작은극장 다함,2023.09.22~\n2024.01.01
155,155,스카프와 나이프,후암스테이지,2023.11.14~\n2023.11.16

In [ ]:
musical_rank = pd.read_csv('/data/raw/musical_rank_sample.csv', encoding='utf-8')
musical_rank = pd.DataFrame(musical_rank[:])
musical_rank

,Unnamed: 0,뮤지컬 이름,공연장,기간
0,0,뮤지컬 〈레베카〉 10주년 기념공연,블루스퀘어 신한카드홀,2023.08.19~\n2023.11.19
1,1,태양의서커스 〈루치아〉,잠실종합운동장 내 빅탑,2023.10.25~\n2023.12.17
2,2,뮤지컬 〈오페라의 유령〉 - 서울,샤롯데씨어터,2023.07.21~\n2023.11.19
3,3,뮤지컬 ＇벤허＇,LG아트센터 서울 LG SIGNATURE 홀,2023.09.02~\n2023.11.19
4,4,뮤지컬 〈멤피스〉,충무아트센터 대극장,2023.07.20~\n2023.10.22
...,...,...,...,...
151,151,하트시그널,대학로 하마씨어터(구 가든씨어터),2022.11.02~\n2023.11.30
152,152,한국문학뮤지컬 시리즈 I ‘메밀꽃필무렵’ - 대전,대전시립연정국악원 큰마당,2023.10.13~\n2023.10.14
153,153,K뮤지컬 〈정수정전〉 - 공주,공주문예회관 대공연장,2023.10.20~\n2023.10.20
154,154,PIUM Project 뮤지컬 갈라 콘서트 - 대전,대전예술의전당 아트홀,2023.10.12~\n2023.10.12
155,155,The Hook - 성남,한국잡월드 나래울극장,2023.11.30~\n2023.12.16

In [ ]:
play_string = play_rank['연극 이름'].apply(str)
musical_string = musical_rank['뮤지컬 이름'].apply(str)

In [ ]:
list = [37, 67, 70, 89, 131, 140]
for j in list:
  test_str = play_string[j]
  test_str = test_str.replace("［", "〈")
  test_str = test_str.replace("］", "〉")
  print(test_str)
  play_string[j] = test_str
#play_string[198] = m

공포연극 〈자취〉
〈연애하기 좋은 날 : 당근거래〉 - 전주
〈청소년극〉〈Tank ; 0-24〉
2023 제작연극 헉슬리〈멋진 신세계〉-대전
로맨틱연극〈연애하기좋은날:당근거래〉
문화가 있는 날 Ⅳ NT Live〈리어왕〉- 대전

In [ ]:
list = [24, 140, 141]
for j in list:
  test_str = musical_string[j]
  test_str = test_str.replace("［", "〈")
  test_str = test_str.replace("］", "〉")
  print(test_str)
  musical_string[j] = test_str
test_str = musical_string[130]
test_str = test_str.replace("「", "<")
test_str = test_str.replace("」", "<")
musical_string[130] = test_str

musical_string

이은결 〈더 일루션 - 마스터피스〉
이은결〈더 일루션 - 마스터피스〉- 고양
이은결〈더 일루션 - 마스터피스〉- 대구

0               뮤지컬 〈레베카〉 10주년 기념공연
1                      태양의서커스 〈루치아〉
2                뮤지컬 〈오페라의 유령〉 - 서울
3                          뮤지컬 ＇벤허＇
4                         뮤지컬 〈멤피스〉
                   ...
151                           하트시그널
152     한국문학뮤지컬 시리즈 I ‘메밀꽃필무렵’ - 대전
153                K뮤지컬 〈정수정전〉 - 공주
154    PIUM Project 뮤지컬 갈라 콘서트 - 대전
155                   The Hook - 성남
Name: 뮤지컬 이름, Length: 156, dtype: object

In [ ]:
play_string = play_string.str.replace(pat=r"［", repl=r'(', regex=True)
play_string = play_string.str.replace(pat=r"］", repl=r')', regex=True)
play_string = play_string.str.replace(pat=r'\([^)]*\)', repl="", regex=True)
play_string = play_string.str.replace(pat="연극", repl="")
#play_string = play_string.str.replace(pat=r"-")

In [ ]:
musical_string = musical_string.str.replace(pat=r"［", repl=r'(', regex=True)
musical_string = musical_string.str.replace(pat=r"］", repl=r')', regex=True)
musical_string = musical_string.str.replace(pat=r'\([^)]*\)', repl="", regex=True)
musical_string = musical_string.str.replace(pat="뮤지컬", repl="")

In [ ]:
i = 0
while(i<155):
  if(play_string.str.contains('-')[i]):
    play_string[i] = play_string[i].split("-")[0]
  if(play_string.str.contains("－")[i]):
    play_string[i] = play_string[i].split("－")[0]
  i += 1

In [ ]:
i = 0
while(i<155):
  if(musical_string.str.contains('-')[i]):
    musical_string[i] = musical_string[i].split("-")[0]
  if(musical_string.str.contains("－")[i]):
    musical_string[i] = musical_string[i].split("－")[0]
  i += 1

In [ ]:
import re
i = 0
while(i < 155):
  if(play_string.str.contains('〈')[i]):
    test_str = play_string[i]
    p = re.compile('〈[^)]+〉')
    try:
      m = p.findall(test_str)[0]
      play_string[i] = m
    except:
      i += 1
      continue
  i += 1

In [ ]:
import re
i = 0
while(i < 155):
  if(musical_string.str.contains('〈')[i]):
    test_str = musical_string[i]
    p = re.compile('〈[^)]+〉')
    try:
      m = p.findall(test_str)[0]
      musical_string[i] = m
    except:
      i += 1
      continue
  i += 1

In [ ]:
play_string = play_string.str.replace(pat=r"〈", repl=r'', regex=True)
play_string = play_string.str.replace(pat=r"〉", repl=r'', regex=True)
#play_string = play_string.str.replace(pat=r" ", repl=r'', regex=True)

In [ ]:
musical_string = musical_string.str.replace(pat=r"〈", repl=r'', regex=True)
musical_string = musical_string.str.replace(pat=r"〉", repl=r'', regex=True)
#musical_string = musical_string.str.replace(pat=r" ", repl=r'', regex=True)

In [ ]:
play_list = pd.DataFrame(play_string)
musical_list = pd.DataFrame(musical_string)

In [ ]:
now = datetime.datetime.now()
play_list.to_csv("/data/raw/play_refine" + now.strftime('%Y-%m-%d') + ".csv", encoding='utf-8')
musical_list.to_csv("/data/raw/musical_refine" + now.strftime('%Y-%m-%d') + ".csv", encoding='utf-8')

## play_rank, musical_rank 읽기

In [ ]:
import pandas as pd
play_refine= pd.read_csv('/data/raw/play_refine2023-10-12.csv', encoding='utf-8')
play_refine = pd.DataFrame(play_refine['연극 이름'])
play_refine

              연극 이름
0        너의 목소리가 들려
1            쉬어매드니스
2               행오버
3         바닷마을 다이어리
4              한뼘사이
..              ...
151  섹시코미디 나의PS파트너
152    쇼팔다 미친 유령 극단
153           스쁘라브카
154            스위치
155        스카프와 나이프

[156 rows x 1 columns]

In [ ]:
musical_refine = pd.read_csv('/data/raw/musical_refine2023-10-12.csv', encoding='utf-8')
musical_refine = pd.DataFrame(musical_refine['뮤지컬 이름'])
musical_refine

                    뮤지컬 이름
0                      레베카
1                      루치아
2                  오페라의 유령
3                     ＇벤허＇
4                      멤피스
..                     ...
151                  하트시그널
152   한국문학 시리즈 I ‘메밀꽃필무렵’
153                   정수정전
154  PIUM Project  갈라 콘서트
155          The Hook - 성남

[156 rows x 1 columns]

In [ ]:
play_rank = pd.read_csv('/data/raw/play_rank2023-10-09.csv', encoding='utf-8')
play_rank = pd.DataFrame(data=play_rank[:156], columns=['공연장', '기간'])
play_rank

                     공연장                       기간
0                 도토리씨어터  2023.04.03~\n2023.10.31
1    콘텐츠박스(KONTENTZ BOX)  2015.11.12~\n2023.10.31
2                    정극장  2023.05.01~\n2023.10.31
3            예술의전당 자유소극장  2023.10.08~\n2023.11.19
4                  라온아트홀  2017.03.01~\n2023.10.31
..                   ...                      ...
151                소명아트홀  2023.12.01~\n2023.12.31
152              수유연극실험실  2023.09.01~\n2023.10.15
153              예술공간 혜화  2023.11.25~\n2023.11.26
154              작은극장 다함  2023.09.22~\n2024.01.01
155               후암스테이지  2023.11.14~\n2023.11.16

[156 rows x 2 columns]

In [ ]:
musical_rank = pd.read_csv('/data/raw/musical_rank2023-10-09.csv', encoding='utf-8')
musical_rank = pd.DataFrame(data=musical_rank[:156], columns=['공연장', '기간'])
musical_rank

                          공연장                       기간
0                 블루스퀘어 신한카드홀  2023.08.19~\n2023.11.19
1                잠실종합운동장 내 빅탑  2023.10.25~\n2023.12.17
2                      샤롯데씨어터  2023.07.21~\n2023.11.19
3    LG아트센터 서울 LG SIGNATURE 홀  2023.09.02~\n2023.11.19
4                  충무아트센터 대극장  2023.07.20~\n2023.10.22
..                        ...                      ...
151        대학로 하마씨어터(구 가든씨어터)  2022.11.02~\n2023.11.30
152             대전시립연정국악원 큰마당  2023.10.13~\n2023.10.14
153               공주문예회관 대공연장  2023.10.20~\n2023.10.20
154               대전예술의전당 아트홀  2023.10.12~\n2023.10.12
155               한국잡월드 나래울극장  2023.11.30~\n2023.12.16

[156 rows x 2 columns]

In [ ]:
play_DF = pd.concat([play_refine, play_rank], axis=1)
musical_DF = pd.concat([musical_refine, musical_rank], axis=1)

## playDB 크롤링

In [ ]:
driver.get("http://www.playdb.co.kr/Index.asp")
time.sleep(3)
driver.find_element(By.XPATH, '//*[@id="HDQuery"]').send_keys(play_DF['연극 이름'][i])
driver.find_element(By.XPATH, '//*[@id="HDQuery"]').send_keys(Keys.ENTER)
time.sleep(3)
info_time = play_DF['기간'][i].split("~")[0]
info_time=datetime.strptime(info_time,'%Y.%m.%d')
comp_time = driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table[1]/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[2]/td[1]').text
comp_time=comp_time.split(" ")[0]
comp_time = datetime.strptime(comp_time,'%Y/%m/%d')

In [ ]:
def playDB(DF, ran, i):
  if(ran == 0):
    print("Search None");
  elif(ran == 1):
    driver.find_element(By.XPATH, '//*[@id="dvSpecial"]/table/tbody/tr[2]/td/table/tbody/tr[2]/td[3]/table/tbody/tr[1]/td/table/tbody/tr[2]/td/b/a')
  else:
    for j in range(1, int(ran)):
      place = driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table['+str(j)+']/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[2]/td[2]/a').text
      if(DF['공연장'][i] == place):
          driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table['+str(j)+']/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[1]/td[1]/b/a').click()
          time.sleep(3)
          driver.find_element(By.XPATH, '//*[@id="Tab2"]').click()
          try:
            print(driver.find_element(By.XPATH, '/html/body/table/tbody/tr[2]/td/table/tbody/tr[3]/td').text)
            break
          except:
            print("Explain None")

In [ ]:
def info_news(driver):
  try:
    time.sleep(3)
    driver.find_element(By.XPATH, '//*[@id="contents"]/div[1]/div[1]/ul[1]/li[2]/a').click()
    iframe_element = driver.find_element(By.ID, "iFrmContent")  # iframe의 id를 사용하여 찾는 예시
    driver.switch_to.frame(iframe_element)
    text = driver.find_element(By.XPATH, '/html/body/table/tbody/tr[2]/td/table/tbody/tr[3]/td').text
  except:
    text = ""
  return text

In [ ]:
play_DF['연극 이름'][i]

'너의목소리가들려'

In [ ]:
import datetime
now = datetime.datetime.now()

In [ ]:
import re
from datetime import datetime, timedelta
play_info = []
for i in range(156):
  driver.get("http://www.playdb.co.kr/Index.asp")
  time.sleep(3)
  driver.find_element(By.XPATH, '//*[@id="HDQuery"]').send_keys(play_DF['연극 이름'][i])
  driver.find_element(By.XPATH, '//*[@id="HDQuery"]').send_keys(Keys.ENTER)
  time.sleep(3)

  try:
    ran = driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[1]/td/table/tbody/tr/td[2]/b').text
    ran = re.sub(r'[^0-9]', '', ran)
  except:
    try:
      driver.find_element(By.XPATH, '//*[@id="wrap"]/table/tbody/tr[3]/td/table/tbody/tr/td[1]/table[2]/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr[2]/td/div/b')
      ran = 0
    except:
      ran = 2

  if(ran == 0):
    print("Search None");
    text = "None"
  elif(ran == 2):
    driver.find_element(By.XPATH, '//*[@id="dvSpecial"]/table/tbody/tr[2]/td/table/tbody/tr[2]/td[3]/table/tbody/tr[1]/td/table/tbody/tr[2]/td/b/a').click()
    text = info_news(driver)
    print(text)
  else:
    info_time = play_DF['기간'][i].split("~")[0]
    info_time=datetime.strptime(info_time,'%Y.%m.%d')
    for j in range(1, int(ran)):
      comp_time = driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table['+str(j)+']/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[2]/td[1]').text
      comp_time=comp_time.split(" ")[0]
      comp_time = datetime.strptime(comp_time,'%Y/%m/%d')
      place = driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table[' +str(j) + ']/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[2]/td[2]/a').text
      if(len(place) >= len(play_DF['공연장'][i])):
        if((place.find(play_DF['공연장'][i]) >= 0) or (comp_time == info_time)):
          driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table['+str(j)+']/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[1]/td[1]/b/a').click()
          time.sleep(3)
          text = info_news(driver)
          print(text)
          break
      else:
        if((play_DF['공연장'][i].find(place) >= 0) or (comp_time == info_time)):
          driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table['+str(j)+']/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[1]/td[1]/b/a').click()
          time.sleep(3)
          text = info_news(driver)
          print(text)
          break
      if(comp_time < info_time):
        text = "None"
        print("Search None")
        break
  play_info.append(text)
play_info_DF = pd.DataFrame(play_info)
play_DF = pd.concat([play_refine, play_rank, play_info_DF], axis=1)
play_DF.to_csv("/data/raw/play_info_DF_new" + now.strftime('%Y-%m-%d') + ".csv", encoding='utf-8')

모든 일은 파라다이스 호텔 506호에서 시작된다.
남편(철수)의 외도를 알게 된 지연(부인)은 이벤트 업체를 이용해서 남편에게 사과를 받고 싶어한다.
이벤트 업체 대표 태민은 지연의 계획대로 철수에게 사과를 받아보려고 했지만,
만취한 철수는 지연을 506호에서 살해한다.
당황한 이벤트 업체 대표 태민은 철수를 급하게 507호로 옮기고 4시간만 대실한다.
술이 깬 철수에게 지난 밤 일을 설명하지만, 철수는 기억나지 않는다.
506호 살인 사건을 조사 중인 경찰이 507호를 방문하지만,
태민의 임기응변으로 위기를 넘긴다.
그런데, 507호에는 다른 2명이 더 있다.
초능력이 있다고 주장하는 508호 케이(남)
자살하기 위해 호텔을 찾은 509호 엠마(여)
케이와 엠마 두명 역시 술을 먹고 깨어보니 507호라는 황당한 말을 전한다.
507호에 만난 태민, 철수, 케이, 엠마!
만약, 경찰이 507호로 들이닥치면 4명 모두 공범이 되는 상황.
이런 말도 안되는 상황을 믿어 줄 경찰은 없다.
4명은 서로를 의심하며 서로에게 자백을 강요하기 시작하는데...
이들 4명에게 주어진 시간은 대실 4시간!
4시간 안에 모든 것을 밝혀내야 되는 상황에서
4명의 비밀이 하나씩 드러난다.

'서로에게 진정한 가족이 되어가는 자매들의 성장 이야기'
연극 <바닷마을 다이어리>는 일본의 영화인 ‘바닷마을 다이어리(海街 Diary)’를 원작으로 한 작품이다.
2015년 칸 영화제 경쟁부문에 초청되고 많은 일본의 영화제에 수상 이력이 있는 만큼 탄탄한 스토리를 가지고 있으며,
자극적이지는 않지만 깊은 위로를 주는 작품이라는 극찬을 받았다.
‘바닷마을 다이어리’ 한국 초연을 위해 연극 각색에 능통한 황정은 작가와 다수의 연극 무대화 경험이 있는 이준우 연출이 개발 과정에 참여를 하면서
아버지와 어머니의 부재, 연인과의 헤어짐, 소중한 사람의 죽음 등으로
어딘가 결여 되어있던 네 자매들의 마음이 서로를 통해 채워지고 위로를 받으며
진정한 가족이 되어가는 모습을 연극에서도 잘 표현할 예정이다.

어느덧 도둑질 33주년! 오늘도, 쉴 새 없이 턴다!
대한민국 No.1 오리지널 코믹극 연극 <늘근도둑이야기>

［View Point］
초단위로 빵빵 터지는 애드리브 맛집이 바로 여기!
관객과 소통하며, 함께 공연을 완성해나가는 연극의 재미와 웃음을 경험할 수 있는 대학로 유일무이 연극!

뻔한 로코가 지겨운 당신의 탁월한 선택!
부조리한 세상에 날리는 사이다 돌직구! 안타까운 세태를 꼬집는 통렬한 웃음!
흥행불변 대학로 코미디 연극의 오리지널이 돌아왔다!

환장 케미를 선사하는 환상의 콤비!
이성민, 강신일, 김원해 등 수많은 명배우들이 거쳐간 연극 <늘근도둑이야기>


서울 종로구 창신동, 보증금 500-월세 30!
서울 시내가 다 보이는 옥탑방!
보증금 다 박고 서울 상경한 작가 지망생 정은과
월세 선불 내고 집 나온 건축학도 경민!
이중계약으로 엮인 두 청춘남녀의 버라이어티한 옥탑방로맨스!
Search None





‘우리 모두는 역사의 수혜자이자 창조자다.’

일제 강점기라는 혹독한 시절,
널리 알려진, 또는 아무도 모르게 청춘을 바친 이들이 있었다.

애국과 매국을 강요받고, 혹은 선택하며
시대의 소용돌이에 삶을 던질 수밖에 없었던 모든 청춘들을 위한 작품.
출입구부터 무대까지 관객의 눈길과 손길이 닿는 곳은 모두가 공포의 현장이 된다.
그동안 공포연극이 갖고 있던 고정관념과 패러다임을 모조리 [스위치]한, 무대 위에서 생생하게 되살아나는 4D공포의 개막! 누구나 생각할 수 있지만 아무나 따라할 수 없는 감각적이고 화려한 공포의 결정판!





DAC Artist 진해정은 연극 작업을 통해 사회의 중심부에서 밀려나 주변부에 갇혀야 했던, 그로 인해 스스로의 목소리를 잃은 채 살아가고 있는 이들의 삶을 주목해왔다. <러브 앤 인포메이션>은 영국 극작가 카릴 처칠의 2012년 작품이다. 이 작품은 총 7개의 대표 · 랜덤 섹션 안에 2~5분 가량의 76개 짧은 장면들과 100명이 넘는 인물들로 구성되어 있다. 이를 통해 통제할 수 없을 정도로 범람하는 정보들, 그 세계 내부를 표류하는 인류의 풍경을 담는다. 구체적인 발화인이 지정되지 않는 대사, 젠더의 구분이 없는 장면 등은 10년이 지난 작품임에도 불구하고 동시대와 사랑, 과학과 언어에 대한 사유를 일상적 언어로 충분히 녹여낸다. 진해정은 정보사회에 존재하는 다양한 사태와 징후를 다룬 퍼즐 같은 텍스트를 연출하며 동시대 인간의 인식 변화와 관계에 대해 질문한다.

Search None

Search None

Search None


근대 이후 산업재해로 손실된 노동자의 몸, 그들의 폐기된 육신을 상상한다!
말끔하게 정리된 듯한 이 세계에 지속적으로 쌓여가는 고통의 흔적.
그 침묵당한 목소리를 극장 안으로 소환, 그들과 대화를 시도한다.

새로운 몸, ‘괴물B’의 탄생
오늘, 세계는 거대한 쓰레기장이다. 산업화와 자본주의의 발달로 일부 인간은 부유해졌다. 그러나 그 댓가는 폐기물로 남았고, 사물뿐 아니라 산업화 과정에서 유실된 노동하는 몸의 조각들도 거기 섞여 있다. ‘괴물B’는 유실되고 버려진 몸, 노동으로 고통받은 몸의 조각들이 결합돼 만들어진 하나의 새로운 종(種)이다.

B의 몸 각 부분은 하나의 시간, 하나의 기억, 계속되는 현재
‘괴물B’의 몸은 한국의 산업화 및 자본주의 역사에 관한 기억을 고스란히 담고 있다. 기계에 끼여 잘려나간 누군가의 팔과 다리, 공장 화재로 타버린 누군가의 젖가슴, 누군가의 폐와 간... B는 이들 육신의 파편들로 인해 존재하며, 각 파편들이 담고 있는 고통의 시간에서 자유롭지 않다. 사라진 과거들이 B의 현재를 이룬다.

B의 현재는 고통의 반복, 죽고 싶어도 죽을 수 없다
몸의 각 부분이 사고의 순간을 상기하며 고통스러워할 때마다 B는 참을 수 없는 고통에 시달린다. 그를 이루는 몸의 실제 주인들은 늙어서, 기억을 잃어서, 혹은 기억이 희미해져서 고통의 순간으로부터 멀어졌지만 B를 조직하는 몸들은 오직 그 고통의 순간 속에서만 존재한다.







Search None
Search None





Search None

Search None


Search None
Search None
서울국제공연예술제(SPAF, Seoul Performing Arts Festival)는 국내 최대 규모와 역사를 자랑하는 한국의 대표 국제공연예술축제로, (재)예술경영지원센터가 주촤허고 문화체육관광부와 한국문화예술위원회가 후원한다.
올해로 23회를 맞는 2023 서울국제공연예술제는 10월 6일(금)부터 10월 29일(일)까지 국립중앙극장 해오름극장, 국립정동극장_세실, 대학로아르코예술극장, 여행자극장에서 개최된다.

Search None
Search None
Search None
Search None
Search None
Search None
Search None
Search None
Search None
Search None
Search None


피아니스트 이난주는 숙명여자대학교 음악대학 피아노과를 수석입학 및 수석졸업하고, 미국 University of Colorado(Boulder)에서 음악석사(M.M.) 및 연주박사(D.M.A.) 학위를 취득하였다. 숙명여자대학교 4년 동안 전액 장학금과 삼익악기 장학금을 받았으며, University of Colorado에서는 Graduate Scholarship을 수여받았다. 그의 연주는 미국에서도 두각을 나타내어 Vice Chancellor's Competition 우승, Colorado 주에서 열린 Music Teachers National Association Competition에 입상하였고, 활동영역을 넓혀 Arkansas Music Festival, Adamant Music School Summer Camp, TCU/Cliburn Piano Institute, Victoria JISA Music Festival 등 미국과 캐나다의 Music Festival에 꾸준히 참가하여 연주하였다.
미국 유학 중 9회의 독주회와 다수의 실내악 및 듀오 연주회, University of Colorado 주최 Bach, Mozart, Beethoven Festival에 출연하였고, Boulder Library Concert Series에 초청되어 연주하였다. 또한 University of Colorado 합창단 반주자로 다양한 활동을 하였다.
신춘음악회, 귀국독주회를 시작으로 한국듀오협회 정기연주회, 평택대 교수음악회, 피아노 앙상블 연구회 정기연주회, 숭의여대 교수음악회, 그랜드 피아노 콘서트, 클래식 나들이 청소년 음악회, 서울 피아스트라 정기연주회, 한?루 수교 11주년 친선음악제에 초청되어 루마니아와 한전아츠풀센터에서 Transilvania 주립 오케스트라와 협연하는 등 활발하고 폭넓은 연주활동을 하고 있다. 최효열, 주혜정, Alvin Chow, Angela Cheng을 사사하였고, 미국 University of Colorado의 Applied Music Course 강사 및 동 대학 평생교육원 강사, 국립 안동대학교 대학원, 평택대학교 강사를 역임하였고, 현재 숙명여자대학교 및 대학원, 안양대학교, 삼육대학교, 숭의여대에 출강하여 후진양성에 힘쓰고 있으며, 서울 피아스트라 이사로 활동하고 있다.
DAC Artist 진해정은 연극 작업을 통해 사회의 중심부에서 밀려나 주변부에 갇혀야 했던, 그로 인해 스스로의 목소리를 잃은 채 살아가고 있는 이들의 삶을 주목해왔다. <러브 앤 인포메이션>은 영국 극작가 카릴 처칠의 2012년 작품이다. 이 작품은 총 7개의 대표 · 랜덤 섹션 안에 2~5분 가량의 76개 짧은 장면들과 100명이 넘는 인물들로 구성되어 있다. 이를 통해 통제할 수 없을 정도로 범람하는 정보들, 그 세계 내부를 표류하는 인류의 풍경을 담는다. 구체적인 발화인이 지정되지 않는 대사, 젠더의 구분이 없는 장면 등은 10년이 지난 작품임에도 불구하고 동시대와 사랑, 과학과 언어에 대한 사유를 일상적 언어로 충분히 녹여낸다. 진해정은 정보사회에 존재하는 다양한 사태와 징후를 다룬 퍼즐 같은 텍스트를 연출하며 동시대 인간의 인식 변화와 관계에 대해 질문한다.

피아니스트 이난주는 숙명여자대학교 음악대학 피아노과를 수석입학 및 수석졸업하고, 미국 University of Colorado(Boulder)에서 음악석사(M.M.) 및 연주박사(D.M.A.) 학위를 취득하였다. 숙명여자대학교 4년 동안 전액 장학금과 삼익악기 장학금을 받았으며, University of Colorado에서는 Graduate Scholarship을 수여받았다. 그의 연주는 미국에서도 두각을 나타내어 Vice Chancellor's Competition 우승, Colorado 주에서 열린 Music Teachers National Association Competition에 입상하였고, 활동영역을 넓혀 Arkansas Music Festival, Adamant Music School Summer Camp, TCU/Cliburn Piano Institute, Victoria JISA Music Festival 등 미국과 캐나다의 Music Festival에 꾸준히 참가하여 연주하였다.
미국 유학 중 9회의 독주회와 다수의 실내악 및 듀오 연주회, University of Colorado 주최 Bach, Mozart, Beethoven Festival에 출연하였고, Boulder Library Concert Series에 초청되어 연주하였다. 또한 University of Colorado 합창단 반주자로 다양한 활동을 하였다.
신춘음악회, 귀국독주회를 시작으로 한국듀오협회 정기연주회, 평택대 교수음악회, 피아노 앙상블 연구회 정기연주회, 숭의여대 교수음악회, 그랜드 피아노 콘서트, 클래식 나들이 청소년 음악회, 서울 피아스트라 정기연주회, 한?루 수교 11주년 친선음악제에 초청되어 루마니아와 한전아츠풀센터에서 Transilvania 주립 오케스트라와 협연하는 등 활발하고 폭넓은 연주활동을 하고 있다. 최효열, 주혜정, Alvin Chow, Angela Cheng을 사사하였고, 미국 University of Colorado의 Applied Music Course 강사 및 동 대학 평생교육원 강사, 국립 안동대학교 대학원, 평택대학교 강사를 역임하였고, 현재 숙명여자대학교 및 대학원, 안양대학교, 삼육대학교, 숭의여대에 출강하여 후진양성에 힘쓰고 있으며, 서울 피아스트라 이사로 활동하고 있다.
Search None
Search None
Search None


Search None









Search None
Search None

Search None
Search None

Search None








Search None

















돌아온 극단 우의 로맨틱 코미디. 그동안의 로맨틱 코미디는 잊어라! 우리에게 벌어지는 누구에게나 한 번쯤 찾아올 그날의, 타이밍 새로운 신개념 공감형 연극. 한국에서 벌어지는 20, 30세대6가지의 연애 스토리 <응답하라 20.30>

돌아온 극단 우의 로맨틱 코미디. 그동안의 로맨틱 코미디는 잊어라! 우리에게 벌어지는 누구에게나 한 번쯤 찾아올 그날의, 타이밍 새로운 신개념 공감형 연극. 한국에서 벌어지는 20, 30세대6가지의 연애 스토리 <응답하라 20.30>

Search None






Search None


Search None


Search None


Search None


2023년 대한민국 연극제 대상 작품
전쟁이라는 특수한 상황 속에 개인, 특히 약자인 여성은 어떠한 선택을 할 수 있었을까?
한국전쟁 당시 전북 임실군 옥정호 인근의 배소고지에서 벌어진 양민학살 생존자의 구술 기록을 토대로 작가 진주의 깊은 고찰과 함께 창작된 연극 배소고지 이야기
여성들이 살아남기 위한 그 ‘선택’의 폭이 얼마나 좁고 폭력적인 상황에 놓여 있었는지를 이야기 한다.
밀양의 한적한 골목에서 헌책방 ‘우리책방’ 을 운영하던 할아버지 ‘경호’는, 사람들의 발길이 끊긴 책방의 폐업을 준비한다.

아끼던 책을 하나씩 묶어 버리던 어느 날, 할머니 ‘두향’이 책방의 책을 주웠다며 책방을 찾는다.

두향은 자신을 18세라 소개하며 경호에게 한글을 알려달라고 한다.

첫사랑에게 편지를 쓰기 위해 한글을 배우려는 두향과, 51년 전 두향의 첫사랑이었던 경호…

두 사람은 오래전, 18세부터의 기억을 천천히 더듬기 시작한다.
연극 <부동산 오브 슈퍼맨>은 금융자본주의 시대, 슈퍼맨이 자신의 전세보증금을 지키고 더 나은 집에 살기 위해 고군분투하는 스펙터클 어드벤처 대서사시입니다.
Search None



Search None
“정착하는 마음으로”

어떻게 해서든 정착을 해야겠다는 각오를 하게 된 이유가 있었습니다. 각박한 현실은 연극인이라는 정체성을 시도 때도 없이 뒤흔들곤 하였습니다. 첫 출발은 분명한 목표를 가지고 출발했다고 생각하였지만 정신차리고 보면 이 사회 속에서 그저 떠돌고 있는 유령이 되어있었습니다. 이대로 가다간 내 삶도, 연극인으로서의 삶도 흐려질 것만 같았기에 약간의 무모함과 케케묵었던 용기를 가지고 연극 공간을 만들고야 말았습니다.
 계약서에 서명을 한 뒤 문득, 빈 공간을 바라보니 그것 자체가 굉장한 큰 위안과 힘이 되었고, 무언가를 시도할 수 있다는 기대감과 상상력이 커졌습니다.

 수유연극실험실을 만들어가면서 평소 생각지도 않았던 한 작품이 떠올랐습니다. 바로, 류보미르 시모비치의 <쇼팔로비치 유랑극단> 입니다. 먼 이야기로 느껴졌던 유랑극단의 삶과 정착하기 전 나의 삶과 겹쳐 보였습니다. 먹고 잘 수 있는 집이 있고, 돈을 벌 수 있는 직장도 있지만 연극을 하기 위해 두 발바닥 온전히 붙일 만한 곳을 찾지 못해 그랬을까요?

"나는 어쩌면 현실판 유랑극단이 아니었을까?"

연극을 하고 싶었고 연극을 계속해서 해 나아가고 싶었으며 연극을 함께 만들어 갈 사람들이 필요했습니다. 지속 가능한 연극 작업을 원했던 간절함으로 수유연극실험실을 만들었고, 연극에 간절한 사람들을 불러 모은 이 마음을 개관 기념 공연에 담고 싶었습니다.

<쇼팔다 미친 유령 극단>을 직접 각색하였지만 이들이 연극하는 마음은 역할을 수행하는 실제 배우들의 마음으로 채워지길 바랍니다 이는 곧 수유연극실의 마음이기도 합니다. 이 뜨거운 마음을 지켜봐주시겠습니까?

NameError: ignored

In [ ]:
play_info_DF = pd.DataFrame(play_info)
play_DF = pd.concat([play_refine, play_rank, play_info_DF], axis=1)
play_DF.to_csv("/data/raw/play_info_DF" + now.strftime('%Y-%m-%d') + ".csv", encoding='utf-8')

In [ ]:
import re
from datetime import datetime, timedelta
musical_info = []
for i in range(156):
  driver.get("http://www.playdb.co.kr/Index.asp")
  time.sleep(3)
  driver.find_element(By.XPATH, '//*[@id="HDQuery"]').send_keys(musical_DF['뮤지컬 이름'][i])
  driver.find_element(By.XPATH, '//*[@id="HDQuery"]').send_keys(Keys.ENTER)
  time.sleep(3)

  try:
    ran = driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[1]/td/table/tbody/tr/td[2]/b').text
    ran = re.sub(r'[^0-9]', '', ran)
  except:
    try:
      driver.find_element(By.XPATH, '//*[@id="wrap"]/table/tbody/tr[3]/td/table/tbody/tr/td[1]/table[2]/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr[2]/td/div/b')
      ran = 0
    except:
      ran = 2

  if(ran == 0):
    print("Search None");
    text = "None"
  elif(ran == 2):
    driver.find_element(By.XPATH, '//*[@id="dvSpecial"]/table/tbody/tr[2]/td/table/tbody/tr[2]/td[3]/table/tbody/tr[1]/td/table/tbody/tr[2]/td/b/a').click()
    text = info_news(driver)
    print(text)
  else:
    info_time = musical_DF['기간'][i].split("~")[0]
    info_time=datetime.strptime(info_time,'%Y.%m.%d')
    driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[1]/td/table/tbody/tr/td[3]/div/a').click()
    time.sleep(3)
    for j in range(1, int(ran)):
      comp_time = driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table['+str(j)+']/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[2]/td[1]').text
      comp_time=comp_time.split(" ")[0]
      comp_time = datetime.strptime(comp_time,'%Y/%m/%d')
      place = driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table[' +str(j) + ']/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[2]/td[2]/a').text
      if(len(place) >= len(musical_DF['공연장'][i])):
        if((place.find(musical_DF['공연장'][i]) >= 0) or (comp_time == info_time)):
          driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table['+str(j)+']/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[1]/td[1]/b/a').click()
          time.sleep(3)
          text = info_news(driver)
          print(text)
          break
      else:
        if((musical_DF['공연장'][i].find(place) >= 0) or (comp_time == info_time)):
          driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table['+str(j)+']/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[1]/td[1]/b/a').click()
          time.sleep(3)
          text = info_news(driver)
          print(text)
          break
      if(comp_time < info_time):
        text = "None"
        print("Search None")
        break
  musical_info.append(text)
musical_info_DF = pd.DataFrame(musical_info)
musical_DF = pd.concat([musical_refine, musical_rank, musical_info_DF], axis=1)
musical_DF.to_csv("/data/raw/musical_info_DF_new" + now.strftime('%Y-%m-%d') + ".csv", encoding='utf-8')

더 이상 수식어가 필요 없는 가장 완벽한 뮤지컬!

역사적 10주년 기념공연으로 돌아온 대체불가 ‘메가 스테디셀러’
약 13개국, 11개 언어로 공연되며 전 세계 2,100만 관객을 전율케 한 초대형 흥행작!
2013년 한국 초연 이후, 2022년 여섯 번째 시즌까지 누적 관람객 95만명 기록!

스릴러의 거장 히치콕의 영화로도 유명한 <레베카>!
감동적인 로맨스, 반전을 거듭하는 서스펜스, 강력한 킬링 넘버!
유럽 뮤지컬 레전드! 극작가 미하엘 쿤체(Michael Kunze)와 작곡가 실베스터 르베이(Sylvester Levay)의 ‘마스터 피스’

영국의 대표 작가 대프니 듀 모리에의 소설을 원작으로,
스릴러의 거장 알프레도 히치콕의 동명의 영화로도 유명한 뮤지컬 <레베카>!
원작을 뛰어넘는 뮤지컬의 탄생이라 불리며 전세계에서 사랑받아온 대작!
숨막히도록 아름다운 대저택의 비밀이 밝혀진다!

대한민국 초연 10주년 기념 무대를 꾸밀 대한민국 최정상 스태프와 압도적인 완벽 캐스팅 라인업!

총괄프로듀서 엄홍현, 연출 로버트 요한슨, 음악감독 김문정 등 국내외 최고의 스태프 총망라!
류정한, 민영기, 에녹, 신영숙, 옥주현, 리사, 장은아, 김보경, 이지혜 등 지난 시즌의 히어로들과
테이, 이지수, 웬디 등 뉴 캐스팅으로 한층 업그레이드된, 단 한 순간에 관객을 매혹시킬 <레베카> 10주년 기념 공연!

13년 간의 긴 기다림…
마침내 한국의 유령이 온다!

환영과도 같은 무대
사라지지 않을 영원한 당신의 첫 감동!
13년 만에 오페라 하우스의 문이 열린다
대한민국 창작 뮤지컬의 압도적 수작의 귀환!
제2회 한국뮤지컬어워즈 대상, 무대예술상, 앙상블상 수상 및 11개 부문 노미네이트!
제6회 에그린뮤지컬어워드 앙상블상 수상!
작품성과 대중성을 모두 만족시킨 대작!
한국 창작 뮤지컬의 새로운 기준을 정립한 수작이 돌아온다!

월드클래스 창작 뮤지컬 명가 EMK의 제작 노하우가 더해져 새롭게 탄생할 <벤허>!
웅장한 경기장에서 펼쳐지는 마지막 전차 경주!
파노라마처럼 펼쳐지는 생생한 수중 탈출 장면!
한 편의 액션 영화처럼 역동적이고 박진감 넘치는 볼거리!
EMK가 만들어낼 단 하나의 무대, 한국 뮤지컬 기술력의 정수를 만난다!

시대를 뛰어넘은 명작의 재탄생!
1880년 소설, 1959년 명작의 반열에 오른 영화 <벤허>
100년이 넘는 시간 동안 증명된 콘텐츠 파워!
시대와 언어를 뛰어넘은 명작이 돌아온다!
전세계 유수 시상식 석권하며 작품성 인정
토니 어워즈 최우수 작품상, 음악상, 각본상, 오케스트레이션상 수상
드라마 데스크 어워즈 최우수작품상, 여우주연상, 오케스트레이션상 수상
로렌스 올리비에 어워즈 최우수 안무상, 음향상 수상

토니 어워즈 수상 창작진의 위대한 만남
토니 어워즈 각본상 출신 극작가 <올슉업>, <아이 러브 유>의 조 디피에트로
토니 어워즈 음악상 출신 작곡가 & 본 조비 키보디스트 데이비드 브라이언 히트
토니 어워즈 안무상 최초 히스패닉 수상자 안무가 세르지오 트루히요

작품성과 대중성을 동시에 완성시킬 국내 최고 창작진 총집합
<리지>, <매디슨 카운티의 다리>, <팬레터> 등 섬세하면서도 독창적인 김태형 연출
한국뮤지컬어워즈 수상 경력 양주인 음악 감독과 이현정 안무 감독
감각적인 조수현 무대 영상 디자이너, 마선영 조명 디자이너, 안현주 의상 디자이너

올 여름 멤피스 열풍을 불러일으킬 최정상 배우들의 향연
뮤지컬 명품 보컬리스트 박강현, 고은성
예능 대세 블루칩이자 뮤지컬계 신성 이창섭
대한민국 최고 디바 정선아, 유리아, 손승연
연기내공 만렙 배우 최민철, 심재현, 최정원, 류수화 등
Groundbreaking on Broadway!

푸치니의 오페라 <라보엠>을 현대화한 록 뮤지컬!
에이즈, 동성애, 마약중독 등 파격적 소재와 록, R＆B, 탱고, 발라드, 가스펠 등 다양한 음악의 향연!
오프-브로드웨이 초연 하루 전 요절한 천재 극본, 작곡, 작사가 조나단 라슨의 자전적 이야기!


Iconic!
Revolutionary Musical

브로드웨이에서 12년간 5123회 공연, 전세계 50개국 25개의 언어로 무대화. 브로드웨이에서 11번째로 롱런한 뮤지컬!
뉴스위크지 표지 장식, 퓰리처상과 토니상 베스트 뮤지컬 상 동시 석권!
‘RENT-HEADS’라는 팬덤을 창조하며 대중문화(Pop Culture) 현상으로 자리 잡은 수작!


Return with Breathtaking Casting!

렌트, 3년만에 크리스마스 시즌을 맞아 다시 돌아오다!
지난 시즌, 관객들의 열렬한 지지를 받았던 장지후, 정원영, 배두훈, 김호영, 임정모, 전나영, 정다희와 백형훈, 김환희, 이지연, 윤형렬, 조권, 김수연, 배수정, 구준모 등 신진 세력이 함께 만들어갈 열정의 무대!
브로드웨이 렌트의 해외 협력 연출 앤디 세뇨르 주니어가 선사하는 젊은이들의 사랑, 우정, 고뇌와 치열함, 그리고 용기가 가득한 이야기


［PRESS REVIEW］

명작은 유행을 타지 않는다. 삶은 일방적으로 흐르지만, 가치는 떠내려가지 않는다.
- 뉴시스 이재훈기자

좋은 노래에 공감력을 부여하는 건 ‘렌트’의 동시대성이다. 1990년대 뉴욕을 배경으로 한 작품이지만 사회 불평등과 기성체제에 저항하는 지금 우리나라 젊은이들 모습과 크게 다를 바 없다.
- 세계일보 박성준기자

수식어가 필요 없는, ‘역시 렌트’였다. 무대 위 파격과 도발은 여전했고, 젊은이들의 꿈과 방황·사랑이 빚어내는 메시지의 울림은 더욱 크게 느껴졌다.
- 서울경제 송주희기자

친구들. 흔들리고, 섣부르고 때로는 불안한 청춘들의 삶이 계속되는 한, 렌트의 가치는 ‘불멸’(不滅)하다. 뮤지컬의 ‘상징’ 같은 작품.
- 이데일리 윤종성기자

전 세계 최초 뮤지컬화!
미겔 데 세르반테스 상, 국립문학상, 마리아 롤란드상 등 수많은 상을 수상한 스페인 희곡의 거장, 안토니오 부에로 바예호(Antonio Buero Vallejo) 첫 번째 희곡 ‘타오르는 어둠 속에서(In The Burning Darkness)가 세계 최초 뮤지컬로 재탄생하다!

각색과 연출 성종완, 작곡/음악감독 김은영
뮤지컬 <사의찬미>, <웨스턴 스토리>에 이어 또 한 번 기대되는 두 창작자의 시너지로 완성도 높은 창작 뮤지컬을 선보인다!


세 발의 총성, 사라진 내일, 갈 수 없는 나라
오늘을 살아가는 모두에게 건네는 불씨
뮤지컬 <곤 투모로우>

갑신정변이라는 근대적 개혁운동을 일으켰으나 3일 만에 실패하고
결국 암살당한 김옥균의 이야기를 모티브로 작가적 상상력을 더해 새롭게 재창조!

인물의 심리를 극적으로 표현한 음악과 격변기의 거대한 소용돌이를 표현한 무대
시대의 흐름과 인물의 감정을 극대화하며, 영화를 보는 듯한 미장센의 감각적인 조명과 영상,
절도 있고 감각적인 안무, 탄탄한 드라마와 섬세한 인물 표현,
시대와 나라를 초월하는 컨템포러리 형식의 세련된 연출!

시대를 초월하는 묵직한 울림으로 깊은 감동을 선사하며
관객들을 사로잡은 뮤지컬 <곤 투모로우> 세번째 시즌,
2023년 8월 10일 광림아트센터 BBCH홀 개막!
대극장 프로덕션으로 더욱 웅장해진 미장센과
초 재연 이상의 완성도 높은 무대로 다시 한 번 가슴 뜨거운 감동을 예고하다!

‘김옥균’ 역에 강필석, 최재웅, 고훈정, 조형균,
‘한정훈’ 역에 김재범, 신성민, 백형훈, 윤소호,
‘고종’ 역에 고영빈, 박영수, 김준수
‘이완’ 역에 김태한, 임별, ‘종윤’ 역에 김민철 등
초 재연을 빛낸 주역들과 몰입도를 배가시킬 실력파 배우들로 구성된 탄탄한 캐스팅!

시대를 초월한 희망의 메시지로 많은 관객들의 기다림을 받은
뮤지컬 <곤 투모로우>가 다시 돌아온다!

* 세계 속 한류를 이끄는 걸그룹들, 과연 그들의 시작은 누구였을까?
세계적 열풍인 K-pop의 반을 차지하는 걸그룹들. 그들은 치열한 경쟁에서 살아남았으며 지금도 최고의자리를 지키기 위해 혹독하게 스스로를 채찍질하는 대단한 근성의 여성들이다. 이런 한국 걸그룹 파워가 과연 하루아침에 이뤄진 것일까? 혹은 특별한 한국 여성의 유전자가 존재하는 것은 아닐까?
연출 박칼린은 이렇게 한국 걸그룹 파워의 시작점에 주목했고, 그 ‘걸그룹 선조- 시스터즈’들의 이야기를 뮤지컬로 담아보기로 결심했다.

* 빛바랜 사진 속에서 뮤지컬 무대 위로, 화려하게 부활하는 레전드들
이 의문의 답을 찾기 위해 연출 박칼린과 전수양 작가는 80여 년 전으로 거슬러 올라갔다. 현대와마찬가지로 성하고 스러진 수많은 그룹들 가운데 특히 한국 가요사에 족적을 남긴 시스터즈의 이야기를 극에 담아내기로 결심했다. 거기엔 조선악극단의 여성 단원으로 구성된 <저고리 시스터>를 시작으로 60년대 슈퍼 걸그룹 <이 시스터즈>, 대중음악의 전설 <윤복희와 코리아 키튼즈>, 그리고 20세기 후반 한국 대중음악계를 휩쓴 <바니걸즈>와 걸출한 예인 인순이를 배출한 <희자매> 등 거인들이 있었다.

일제 강점, 전쟁, 가난, 연예인에 대한 폄하, 여자 가수에 대한 멸시 등 척박한 환경 속에서도 기어코 살아남아 이름을 떨쳤던 그녀들. 특히 라디오가 막 가정에 보급되고 흑백 TV가 전부인 시절에도 사람들의 입에서 입으로 전해지며 유명해지고, 실력을 뽐냈던 그녀들의 화려하고 당당한 무대를 오늘날 뮤지컬 무대 위에서 화려하게 부활시켜 보려고 한다.

연출 박칼린은 “쇼 뮤지컬 <시스터즈 (SheStars!)>가 세 가지 여운을 관객에게 남기는 공연이 되길 바란다. 그 첫 번째는 우리 음악 역사에 운명을 개척했던 대단한 여성들이 있었구나. 둘째는 역사물인데도 너무 흥미진진하고 재미있는 구성이었다. 그리고, 마지막으로 그 무대를 채우는 우리 배우들이 정말 시대의 히로인을 표현하기에 손색이 없이 대단하다는 것이다. 100분간의 컴팩트한 시간이 그야말로 쏜살같이 흐르는 즐거운 경험을 할 것”이라고 공연에 대한 기대를 드높였다.

* 전 배역을 멀티로 소화해 낼 배우들
흑백사진 속 인물들을 현실로 불러내 올 <시스터즈 (SheStars!)>의 배우들은 한국 뮤지컬의 전성기를 이어갈 재능 넘치는 신성들로 구성되었다.
유연, 신의정, 김려원, 선민, 하유진, 이예은, 정유지, 정연, 이서영, 홍서영, 황성현 등 크고 작은 무대에서 빼어난 재능을 뽐냈던 배우들은 모두 까마득한 예인 선배들의 무대를 재현하는 배우로 선택된 것에 기뻐하며 전설들의 완벽한 무대 매너, 가창력, 카리스마에 누가 되지 않기 위해 저마다 혼신의 노력을 다할 각오를 비추고 있다.

특히 이 배우들의 무대가 더욱 빛날 것은 참여하는 모든 배우가 멀티 배역으로 여러 역할을 소화한다는 점이다.

공연에 참여하는 배우는 여배우 10명에 남배우 1명 합쳐 총 11명, 그러나 한 공연의 무대 위 출연배우는 단 7명이다. 이를 위해 각 배우들은 주역 1-3인과 단역 3-4인을 소화하며 고군분투하고 오늘과 내일 소화하는 주요 배역도 달라진다. 단일 서사의 북 뮤지컬에서는 좀처럼 볼 수 없는 주연 배우가 주, 조, 단역을 모두 소화하는 배역 배정은 배우들에게는 새로운 도전정신을 불러일으키고, 관객들에게는 흥미로움과 다 회 관람의 가치를 높인다.
배우들이 이 새로운 시스템을 완벽하게 소화해 낼 때, 본인들이 그리는 전설들처럼, 목표를 위해 열심히 노력한 예인으로서의 카타르시스를 느끼게 될 것이며, 그 에너지는 관객들에게 큰 감동을 선사할 것이다.

* 10인조 밴드와 함께 그 시절의 느낌 그대로 부활할 시대의 히트곡들
지휘자 없이 밴드 마스터와 함께 구성된 10인조 밴드와 각 시대 가수들의 드라마틱한 모습으로 분한 배우들은 ‘처녀 합창’, ’울릉도 트위스트’, ‘What I’d Say’, ’커피 한잔’ 등 시대의 히트곡들을 그 시절 그대로의 감성으로 되살린다. 춤꾼, 노래꾼, 연주자로 대표되었던 그 시절 엔터 업계의 느낌을 그대로 살려 <시스터즈 (SheStars!)>의 밴드는 또 하나의 배우로서 무대 위 존재한다. 금관악기가 주축이 되는 브라스 밴드가 들려주는 시대의 주법을 되살린 음악, 그리고 시스터즈들의 발성과 몸짓을 그대로 재현하는 배우들은 시대의 히트곡들이 왜 관객들의 사랑을 받을 수밖에 없었는지를 증명하는 무대가 될 것이다.

* 멈춘 왁스 뮤지엄이 아닌 생생하게 살아 숨 쉬는 시스터즈들의 시그니처 무대
이 공연의 가장 큰 특징은 무대 위 진정한 엔터테이너였던 시스터즈들의 최전성기 전설적 무대를 그대로 재현하는 쇼가 중심이 된다는 것이다. 또한 쇼 사이사이에 그 시대 최고의 팝스타가 되기까지 성장 스토리가 드라마틱하게 엮인다. 그녀들의 스토리, 그리고 옛날 신문, 사진, 영상 등 팩트가 가미되어 다큐멘터리를 보는 것 같으면서도 어느 순간 생생한 그 시절이 오늘날 허구의 무대에서 화려하게 재생되는 일종의 모큐멘터리 공연이다.

* 하이테크로 완성되는 최고의 아날로그적 무대
본 작품 속 무대는 시간과 배경을 초월해서 구성된다.
일제 강점기의 경성 조선극장, 미8군 무대, 60년대 라스베가스 호텔, 에드설리번 쇼, 서울 명동 거리 등 역사 속 다양한 배경이 등장한다. 자료화면을 보는 듯한 무대는 어느새 무대 뒤 분장실, 화려한 무대로 변하고, 시스터즈들은 현란한 조명 속에서 춤추며 노래하다 다시 쓸쓸한 무대 뒤에서 앳된 여인으로 돌아간다. 시공간을 초월하는 도구로서 최신 무대 기술은 구현되지만, 그 옛날 의존할 기계음, 포토샵 하나 없이 오로지 자신들의 실력과 아우라로만 무대를 휘어잡아야 했던 그 시절의 가치와 시대 느낌을 지키기 위해, 무대는 하이테크 기술을 통해 더욱더 아날로그적으로 표현된다.
대한민국 대표 심리 추리 스릴러 뮤지컬 <블랙메리포핀스>
매 시즌 유료 객석 점유율 80% 이상을 기록한 흥행 불패의 주인공!
작품성과 흥행성을 모두 갖춘 심리 추리 스릴러 웰메이드 창작 뮤지컬 <블랙메리포핀스>가 돌아왔다.

지난 10년 동안 공연된 한스, 헤르만, 요나스 버전에 이어
2023년, <블랙메리포핀스>의 완결판 ‘안나의 방’을 새롭게 선보인다.
2012년 초연, 2013년, 2014년 ‘메리포핀스 살인 사건을 위한 변호’ 한스 ver.
2016년 ‘모래 사나이가 나오는 꿈’ 헤르만 ver.
2020년, 2021년 ‘숲의 기억’ 요나스 ver.
2023년 ‘안나의 방 - 두 개의 책상’ 최종 ver.

같은 사건을 바라보는 주인공들의 서로 다른 관점!
단순히 내레이터가 교체되는 것이 아니라
치밀하게 계산된 대본에 따라 사건에 대해 느끼는 인물들의 심리 변화를 그려낸다.
<블랙메리포핀스> 완결판 ‘안나의 방’에는 네 명의 아이들 외에
1945년의 안나가 특별 출연해, ‘1945 안나’의 서술로 극이 진행된다!
1938년 로먼 박사의 연구실에서 헤어진 후,
다시 7년이 지난 1945년.
여전히 살아남아 여전히 기억하며, 존재하고 있는 아이들은
이제 “안나의 방”에서 다시 만나 기억의 방문을 스스로 연다.

한국, 중국, 일본
아시아 3개국에서 모두 성공한 창작 뮤지컬의 유례없는 신화
2014년 도쿄 초연에 이어 2016년 일본 전국 투어는 물론
2018년, 2019년, 2020년 중국 상하이와 베이징에서도 흥행 성공!
5명의 배우만으로 대극장 무대와 객석을 가득 채우며 전석 매진을 기록
큰 호평 속에서 수많은 마니아를 양산하며 명실상부 한국 최고의 웰메이드 창작 뮤지컬임을 입증했다!

동화 <메리포핀스>를 모티브로 한 발상의 전환
‘WHO’가 아닌 ‘WHY’를 찾아가는 심리 추리 스릴러
동화 <메리포핀스>를 뒤집은 상상력
2023년, 뮤지컬 <블랙메리포핀스>가 다시 한번 관객들의 마음을 울린다.
1926년 나치 정권 아래의 독일.
불타버린 대저택과 안개 속에 사라진 수요일의 기억, 그리고 그 기억으로의 귀로
‘WHY’를 찾는 과정을 통해 주인공들의 심리 상태를 조명하고
그들이 선택한 삶을 방식을 통해 주제를 드러낸다.

시대를 뛰어넘는 ‘마스터피스’
10년 만의 위대한 귀환!

한국 라이선스 공연 10주년 기념!
역대급 프로덕션으로 돌아온다!

생애 반드시 경험해야 할 세계 BIG4 뮤지컬!
위대한 명작을 오리지널 스케일로 만날 수 있는 기회!
한국 최초 시즌제 뮤지컬 <셜록홈즈>는 2011년 뮤지컬 <셜록홈즈: 앤더슨가의 비밀>
초연 이후 한국뮤지컬대상 최우수작품상, 작곡상, 극본상 및 2012년 더뮤지컬어워즈 올해의 창작뮤지컬상, 작곡작사상, 극본상, 연출상 등 주요 시상식에서 수많은 상을 휩쓸며 작품성과 대중성을 동시에 인정받았고 일본에도 수출되어 해외 진출에도 성공했다.

평단과 관객을 모두 매료시킨 웰메이드 뮤지컬 <셜록홈즈: 앤더슨가의 비밀>이 다시 무대로 돌아온다.


“욕망을 따라 순응할 것인가, 모든 것을 잃더라도 반항할 것인가.”
웰메이드 창작 뮤지컬 <비더슈탄트> 2023년 최대 화제작의 귀환!
유료 객석 점유율 98%, 초연 3개월 만에 누적관객 2만 2천명 돌파!
‘2022 대학로 민간공연장 공연 티켓예매순위 상위권 20개 공연’ 랭크!
대학로 최고 화제작 <비더슈탄트>가 돌아오다!

믿고 보는 24명의 실력파 배우 총 집결! 완벽 캐스팅 라인업!
매그너스 역 송유택, 안지환, 황순종, 정백선,
아벨 루터 역 김바다, 김지온, 동현, 이진우,
프레드릭 칼 역 김이담, 손지환, 김도현, 김방언,
하겐 악스만 역 이태이, 김민강, 박선영, 곽다인,
재스퍼 뮬러 역 정선기, 한정훈, 이한솔, 류동휘,
라인하르트 클레어 역 이승현, 김보현, 조풍래, 조상웅
압도적인 연기력과 가창력으로 관객을 마음을 사로잡을 가장 완벽한 캐스팅을 만나다!

7년의 개발 과정을 거친 다미로 X 아떼오드의 신작!
뮤지컬 <광염 소나타>의 원작자이자 작곡가 겸 음악감독 다미로가
7년간 기획 / 개발한 창작뮤지컬 <22년 2개월>이
제작사 (주)아떼오드에 의해
드디어 관객들에게 공개된다!

아주 평온한 표정으로 턱을 괴고 의자에 앉아있는 남자와
그에게 기대어 책은 읽는 여자.
이 사진 한 장에서 출발한 뮤지컬 <22년 2개월>은
박열과 가네코의 역사적 실화 위에 극적 상상력을 더했다.

최고의 배우들과 5인조 오케스트라의 앙상블로 완성되는
박열과 가네코 후미코의 이상과 사랑!
민족적 차이를 넘어 함께했던 박열과 가네코,
그 둘을 지키고자 했던 후세와 다테마스.
그리고 불령사.
그들의 이야기가 배우들과 5인조 오케스트라의 조화를 통해
무대 위에 구현된다.
BEST OF BEST!
멈추지 않는 흥행, 더욱 화려하게 돌아온 레전드!
뮤지컬 <삼총사>
17세기 파리, 위대한 전설이 시작된다!

최고의 이야기꾼! 세대와 국경을 넘어 지금까지도 사랑받고 있는
대문호 알렉상드르 뒤마의 걸작 <삼총사>가 무대 위에 펼쳐지다!
왕실 총사를 꿈꾸는 청년 ‘달타냥’과
프랑스 왕의 친위부대 삼총사 ‘아토스’, ‘아라미스’, ‘포르토스’ 세 사람의 우정과 모험!

낭만적인 17세기 파리를 배경으로 한 아름답고 웅장한 무대와
아크로바틱, 검술 등 박진감 넘치는 화려한 액션
시대를 넘어 전 세계적으로 사랑받아오며 영화, 드라마 시리즈에서 애니메이션까지
수많은 장르로 탄생한, 한 순간도 눈을 뗄 수 없는 흥미진진한 스토리!
전설의 팝스타 브라이언 아담스와 스팅, 로드 스튜어트의 ‘All For Love’를 메인 테마로 하는
감미로우면서도 웅장한 넘버!

국내 최정상 배우들이 거쳐간 <삼총사>
박장현, 후이(펜타곤), 렌, 유태양(SF9), 민규(DKZ)
이건명, 최대철, 김형균, 김신의, 김현수, 신인선, 최오식, 장대웅, 조순창
안유진, 류비, 이윤하, 지수연, 서범석, 강동우, 김상현, 엄준식 등
실력파 뉴 캐스팅과 베테랑 배우들이 함께 다시 한번 전설을 만든다!

뮤지컬 <삼총사>
2023년 9월 15일 한전아트센터 개막!
두 남자가 쓴 역사상 가장 위대’할’ 뮤지컬
뮤지컬 구텐버그

열정 넘치는 무명 뮤지컬 작가 “더그”와 작곡가 “버드“
드!디!어! 앤드류 로이드 웨버도, 카매론 매킨토시도 두려워할!
필생의 역작! 뮤지컬 <구텐버그>를 완성하고 말았다!
그들은 과연 유-우-명한 브로드웨이 프로듀서를 만날 수 있을까?

-

독특한 형식! 신선한 시도! 그리고 유쾌한 웃음까지!
2013년 국내 초연 이후 2014년 재연, 2016년 삼연까지 매 시즌마다 화제를 모으며
큰 사랑을 받았던 뮤지컬 <구텐버그>가
기발하고 유쾌한 모습으로 시원한 웃음을 선사할 새로운 프로덕션과
거침없는 연기 내공을 선보이며 넘치는 개성과 에너지로 무대를 가득 채울 새로운 캐스팅으로
6년여 만에 돌아왔다!

올여름, 기발하고 유쾌한 웃음으로 관객들을 사로잡을 새로운 <구텐버그>를 기대하라!



겨울이 되면 생각나는 작품
대체불가 캐스팅 라인업으로 돌아온 스테디셀러 뮤지컬!

2010년 초연 이후 누적 관객 수 20만 명 기록!
매 시즌 관객과 평단의 전폭적인 사랑을 받아온 가슴 따뜻한 이야기가
올겨울, 한층 더 깊어진 감성으로 찾아온다.

시즌이 거듭될수록 견고해지는 신뢰를 쌓아온 흥행 주역과
작품에 신선한 에너지를 더해줄 NEW 캐스트의 만남으로
마법 같은 울림을 다시 한번 이어간다.


찰나의 순간, 우리가 놓쳐버린
소중한 ‘일상’과 ‘인연’에 대한 이야기

순수했던 어린 시절부터 성장의 순간을 함께 나눈 두 캐릭터가
세월이 흐르며 변해가는 모습을 통해
우리가 잊고 지냈던 소중한 가치에 주목한다.

전 세대를 아울러 감동을 선사하는 스토리는
누구나 저마다의 생애 가장 행복했던 순간을 떠올리게 만들며
모두의 마음 속에 섬세한 위로를 남긴다.


동화 같은 무대와 아름다운 넘버가 전하는 따뜻한 감동

동화 속 서재를 옮겨놓은 듯한 무대
서정적인 텍스트와 가슴을 툭 치는 아름다운 선율
환상과 현실을 넘나드는 몽환적인 조명까지!

아날로그적 감성과 향수를 자극하는 특별한 페이지가
두산아트센터 연강홀에서 새롭게 펼쳐진다.
아폴로 11호가 달을 향해 쏘아 올려진 1969년의 밤.
동네 최고의 수선장이 남원은 편지 한 통을 받으며
불가능할 것만 같았던 패션 디자이너라는 꿈에 한 발짝 다가선다.
사랑하는 정분이와의 멋진 내일을 꿈꾸던 남원은
점점 커지는 달에 놀라 쓰러지고.

다시 눈을 뜬 곳은 2020년의 어느 날!

당황스럽고 어리둥절한 남원 앞에
‘영감, 지금은 2020년이고, 우린 70이야!’ 말하는 선희 할머니가 나타난다.
2020년이 낯선 듯 익숙한 남원.
어떻게든 사랑하는 정분이가 있는 1969년으로 돌아가기 위한 미래 탐사를 시작한다.

기존 법칙을 파괴하고 뮤지컬의 새로운 공식을 쓴 문제적 작품
뮤지컬 <더데빌> 10년 만의 후속작

이전에도, 지금도, 앞으로도 이어질 이야기
초연 10주년을 맞아 탄생한 <더데빌:에덴>을 통해 계속되는 빛과 어둠의 내기
끝없는 인간의 욕망, 빛을 향한 방황이라는 작품의 세계관을 확장시킨다!

빛도 어둠도 인간의 선택
세계를 뒤흔든 전염병과 바이러스, 욕망과 혼돈이 범람하는 시대에
인간 내면의 빛과 어둠은 인간을 향해 어떻게 손 내미는가
인간은 무엇을 선택할 것인가에 관한 근원적 질문을 던지다.

또 한 번 관객들을 유혹하는 <더데빌>이란 황홀경
독창적 세계관을 완성할 오리지널 크리에이터
[극작/작사] 이지나  [작곡/작사] Woody Pak(우디 박)

새로운 세계를 탄생시킬 최고의 유니온
[극작/작사] 우찬  [음악감독/작곡/작사] 신은경
[연출] 오루피나 [안무] 채현원



Search None
내숭은 벗어던진 발칙한 이야기
어른이 뮤지컬 난쟁이들

2014년 뮤지컬 하우스 블랙앤블루 개발지원작
제 3회 서울뮤지컬페스티벌 예그린 앙코르 최우수 작품 선정작
2015, 2017 한국문화예술위원회 창작뮤지컬 우수재공연 제작지원 선정작

발칙,신선,유쾌! 다 있다!
거침없이 웃기는 웰메이드 창작뮤지컬이 다시 돌아왔다!
독특한 소재, 신선한 시도, 그리고 파격적인 웃음으로
2015년 초연 이후 매 시즌마다 화제를 모으며 큰 사랑을 받았던
창작 뮤지컬 <난쟁이들>이 넘치는 개성과 에너지로 독보적 웃음 선사할
캐스팅으로 2년여 만에 다시 돌아왔다!


★★★★★
풍자적인 가사를 경쾌한 멜로디로 풀어내 극을 다채롭게 만들며,
배우들의 익살스러운 연기가 돋보이는 작품
-조선일보

기존의 문법을 완전히 깨부순 발칙하고 유쾌한 창작 뮤지컬
B급 코드를 제대로 관통한 뮤지컬의 탄생
-국민일보

박장대소 속에 날카로운 메시지를 숨겨 우리를 둘러싼 현실을 되돌아보게 하는 작품
-뉴스컬처
당신 인생의 가장 특별한 하루
뮤지컬 맘마미아!

Happy 19th Anniversary! In Korea
2004년 한국 초연 이후 19년간 공연!
서울을 포함 33개 지역에서 1,791회 공연, 2,099,893 관객이 선택!
대한민국이 사랑한 뮤지컬〈맘마미아!〉가 2023년 다시 파티를 시작한다!

2023 New, Brilliant Cast!
당신 인생의 가장 특별한 하루를 선물할 최고의 배우들
대체 불가 배우 - 최정원, 신영숙, 홍지민, 김영주, 박준면, 김정민, 이현우
250:1 치열한 경쟁률을 뚫고 새롭게 선발된 소피 - 김환희, 최태이
2023 맘마미아!에 신선한 활력을 불어넣을 새로운 멤버 - 장현성 (샘 역), 민영기 (해리 역), 김진수, 송일국 (빌 역), 김경선 (로지 역), 김시영 (스카이 역) 그리고 에너지 넘치는 20명의 앙상블!


World No1. Musical MAMMA MIA!
전 세계 50개 프로덕션, 450개 주요 도시, 16개 언어로 공연, 6,500만 명 이상 관람한 뮤지컬
뮤지컬 역사상 가장 빠르게 전 세계로 퍼진 뮤지컬
웨스트엔드 역사상 다섯 번째로 롱런 중인 뮤지컬 <맘마미아!>, 그 끝나지 않은 기록은 현재도 진행중!


It’s Time to Party!
Touching and Amazing Story
‘도나’의 우정과 사랑
딸 ‘소피’의 자아 찾기
그리고 엄마와 딸의 가슴 먹먹한 이야기
전 세대가 공감하는 재미와 감동!

ABBA’s Greatest Hits
‘댄싱퀸’ ’땡큐 포 더 뮤직’ ‘치키티타’ ‘허니허니’ 등 제목만 들어도 누구나 알 수 있는 세계적인 팝그룹 아바의 히트곡 22곡!

Beautiful Dream Island
잔잔한 물결이 넘실대는 아름다운 그리스 섬을 옮겨놓은 듯 감각적이고 세련된 무대
섬세하고 다채로운 빛의 향연! 그리고 아바의 전성기를 연상케 하는 화려한 무대의상!

AMAZING ROCK MUSICAL IS HERE!

전 세계 1,500만 관객을 열광시킨 뮤지컬 속 주인공들이
2023년으로 타임슬립을 했다?!

‘미스터빈’을 집필한 영국의 인기작가 ‘벤 엘튼’ 원작!
‘QUEEN’의 주옥 같은 명곡들!
실력파 국내 크리에이티브 팀이 탄생시킨 새로운 스토리!

전설의 록밴드 QUEEN의 음악으로 구성된
최고의 뮤지컬 의 스핀오프 에피소드!
강렬한 록음악과 트렌디한 팝안무의 놀라운 콜라보,
다채로운 영상과 원작의 의상이 만들어내는 화려한 볼거리!

소극장에서 펼쳐지는 어메이징 록뮤지컬
즐겨라, 노래하라, 열광하라!
WELCOME TO THE QUEEN WORLD!
최고의 창작진이 선보이는 서울예술단 창작 신작!
국공립단체로서 한국적 콘텐츠의 가치 발굴과 새로운 공연 양식 개발에 집중하고 있는 서울예술단은 이지나(연출), 김문정(작곡), 이자람(작창) 등 국내 최고의 창작진들과 가장 대중적인 역사 속 영웅 이순신을 새로운 양식으로 구현한 신작을 선보인다. 이순신이 전장에서 집필한 ‘난중일기’에 나오는 꿈의 해석을 통해 난세 영웅으로서의 모습과 신하로서의 모습 사이에서 갈등하고 고뇌하는 인간 이순신을 그릴 예정이다. 서울예술단의 특징인 무용수들의 군무와 움직임을 통해 전투 장면을 실감나게 표현하고, 입체적인 영상과 무대효과를 통해 스펙터클한 장면을 연출하며, 동·서양의 음악이 더해진 다이내믹한 음악을 바탕으로 ‘한산’, ‘명량’, ‘노량’ 등 주요 해전 장면은 판소리로 풀어내는 등 토털 시어터를 지향하고 있는 작품이다.




대한민국 대표 창작 뮤지컬 <그날들> 10주년 기념 공연,
7월 12일 예술의전당 오페라극장 개막!

대한민국 대표 창작 뮤지컬 <그날들> 10주년 기념 대구공연이 오는 10월 13일 계명아트센터에서 막을 올린다.

2013년 초연 이래, 총 관객 55만 돌파, 뮤지컬 시상식 11개 부문 최다 석권 등의 경이적 기록을 세운
국민 뮤지컬 <그날들>은 창작 뮤지컬로서는 단연 최고의 스케일과 독보적인 흥행 행보를 보여주고 있다.

세월이 흘러도 변함없이 사랑받는 영원한 가객, 故김광석이 불렀던 명곡들로 이뤄진 넘버는 물론,
청와대 경호실을 배경으로 20년의 시간을 넘나드는 한 편의 영화 같은 스토리로 매 시즌 많은 사랑을 받고 있다.

역대 주크박스 뮤지컬로서는 최고의 완성도를 보여준 것은 물론,
남녀노소 할 것 없이 대한민국 국민이라면 누구나 즐길 수 있는 뮤지컬 <그날들> 10주년 기념 대구공연!
오는 10월 13일부터 10월 15일까지, 계명아트센터에서 공연된다.

10주년 기념 공연을 위해 뭉쳤다!
유준상, 이건명, 오만석, 엄기준, 오종혁, 김건우, 김지현, 효은,
이정열, 고창석 등 역대 최고의 캐스팅으로 돌아온 <그날들>

뮤지컬 <그날들> 10주년 기념 공연에는 초연부터 함께한 배우들이 대거 합류한 것은 물론,
극에 활력을 불어넣어줄 뉴 캐스트의 출연으로 큰 화제를 모으고 있다.


철두철미한 원칙주의자 ‘정학’ 역에 유준상, 이건명, 오만석, 엄기준
여유와 위트를 지닌 자유로운 영혼 ‘무영’ 역에 오종혁, 김건우
신원을 알 수 없는 피경호인 ‘그녀’ 역에 김지현, 효은
다정하고 소탈한 성품의 대통령 전담 요리사 ‘운영관’ 역에 이정열, 고창석


여기에 ‘사서’ 역에 김보정, ‘대식’ 역에 최지호, 김산호, ‘상구’ 역에 정순원, 손우민,
‘하나’ 역에 곽나윤, 이정화, ‘수지’ 역에 이자영이 출연을 확정,
역대 최고의 캐스팅으로 관객들에게 완벽한 무대를 선사할 예정이다.




수십 년 간 한 분야에 종사한 구두장인. 평생을 통해 최고가 된 구두장인 빌의 이야기!
선천적 장애를 지닌 길버타, 빌의 구둣방을 계기로 달라지는 그녀의 세상!
더불어 살아가는 세상을 보여주는 뮤지컬!

무대 공간에  투사되는 영상으로  느낄 수 있는 신비롭고 초월적인 경험!
풍요로운 뮤지컬 넘버! 다양한 매력의 스케일을 지닌 음악과 노래들!
생각지도 못한 유머러스한 상황! 꿈과 꿈을 지지해주는 진심 어린 사랑까지!
교육적 효과, 마음의 감동을 두루 충족시켜줄 MUSICAL 빌의 구둣방!


Search None












Search None





[2023 문예회관과 함께하는 방방곡곡 문화공감 사업]
문예회관, 예술단체 공연콘텐츠 공동제작. 배급 프로그램 선정작

“여긴 어디죠?”

무작정 떠난 여행 그곳에서 만난 새로운 사람들
각자 다른 이유로 머무르고 있지만 같은 목적으로 이곳에 모였다.

작가님의 삶은 비극적이신가요?

어딘지 모르는 곳에 분명 문제를 해결할 방법이 있다.

유명 비극 작가 루미와 알 수 없는 초대자 루이,
Wish Guesthouse의 숙박객들
이곳 Wish Guesthouse 모여 각자의 해피엔딩을 찾아 나선다.

그동안 볼 수 없었던 새로운 장르의 음악!
궁금증과 신비로움을 자아내는 환상적인 무대!
우리들의 삶 속 어딘가의 해피엔딩을 찾아주는 따뜻한 뮤지컬

“ 어서 오세요 Wish Guesthouse에 ”
오신 걸 환영합니다.
[2023 문예회관과 함께하는 방방곡곡 문화공감 사업]
문예회관, 예술단체 공연콘텐츠 공동제작. 배급 프로그램 선정작

“여긴 어디죠?”

무작정 떠난 여행 그곳에서 만난 새로운 사람들
각자 다른 이유로 머무르고 있지만 같은 목적으로 이곳에 모였다.

작가님의 삶은 비극적이신가요?

어딘지 모르는 곳에 분명 문제를 해결할 방법이 있다.

유명 비극 작가 루미와 알 수 없는 초대자 루이,
Wish Guesthouse의 숙박객들
이곳 Wish Guesthouse 모여 각자의 해피엔딩을 찾아 나선다.

그동안 볼 수 없었던 새로운 장르의 음악!
궁금증과 신비로움을 자아내는 환상적인 무대!
우리들의 삶 속 어딘가의 해피엔딩을 찾아주는 따뜻한 뮤지컬

“ 어서 오세요 Wish Guesthouse에 ”
오신 걸 환영합니다.
[2023 문예회관과 함께하는 방방곡곡 문화공감 사업]
문예회관, 예술단체 공연콘텐츠 공동제작. 배급 프로그램 선정작

“여긴 어디죠?”

무작정 떠난 여행 그곳에서 만난 새로운 사람들
각자 다른 이유로 머무르고 있지만 같은 목적으로 이곳에 모였다.

작가님의 삶은 비극적이신가요?

어딘지 모르는 곳에 분명 문제를 해결할 방법이 있다.

유명 비극 작가 루미와 알 수 없는 초대자 루이,
Wish Guesthouse의 숙박객들
이곳 Wish Guesthouse 모여 각자의 해피엔딩을 찾아 나선다.

그동안 볼 수 없었던 새로운 장르의 음악!
궁금증과 신비로움을 자아내는 환상적인 무대!
우리들의 삶 속 어딘가의 해피엔딩을 찾아주는 따뜻한 뮤지컬

“ 어서 오세요 Wish Guesthouse에 ”
오신 걸 환영합니다.


새로운 세상이 펼쳐진다!
뮤지컬 <더 쇼! 신라하다>

“2023 경상북도문화관광공사 신라문화기반 창작 뮤지컬 선정”
찬란한 과거의 신라와 역동적인 현대를 넘나들며 펼쳐지는 쇼 뮤지컬!
10월 21일 경주엑스포대공원 문화센터 문무홀 개막!

국내 최고의 창작진과 스타들이 함께하는 공연
남경주, 김동완, 세용(마이네임), 유권, 린지, 낸시, 박소현 外

압도되는 퍼포먼스! 신나는 춤과 음악!
무대의 한계를 뛰어넘는 영상 예술까지!
무대 위 새로운 세상을 펼친다!
시대를 뛰어넘는 ‘마스터피스’
10년 만의 위대한 귀환!

한국 라이선스 공연 10주년 기념!
역대급 프로덕션으로 돌아온다!

생애 반드시 경험해야 할 세계 BIG4 뮤지컬!
위대한 명작을 오리지널 스케일로 만날 수 있는 기회!

당신 인생의 가장 특별한 하루
뮤지컬 맘마미아!

Happy 19th Anniversary! In Korea
2004년 한국 초연 이후 19년간 공연!
서울을 포함 33개 지역에서 1,791회 공연, 2,099,893 관객이 선택!
대한민국이 사랑한 뮤지컬<맘마미아!>가 2023년 다시 파티를 시작한다!

2023 New, Brilliant Cast!
당신 인생의 가장 특별한 하루를 선물할 최고의 배우들
대체 불가 배우 - 최정원, 신영숙, 홍지민, 김영주, 박준면, 김정민, 이현우
250:1 치열한 경쟁률을 뚫고 새롭게 선발된 소피 - 최태이
2023 맘마미아!에 신선한 활력을 불어넣을 새로운 멤버 - 장현성 (샘 역), 민영기 (해리 역), 김진수, 송일국 (빌 역), 김경선 (로지 역), 김시영 (스카이 역) 그리고 에너지 넘치는 20명의 앙상블!

World No1. Musical MAMMA MIA!
전 세계 50개 프로덕션, 450개 주요 도시, 16개 언어로 공연, 6,500만 명 이상 관람한 뮤지컬
뮤지컬 역사상 가장 빠르게 전 세계로 퍼진 뮤지컬
웨스트엔드 역사상 다섯 번째로 롱런 중인 뮤지컬 <맘마미아!>, 그 끝나지 않은 기록은 현재도 진행중!

It’s Time to Party!
Touching and Amazing Story
‘도나’의 우정과 사랑
딸 ‘소피’의 자아 찾기
그리고 엄마와 딸의 가슴 먹먹한 이야기
전 세대가 공감하는 재미와 감동!

ABBA’s Greatest Hits
‘댄싱퀸’ ’땡큐 포 더 뮤직’ ‘치키티타’ ‘허니허니’ 등 제목만 들어도 누구나 알 수 있는 세계적인 팝그룹 아바의 히트곡 22곡!

Beautiful Dream Island
잔잔한 물결이 넘실대는 아름다운 그리스 섬을 옮겨놓은 듯 감각적이고 세련된 무대
섬세하고 다채로운 빛의 향연! 그리고 아바의 전성기를 연상케 하는 화려한 무대의상!



당신 인생의 가장 특별한 하루
뮤지컬 맘마미아!

Happy 19th Anniversary! In Korea
2004년 한국 초연 이후 19년간 공연!
서울을 포함 33개 지역에서 1,791회 공연, 2,099,893 관객이 선택!
대한민국이 사랑한 뮤지컬 <맘마미아!>가 2023년 다시 파티를 시작한다!

2023 New, Brilliant Cast!
당신 인생의 가장 특별한 하루를 선물할 최고의 배우들
대체 불가 배우 - 최정원, 신영숙, 홍지민, 김영주, 박준면, 김정민, 이현우
250:1 치열한 경쟁률을 뚫고 새롭게 선발된 소피 - 김환희, 최태이
2023 맘마미아!에 신선한 활력을 불어넣을 새로운 멤버 - 장현성 (샘 역), 민영기 (해리 역), 김진수, 송일국 (빌 역), 김경선 (로지 역), 김시영 (스카이 역) 그리고 에너지 넘치는 20명의 앙상블!


World No1. Musical MAMMA MIA!
전 세계 50개 프로덕션, 450개 주요 도시, 16개 언어로 공연, 6,500만 명 이상 관람한 뮤지컬
뮤지컬 역사상 가장 빠르게 전 세계로 퍼진 뮤지컬
웨스트엔드 역사상 다섯 번째로 롱런 중인 뮤지컬 <맘마미아!>, 그 끝나지 않은 기록은 현재도 진행중!


It’s Time to Party!
Touching and Amazing Story
‘도나’의 우정과 사랑
딸 ‘소피’의 자아 찾기
그리고 엄마와 딸의 가슴 먹먹한 이야기
전 세대가 공감하는 재미와 감동!

ABBA’s Greatest Hits
‘댄싱퀸’ ’땡큐 포 더 뮤직’ ‘치키티타’ ‘허니허니’ 등 제목만 들어도 누구나 알 수 있는 세계적인 팝그룹 아바의 히트곡 22곡!

Beautiful Dream Island
잔잔한 물결이 넘실대는 아름다운 그리스 섬을 옮겨놓은 듯 감각적이고 세련된 무대
섬세하고 다채로운 빛의 향연! 그리고 아바의 전성기를 연상케 하는 화려한 무대의상!



BEST OF BEST!
멈추지 않는 흥행, 더욱 화려하게 돌아온 레전드!
뮤지컬 <삼총사>
17세기 파리, 위대한 전설이 시작된다!

최고의 이야기꾼! 세대와 국경을 넘어 지금까지도 사랑받고 있는
대문호 알렉상드르 뒤마의 걸작 <삼총사>가 무대 위에 펼쳐지다!
왕실 총사를 꿈꾸는 청년 ‘달타냥’과
프랑스 왕의 친위부대 삼총사 ‘아토스’, ‘아라미스’, ‘포르토스’ 세 사람의 우정과 모험!

낭만적인 17세기 파리를 배경으로 한 아름답고 웅장한 무대와
아크로바틱, 검술 등 박진감 넘치는 화려한 액션
시대를 넘어 전 세계적으로 사랑받아오며 영화, 드라마 시리즈에서 애니메이션까지
수많은 장르로 탄생한, 한 순간도 눈을 뗄 수 없는 흥미진진한 스토리!
전설의 팝스타 브라이언 아담스와 스팅, 로드 스튜어트의 ‘All For Love’를 메인 테마로 하는
감미로우면서도 웅장한 넘버!

국내 최정상 배우들이 거쳐간 <삼총사>
박장현, 후이(펜타곤), 렌, 유태양(SF9), 민규(DKZ)
이건명, 최대철, 김형균, 김신의, 김현수, 신인선, 최오식, 장대웅, 조순창
안유진, 류비, 이윤하, 지수연, 서범석, 강동우, 김상현, 엄준식 등
실력파 뉴 캐스팅과 베테랑 배우들이 함께 다시 한번 전설을 만든다!
One for All, All for One
멈추지 않는 흥행, 더욱 화려하게 돌아온 레전드!
뮤지컬 <삼총사>
17세기 파리, 위대한 전설이 시작된다!

최고의 이야기꾼! 세대와 국경을 넘어 지금까지도 사랑받고 있는
대문호 알렉상드르 뒤마의 걸작 <삼총사>가 무대위에 펼쳐지다!
왕실 총사를 꿈꾸는 청년 ‘달타냥’과
프랑스 왕의 친위부대 삼총사 ‘아토스’, ‘아라미스’, ‘포르토스’의 세 사람의 우정과 모험!

낭만적인 17세기 파리를 배경으로 한 아름답고 웅장한 무대와
아크로바틱, 검술 등 박진감 넘치는 화려한 액션
시대를 넘어 전 세계적으로 사랑받아오며 영화, 드라마 시리즈에서 애니메이션까지
수많은 장르로 탄생한 한 순간도 눈을 뗄 수 없는 흥미진진한 스토리!
전설의 팝스타 브라이언 아담스와 스팅, 로드 스튜어트의 ‘All For Love’를 메인 테마로 하는
감미로우면서도 웅장한 넘버!

국내 최정상 배우들이 거쳐간 <삼총사>
박장현, 후이(펜타곤), 렌, 민규(DKZ)
이건명, 최대철, 김형균, 김신의, 김현수, 신인선, 최오식, 장대웅, 조순창
안유진, 류비, 이윤하, 지수연, 서범석, 강동우, 김상현, 엄준식 등
실력파 뉴 캐스팅과 베테랑 배우들이 함께 다시 한번 전설을 만든다!

2023년 12월, 크리스마스!
다시 한번 부산관객들을 17세기 파리의 낭만 속으로 이끈다.



Mega-Hit Worldwide Musical
EMK 1ST International Production
영원한 클래식을 뛰어넘는 업그레이드된 명작!

뮤지컬 <시스터 액트>는 세계가 열광한 우피 골드버그 주연의 <시스터 액트> 동명의 뮤지컬로 2006년 초연 이후 18년 동안 오스트리아부터 프랑스, 독일, 이탈리아, 모나코까지 수많은 나라에서 롱런하고 있는 뮤지컬이다.

글로벌 히트 콘텐츠와 EMK의 월드클래스 제작 시스템이 만나 새롭게 태어난 뮤지컬 <시스터 액트>는 3개월에 걸친 치열한 오디션을 통해 완성된 최정예 캐스팅 라인업에 <엘리자벳>, <레베카>, <마리 앙투아네트>, <웃는 남자> 등 뮤지컬 미다스 손, 로버트 요한슨이 연출을 맡는다.

국내외 최정상 배우들이 선사하는 최고의 하모니
그 어느때보다 HIP하고 Powerful한 수녀들이 온다!



In [ ]:
musical_info.count("None") + musical_info.count("")

115

In [ ]:
musical_DF.to_csv("/data/raw/musical_info_DF" + now.strftime('%Y-%m-%d') + ".csv", encoding='utf-8')

In [ ]:
len(musical_info)

156

## 테스트 코드

In [ ]:
info_time = play_DF['기간'][i].split("~")[0]
info_time=datetime.strptime(info_time,'%Y.%m.%d')
print(info_time)

2023-04-03 00:00:00

In [ ]:
play_info.count("None") + play_info.count("")

139

In [ ]:
play_INFO = pd.DataFrame({'공연소개':play_info})
play_INFO[play_INFO['공연소개']=='None'].index

Int64Index([12, 14, 18, 20, 23, 29], dtype='int64')

In [ ]:
search_none = pd.concat([play_refine, play_rank, play_INFO], axis=1)

In [ ]:
search_none[search_none['공연소개']=='']

                 연극 이름                  공연장                       기간 공연소개
0             너의목소리가들려               도토리씨어터  2023.04.03~\n2023.10.31
1               쉬어매드니스  콘텐츠박스(KONTENTZ BOX)  2015.11.12~\n2023.10.31
4                 한뼘사이                라온아트홀  2017.03.01~\n2023.10.31
6               불편한편의점    대학로 스타시티 7층 후암씨어터  2023.04.08~\n2023.12.31
7               2호선세입자          대학로 바탕골 소극장  2022.01.14~\n2023.10.31
9               좀비오마이갓         대학로 오마이갓 전용관  2023.04.11~\n2023.10.31
10                 핫식스               도토리씨어터  2023.04.03~\n2023.10.31
11                  라면            대학로 해피씨어터  2021.01.16~\n2023.10.31
13             죽여주는이야기      지인시어터(구.알과핵소극장)  2023.07.01~\n2023.10.31
17               운빨로맨스                컬쳐씨어터  2021.05.01~\n2023.10.31
19               오백에삼십        대학로 세우아트센터 1관  2022.03.01~\n2023.10.31
21              뷰티풀라이프           JTN 아트홀 4관  2018.02.20~\n2023.10.31
24  ★평점9.5★코미디의맛/쇼미더퍼니            홍대 윤형빈소극장  2023.09.05~\n2023.11.05
25              진짜나쁜소녀           JTN 아트홀 1관  2023.05.02~\n2023.10.31
26      2023년친정엄마와2박3일          김해문화의전당 마루홀  2023.10.27~\n2023.10.28
27                딜리버리                아티스탄홀  2023.03.10~\n2023.10.31
28          이머시브씨어터카지노     대학로 스타시티 카지노 전용관  2023.04.28~\n2023.10.29

In [ ]:
play_info_DF = pd.DataFrame(play_info)
play_DF = pd.concat([play_refine, play_rank, play_info_DF], axis=1)
play_DF.to_csv("/data/raw/play_info_DF" + now.strftime('%Y-%m-%d') + ".csv", encoding='utf-8')

In [ ]:
if(comp_time < info_time):
  text = ""
  print("Search None")

Yes

In [ ]:
info_time

datetime.datetime(2023, 11, 10, 0, 0)

In [ ]:
driver.get("http://www.playdb.co.kr/Index.asp")
time.sleep(3)
driver.find_element(By.XPATH, '//*[@id="HDQuery"]').send_keys(play_DF['연극 이름'][2])
driver.find_element(By.XPATH, '//*[@id="HDQuery"]').send_keys(Keys.ENTER)
time.sleep(3)
try:
  ran = driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[1]/td/table/tbody/tr/td[2]/b').text
  ran = re.sub(r'[^0-9]', '', ran)
except:
  ran = 2
for j in range(1, int(ran)):
  comp_time = driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table['+str(j)+']/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[2]/td[1]').text
  comp_time=comp_time.split(" ")[0]
  comp_time = datetime.strptime(comp_time,'%Y/%m/%d')
  place = driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table[' +str(j) + ']/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[2]/td[2]/a').text
  print(place)
  if(len(place) >= len(play_DF['공연장'][2])):
    if((place.find(play_DF['공연장'][2]) >= 0) or (comp_time == info_time)):
      driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table['+str(j)+']/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[1]/td[1]/b/a').click()
      time.sleep(3)
      driver.find_element(By.XPATH, '//*[@id="Tab2"]').click()
      try:
        print(driver.find_element(By.XPATH, '//*[@id="wrap"]/div[3]/div[1]/div[1]/table/tbody/tr[1]/td/span').text)
        print(driver.find_element(By.XPATH, '/html/body/table/tbody/tr[2]/td/table/tbody/tr[3]/td').text)
      except:
        print("Explain None")
      break
  else:
    if((play_DF['공연장'][2].find(place) >= 0) or (comp_time == info_time)):
      driver.find_element(By.XPATH, '//*[@id="tblPlay"]/tbody/tr[1]/td/table/tbody/tr[2]/td/table/tbody/tr[1]/td/table/tbody/tr[2]/td/table['+str(j)+']/tbody/tr[1]/td/table/tbody/tr/td[3]/table/tbody/tr[2]/td/table/tbody/tr[1]/td[1]/b/a').click()
      time.sleep(3)
      driver.find_element(By.XPATH, '//*[@id="Tab2"]').click()
      try:
        print(driver.find_element(By.XPATH, '//*[@id="wrap"]/div[3]/div[1]/div[1]/table/tbody/tr[1]/td/span').text)
        print(driver.find_element(By.XPATH, '/html/body/table/tbody/tr[2]/td/table/tbody/tr[3]/td').text)
      except:
        print("Explain None")
      break

정극장 (구 M시어터)
행오버
Explain None

In [ ]:
import requests
from bs4 import BeautifulSoup
driver.get("http://www.playdb.co.kr/playdb/PlaydbDetail.asp?sReqPlayNo=183033")

time.sleep(3)
driver.find_element(By.XPATH, '//*[@id="contents"]/div[1]/div[1]/ul[1]/li[2]/a').click()
iframe_element = driver.find_element(By.ID, "iFrmContent")  # iframe의 id를 사용하여 찾는 예시
driver.switch_to.frame(iframe_element)
driver.find_element(By.XPATH, '/html/body/table/tbody/tr[2]/td/table/tbody/tr[3]/td').text

' \n모든 일은 파라다이스 호텔 506호에서 시작된다.\n남편(철수)의 외도를 알게 된 지연(부인)은 이벤트 업체를 이용해서 남편에게 사과를 받고 싶어한다.\n이벤트 업체 대표 태민은 지연의 계획대로 철수에게 사과를 받아보려고 했지만,\n만취한 철수는 지연을 506호에서 살해한다.\n당황한 이벤트 업체 대표 태민은 철수를 급하게 507호로 옮기고 4시간만 대실한다.\n술이 깬 철수에게 지난 밤 일을 설명하지만, 철수는 기억나지 않는다.\n506호 살인 사건을 조사 중인 경찰이 507호를 방문하지만,\n태민의 임기응변으로 위기를 넘긴다.\n그런데, 507호에는 다른 2명이 더 있다.\n초능력이 있다고 주장하는 508호 케이(남)\n자살하기 위해 호텔을 찾은 509호 엠마(여)\n케이와 엠마 두명 역시 술을 먹고 깨어보니 507호라는 황당한 말을 전한다.\n507호에 만난 태민, 철수, 케이, 엠마!\n만약, 경찰이 507호로 들이닥치면 4명 모두 공범이 되는 상황.\n이런 말도 안되는 상황을 믿어 줄 경찰은 없다.\n4명은 서로를 의심하며 서로에게 자백을 강요하기 시작하는데...\n이들 4명에게 주어진 시간은 대실 4시간!\n4시간 안에 모든 것을 밝혀내야 되는 상황에서\n4명의 비밀이 하나씩 드러난다.\n '

In [ ]:
i, j, ran

(0, 1, '3')

## PlayDB 기본 정보(줄거리) 크롤링

## 배우 100명 크롤링

In [ ]:
## 연극배우
driver.get("http://www.playdb.co.kr/artistdb/list.asp?code=013004")
time.sleep(3)
driver.refresh()
driver.find_element(By.XPATH, '//*[@id="contents"]/div[2]/table/tbody/tr[1]/td/table/tbody/tr/td[2]/a[2]').click()
driver.find_element(By.XPATH, '//*[@id="contents"]/div[2]/table/tbody/tr[1]/td/table/tbody/tr/td[2]/a[1]').click()
time.sleep(2)
iframe_element = driver.find_element(By.ID, "list_ifm")  # iframe의 id를 사용하여 찾는 예시
driver.switch_to.frame(iframe_element)
play_actor = []
for i in range(1, 6):
  for j in range(3, 80, 4):
    # play_DF 에 있는 장소 추출
    name = driver.find_element(By.XPATH, '/html/body/table/tbody/tr['+str(j)+']/td/table/tbody/tr/td[1]/table/tbody/tr/td[2]/a').text
    name_work = driver.find_element(By.XPATH, '/html/body/table/tbody/tr['+str(j)+']/td/table/tbody/tr/td[5]').text
    play_actor.append([name, name_work])
    print(name, name_work)
  driver.find_element(By.XPATH, '/html/body/table/tbody/tr[84]/td/a['+str(i)+']').click()

윤은채 은밀하게 위대하게(2017)
챠이카(2016)
레베카(2016)
유희준 시간을 파는 상점(2017)
하지혜 둥근 해가 떴습니다(2012)
연극 이(爾)(2010)
짐(2007)
백시연 나도 이제 결혼하고 싶다(2021)
제5회 한국여성극작가전 - 그 집(2019)
연애플레이리스트(2018)
고형우 애니 모어 스토리(2020)
두드려라 맥베스(2018)
이인규 수상한 흥신소(2021)
라면(2021)
러브 액츄얼리(2019)
최정원 컴프롬어웨이(2023)
맘마미아 - 천안(2023)
맘마미아 - 수원(2023)
유아름 1948 여수 - 여수(2022)
1948 여수 - 여수(2020)
그해 분장실(2020)
신성록 드라큘라(2023)
벤허(2023)
스위니토드(2022)
김성진 사명(2021)
숙희(2021)
언플러그드(2020)
김화영 고목(2023)
장녀들(2023)
스카프와 나이프(2022)
이란희 노르망디(2023)
칸사이 주먹(2022)
노르망디(2022)
홍경인 준생(2023)
왓 이프(2023)
행복(2023)
홍나현 22년 2개월(2023)
붉은머리 안(2023)
홍련(2023)
남윤호 코리올라누스(2021)
보도지침(2017)
월요쇼케이스 - 보도지침(2017)
강보라 리미트(2018)
뷰티풀 라이프(2018)
변서윤 룸넘버13 - 울산(2018)
룸넘버13(2016)
내 깡패같은 로맨스(2015)
김지현 그날들 - 대구(2023)
그날들(2023)
스위니토드(2022)
이시원 극적인 하룻밤(2023)
오싹한 연애(2020)
당신 안녕(2016)
엄기준 그날들 - 수원(2023)
그날들 - 대구(2023)
그날들(2023)
윤은채 은밀하게 위대하게(2017)
챠이카(2016)
레베카(2016)
유희준 시간을 파는 상점(2017)
하지혜 둥근 해가 떴습니다(2012)
연극 이(爾)(2010)
짐(2007)
백시연 나도 이제 결혼하고 싶다(2021)
제5회 한국여성극작가전 - 그 집(2019)
연애플레이리스트(2018)
고형우 애니 모어 스토리(2020)
두드려라 맥베스(2018)
이인규 수상한 흥신소(2021)
라면(2021)
러브 액츄얼리(2019)
최정원 컴프롬어웨이(2023)
맘마미아 - 천안(2023)
맘마미아 - 수원(2023)
유아름 1948 여수 - 여수(2022)
1948 여수 - 여수(2020)
그해 분장실(2020)
신성록 드라큘라(2023)
벤허(2023)
스위니토드(2022)
김성진 사명(2021)
숙희(2021)
언플러그드(2020)
김화영 고목(2023)
장녀들(2023)
스카프와 나이프(2022)
이란희 노르망디(2023)
칸사이 주먹(2022)
노르망디(2022)
홍경인 준생(2023)
왓 이프(2023)
행복(2023)
홍나현 22년 2개월(2023)
붉은머리 안(2023)
홍련(2023)
남윤호 코리올라누스(2021)
보도지침(2017)
월요쇼케이스 - 보도지침(2017)
강보라 리미트(2018)
뷰티풀 라이프(2018)
변서윤 룸넘버13 - 울산(2018)
룸넘버13(2016)
내 깡패같은 로맨스(2015)
김지현 그날들 - 대구(2023)
그날들(2023)
스위니토드(2022)
이시원 극적인 하룻밤(2023)
오싹한 연애(2020)
당신 안녕(2016)
엄기준 그날들 - 수원(2023)
그날들 - 대구(2023)
그날들(2023)
윤은채 은밀하게 위대하게(2017)
챠이카(2016)
레베카(2016)
유희준 시간을 파는 상점(2017)
하지혜 둥근 해가 떴습니다(2012)
연극 이(爾)(2010)
짐(2007)
백시연 나도 이제 결혼하고 싶다(2021)
제5회 한국여성극작가전 - 그 집(2019)
연애플레이리스트(2018)
고형우 애니 모어 스토리(2020)
두드려라 맥베스(2018)
이인규 수상한 흥신소(2021)
라면(2021)
러브 액츄얼리(2019)
최정원 컴프롬어웨이(2023)
맘마미아 - 천안(2023)
맘마미아 - 수원(2023)
유아름 1948 여수 - 여수(2022)
1948 여수 - 여수(2020)
그해 분장실(2020)
신성록 드라큘라(2023)
벤허(2023)
스위니토드(2022)
김성진 사명(2021)
숙희(2021)
언플러그드(2020)
김화영 고목(2023)
장녀들(2023)
스카프와 나이프(2022)
이란희 노르망디(2023)
칸사이 주먹(2022)
노르망디(2022)
홍경인 준생(2023)
왓 이프(2023)
행복(2023)
홍나현 22년 2개월(2023)
붉은머리 안(2023)
홍련(2023)
남윤호 코리올라누스(2021)
보도지침(2017)
월요쇼케이스 - 보도지침(2017)
강보라 리미트(2018)
뷰티풀 라이프(2018)
변서윤 룸넘버13 - 울산(2018)
룸넘버13(2016)
내 깡패같은 로맨스(2015)
김지현 그날들 - 대구(2023)
그날들(2023)
스위니토드(2022)
이시원 극적인 하룻밤(2023)
오싹한 연애(2020)
당신 안녕(2016)
엄기준 그날들 - 수원(2023)
그날들 - 대구(2023)
그날들(2023)
윤은채 은밀하게 위대하게(2017)
챠이카(2016)
레베카(2016)
유희준 시간을 파는 상점(2017)
하지혜 둥근 해가 떴습니다(2012)
연극 이(爾)(2010)
짐(2007)
백시연 나도 이제 결혼하고 싶다(2021)
제5회 한국여성극작가전 - 그 집(2019)
연애플레이리스트(2018)
고형우 애니 모어 스토리(2020)
두드려라 맥베스(2018)
이인규 수상한 흥신소(2021)
라면(2021)
러브 액츄얼리(2019)
최정원 컴프롬어웨이(2023)
맘마미아 - 천안(2023)
맘마미아 - 수원(2023)
유아름 1948 여수 - 여수(2022)
1948 여수 - 여수(2020)
그해 분장실(2020)
신성록 드라큘라(2023)
벤허(2023)
스위니토드(2022)
김성진 사명(2021)
숙희(2021)
언플러그드(2020)
김화영 고목(2023)
장녀들(2023)
스카프와 나이프(2022)
이란희 노르망디(2023)
칸사이 주먹(2022)
노르망디(2022)
홍경인 준생(2023)
왓 이프(2023)
행복(2023)
홍나현 22년 2개월(2023)
붉은머리 안(2023)
홍련(2023)
남윤호 코리올라누스(2021)
보도지침(2017)
월요쇼케이스 - 보도지침(2017)
강보라 리미트(2018)
뷰티풀 라이프(2018)
변서윤 룸넘버13 - 울산(2018)
룸넘버13(2016)
내 깡패같은 로맨스(2015)
김지현 그날들 - 대구(2023)
그날들(2023)
스위니토드(2022)
이시원 극적인 하룻밤(2023)
오싹한 연애(2020)
당신 안녕(2016)
엄기준 그날들 - 수원(2023)
그날들 - 대구(2023)
그날들(2023)
윤은채 은밀하게 위대하게(2017)
챠이카(2016)
레베카(2016)
유희준 시간을 파는 상점(2017)
하지혜 둥근 해가 떴습니다(2012)
연극 이(爾)(2010)
짐(2007)
백시연 나도 이제 결혼하고 싶다(2021)
제5회 한국여성극작가전 - 그 집(2019)
연애플레이리스트(2018)
고형우 애니 모어 스토리(2020)
두드려라 맥베스(2018)
이인규 수상한 흥신소(2021)
라면(2021)
러브 액츄얼리(2019)
최정원 컴프롬어웨이(2023)
맘마미아 - 천안(2023)
맘마미아 - 수원(2023)
유아름 1948 여수 - 여수(2022)
1948 여수 - 여수(2020)
그해 분장실(2020)
신성록 드라큘라(2023)
벤허(2023)
스위니토드(2022)
김성진 사명(2021)
숙희(2021)
언플러그드(2020)
김화영 고목(2023)
장녀들(2023)
스카프와 나이프(2022)
이란희 노르망디(2023)
칸사이 주먹(2022)
노르망디(2022)
홍경인 준생(2023)
왓 이프(2023)
행복(2023)
홍나현 22년 2개월(2023)
붉은머리 안(2023)
홍련(2023)
남윤호 코리올라누스(2021)
보도지침(2017)
월요쇼케이스 - 보도지침(2017)
강보라 리미트(2018)
뷰티풀 라이프(2018)
변서윤 룸넘버13 - 울산(2018)
룸넘버13(2016)
내 깡패같은 로맨스(2015)
김지현 그날들 - 대구(2023)
그날들(2023)
스위니토드(2022)
이시원 극적인 하룻밤(2023)
오싹한 연애(2020)
당신 안녕(2016)
엄기준 그날들 - 수원(2023)
그날들 - 대구(2023)
그날들(2023)

In [ ]:
from collections import Counter

counter = Counter(play_actor[0])

print(play_actor)
print(counter)
print(dict(counter))

[['윤은채', '은밀하게 위대하게(2017)\n챠이카(2016)\n레베카(2016)'], ['유희준', '시간을 파는 상점(2017)'], ['하지혜', '둥근 해가 떴습니다(2012)\n연극 이(爾)(2010)\n짐(2007)'], ['백시연', '나도 이제 결혼하고 싶다(2021)\n제5회 한국여성극작가전 - 그 집(2019)\n연애플레이리스트(2018)'], ['고형우', '애니 모어 스토리(2020)\n두드려라 맥베스(2018)'], ['이인규', '수상한 흥신소(2021)\n라면(2021)\n러브 액츄얼리(2019)'], ['최정원', '컴프롬어웨이(2023)\n맘마미아 - 천안(2023)\n맘마미아 - 수원(2023)'], ['유아름', '1948 여수 - 여수(2022)\n1948 여수 - 여수(2020)\n그해 분장실(2020)'], ['신성록', '드라큘라(2023)\n벤허(2023)\n스위니토드(2022)'], ['김성진', '사명(2021)\n숙희(2021)\n언플러그드(2020)'], ['김화영', '고목(2023)\n장녀들(2023)\n스카프와 나이프(2022)'], ['이란희', '노르망디(2023)\n칸사이 주먹(2022)\n노르망디(2022)'], ['홍경인', '준생(2023)\n왓 이프(2023)\n행복(2023)'], ['홍나현', '22년 2개월(2023)\n붉은머리 안(2023)\n홍련(2023)'], ['남윤호', '코리올라누스(2021)\n보도지침(2017)\n월요쇼케이스 - 보도지침(2017)'], ['강보라', '리미트(2018)\n뷰티풀 라이프(2018)'], ['변서윤', '룸넘버13 - 울산(2018)\n룸넘버13(2016)\n내 깡패같은 로맨스(2015)'], ['김지현', '그날들 - 대구(2023)\n그날들(2023)\n스위니토드(2022)'], ['이시원', '극적인 하룻밤(2023)\n오싹한 연애(2020)\n당신 안녕(2016)'], ['엄기준', '그날들 - 수원(2023)\n그날들 - 대구(2023)\n그날들(2023)'], ['윤은채', '은밀하게 위대하게(2017)\n챠이카(2016)\n레베카(2016)'], ['유희준', '시간을 파는 상점(2017)'], ['하지혜', '둥근 해가 떴습니다(2012)\n연극 이(爾)(2010)\n짐(2007)'], ['백시연', '나도 이제 결혼하고 싶다(2021)\n제5회 한국여성극작가전 - 그 집(2019)\n연애플레이리스트(2018)'], ['고형우', '애니 모어 스토리(2020)\n두드려라 맥베스(2018)'], ['이인규', '수상한 흥신소(2021)\n라면(2021)\n러브 액츄얼리(2019)'], ['최정원', '컴프롬어웨이(2023)\n맘마미아 - 천안(2023)\n맘마미아 - 수원(2023)'], ['유아름', '1948 여수 - 여수(2022)\n1948 여수 - 여수(2020)\n그해 분장실(2020)'], ['신성록', '드라큘라(2023)\n벤허(2023)\n스위니토드(2022)'], ['김성진', '사명(2021)\n숙희(2021)\n언플러그드(2020)'], ['김화영', '고목(2023)\n장녀들(2023)\n스카프와 나이프(2022)'], ['이란희', '노르망디(2023)\n칸사이 주먹(2022)\n노르망디(2022)'], ['홍경인', '준생(2023)\n왓 이프(2023)\n행복(2023)'], ['홍나현', '22년 2개월(2023)\n붉은머리 안(2023)\n홍련(2023)'], ['남윤호', '코리올라누스(2021)\n보도지침(2017)\n월요쇼케이스 - 보도지침(2017)'], ['강보라', '리미트(2018)\n뷰티풀 라이프(2018)'], ['변서윤', '룸넘버13 - 울산(2018)\n룸넘버13(2016)\n내 깡패같은 로맨스(2015)'], ['김지현', '그날들 - 대구(2023)\n그날들(2023)\n스위니토드(2022)'], ['이시원', '극적인 하룻밤(2023)\n오싹한 연애(2020)\n당신 안녕(2016)'], ['엄기준', '그날들 - 수원(2023)\n그날들 - 대구(2023)\n그날들(2023)'], ['윤은채', '은밀하게 위대하게(2017)\n챠이카(2016)\n레베카(2016)'], ['유희준', '시간을 파는 상점(2017)'], ['하지혜', '둥근 해가 떴습니다(2012)\n연극 이(爾)(2010)\n짐(2007)'], ['백시연', '나도 이제 결혼하고 싶다(2021)\n제5회 한국여성극작가전 - 그 집(2019)\n연애플레이리스트(2018)'], ['고형우', '애니 모어 스토리(2020)\n두드려라 맥베스(2018)'], ['이인규', '수상한 흥신소(2021)\n라면(2021)\n러브 액츄얼리(2019)'], ['최정원', '컴프롬어웨이(2023)\n맘마미아 - 천안(2023)\n맘마미아 - 수원(2023)'], ['유아름', '1948 여수 - 여수(2022)\n1948 여수 - 여수(2020)\n그해 분장실(2020)'], ['신성록', '드라큘라(2023)\n벤허(2023)\n스위니토드(2022)'], ['김성진', '사명(2021)\n숙희(2021)\n언플러그드(2020)'], ['김화영', '고목(2023)\n장녀들(2023)\n스카프와 나이프(2022)'], ['이란희', '노르망디(2023)\n칸사이 주먹(2022)\n노르망디(2022)'], ['홍경인', '준생(2023)\n왓 이프(2023)\n행복(2023)'], ['홍나현', '22년 2개월(2023)\n붉은머리 안(2023)\n홍련(2023)'], ['남윤호', '코리올라누스(2021)\n보도지침(2017)\n월요쇼케이스 - 보도지침(2017)'], ['강보라', '리미트(2018)\n뷰티풀 라이프(2018)'], ['변서윤', '룸넘버13 - 울산(2018)\n룸넘버13(2016)\n내 깡패같은 로맨스(2015)'], ['김지현', '그날들 - 대구(2023)\n그날들(2023)\n스위니토드(2022)'], ['이시원', '극적인 하룻밤(2023)\n오싹한 연애(2020)\n당신 안녕(2016)'], ['엄기준', '그날들 - 수원(2023)\n그날들 - 대구(2023)\n그날들(2023)'], ['윤은채', '은밀하게 위대하게(2017)\n챠이카(2016)\n레베카(2016)'], ['유희준', '시간을 파는 상점(2017)'], ['하지혜', '둥근 해가 떴습니다(2012)\n연극 이(爾)(2010)\n짐(2007)'], ['백시연', '나도 이제 결혼하고 싶다(2021)\n제5회 한국여성극작가전 - 그 집(2019)\n연애플레이리스트(2018)'], ['고형우', '애니 모어 스토리(2020)\n두드려라 맥베스(2018)'], ['이인규', '수상한 흥신소(2021)\n라면(2021)\n러브 액츄얼리(2019)'], ['최정원', '컴프롬어웨이(2023)\n맘마미아 - 천안(2023)\n맘마미아 - 수원(2023)'], ['유아름', '1948 여수 - 여수(2022)\n1948 여수 - 여수(2020)\n그해 분장실(2020)'], ['신성록', '드라큘라(2023)\n벤허(2023)\n스위니토드(2022)'], ['김성진', '사명(2021)\n숙희(2021)\n언플러그드(2020)'], ['김화영', '고목(2023)\n장녀들(2023)\n스카프와 나이프(2022)'], ['이란희', '노르망디(2023)\n칸사이 주먹(2022)\n노르망디(2022)'], ['홍경인', '준생(2023)\n왓 이프(2023)\n행복(2023)'], ['홍나현', '22년 2개월(2023)\n붉은머리 안(2023)\n홍련(2023)'], ['남윤호', '코리올라누스(2021)\n보도지침(2017)\n월요쇼케이스 - 보도지침(2017)'], ['강보라', '리미트(2018)\n뷰티풀 라이프(2018)'], ['변서윤', '룸넘버13 - 울산(2018)\n룸넘버13(2016)\n내 깡패같은 로맨스(2015)'], ['김지현', '그날들 - 대구(2023)\n그날들(2023)\n스위니토드(2022)'], ['이시원', '극적인 하룻밤(2023)\n오싹한 연애(2020)\n당신 안녕(2016)'], ['엄기준', '그날들 - 수원(2023)\n그날들 - 대구(2023)\n그날들(2023)'], ['윤은채', '은밀하게 위대하게(2017)\n챠이카(2016)\n레베카(2016)'], ['유희준', '시간을 파는 상점(2017)'], ['하지혜', '둥근 해가 떴습니다(2012)\n연극 이(爾)(2010)\n짐(2007)'], ['백시연', '나도 이제 결혼하고 싶다(2021)\n제5회 한국여성극작가전 - 그 집(2019)\n연애플레이리스트(2018)'], ['고형우', '애니 모어 스토리(2020)\n두드려라 맥베스(2018)'], ['이인규', '수상한 흥신소(2021)\n라면(2021)\n러브 액츄얼리(2019)'], ['최정원', '컴프롬어웨이(2023)\n맘마미아 - 천안(2023)\n맘마미아 - 수원(2023)'], ['유아름', '1948 여수 - 여수(2022)\n1948 여수 - 여수(2020)\n그해 분장실(2020)'], ['신성록', '드라큘라(2023)\n벤허(2023)\n스위니토드(2022)'], ['김성진', '사명(2021)\n숙희(2021)\n언플러그드(2020)'], ['김화영', '고목(2023)\n장녀들(2023)\n스카프와 나이프(2022)'], ['이란희', '노르망디(2023)\n칸사이 주먹(2022)\n노르망디(2022)'], ['홍경인', '준생(2023)\n왓 이프(2023)\n행복(2023)'], ['홍나현', '22년 2개월(2023)\n붉은머리 안(2023)\n홍련(2023)'], ['남윤호', '코리올라누스(2021)\n보도지침(2017)\n월요쇼케이스 - 보도지침(2017)'], ['강보라', '리미트(2018)\n뷰티풀 라이프(2018)'], ['변서윤', '룸넘버13 - 울산(2018)\n룸넘버13(2016)\n내 깡패같은 로맨스(2015)'], ['김지현', '그날들 - 대구(2023)\n그날들(2023)\n스위니토드(2022)'], ['이시원', '극적인 하룻밤(2023)\n오싹한 연애(2020)\n당신 안녕(2016)'], ['엄기준', '그날들 - 수원(2023)\n그날들 - 대구(2023)\n그날들(2023)']]
Counter({'윤은채': 1, '은밀하게 위대하게(2017)\n챠이카(2016)\n레베카(2016)': 1})
{'윤은채': 1, '은밀하게 위대하게(2017)\n챠이카(2016)\n레베카(2016)': 1}

In [ ]:
## 뮤지컬 배우
driver.get("http://www.playdb.co.kr/artistdb/list.asp?code=013003")
time.sleep(3)
driver.find_element(By.XPATH, '//*[@id="contents"]/div[2]/table/tbody/tr[1]/td/table/tbody/tr/td[2]/a[2]').click()
time.sleep(2)
iframe_element = driver.find_element(By.ID, "list_ifm")  # iframe의 id를 사용하여 찾는 예시
driver.switch_to.frame(iframe_element)
musical_actor = []
for i in range(1, 6):
  for j in range(3, 80, 4):
    # play_DF 에 있는 장소 추출
    name = driver.find_element(By.XPATH, '/html/body/table/tbody/tr['+str(j)+']/td/table/tbody/tr/td[1]/table/tbody/tr/td[2]/a').text
    name_work = driver.find_element(By.XPATH, '/html/body/table/tbody/tr['+str(j)+']/td/table/tbody/tr/td[5]').text
    musical_actor.append([name, name_work])
    print(name, name_work)
  driver.find_element(By.XPATH, '/html/body/table/tbody/tr[84]/td/a['+str(i)+']').click()

임태경 할란카운티(2023)
지저스 크라이스트 수퍼스타(2022)
나폴레옹 헌정 콘서트(2022)
김다현 루쓰(2023)
더 그레이티스트 뮤지컬 콘서트 - 용인(2022)
미세스 다웃파이어(2022)
차지연 컴프롬어웨이(2023)
차지연 콘서트(2023)
아마데우스(2023)
김지현 그날들 - 대구(2023)
그날들(2023)
스위니토드(2022)
바다 안양 시 승격 50주년 기념 신년음악회 - 안양(2023)
제주신화월드 카운트다운 2023 - 제주(2022)
드라뮤지션 바다 콘서트 - 하남(2022)
규현 규현 & HYNN 콘서트(2023)
벤허(2023)
2023 서울파크뮤직페스티벌(2023)
박호산 기형도 플레이(2023)
오셀로(2023)
무제의 시대(2022)
주지훈 주지훈 팬미팅(2019)
생명의 항해(2010)
돈 주앙(2009)
강태을 몬테크리스토(2023)
엘리자벳(2022)
엑스칼리버(2022)
정민 스모크(2023)
사의찬미 콘서트(2023)
구텐버그(2023)
장승조 킹아더(2019)
더 데빌(2017)
구텐버그(2014)
이자람 노인과 바다 - 평택(2023)
순신(2023)
노인과 바다 - 경기 광주(2023)
김도현 배니싱(2018)
리차드3세(2018)
금강 1894 - 성남(2017)
송원근 오페라의 유령(2023)
레드북(2023)
이프덴(2022)
소냐 포르테 디 콰트로 ＆ 소냐 콘서트 - 구미(2023)
뮤지컬 갈라 콘서트 - 함양(2022)
라비앙로즈 - 화성(2022)
문혜원 타오르는 어둠 속에서(2023)
제15회 대구국제뮤지컬페스티벌 - 스페셜5(2021)
인현왕후 - 김천(2019)
이율 트레이스 유(2023)
모래시계(2022)
트레이스 유(2021)
박해미 블루 블라인드 - 의정부(2023)
박해미 콘서트 - 구리(2023)
어게인 - 여고동창생(2023)
이태원 블루 블라인드 - 의정부(2023)
헤다가블러(2023)
엘리자벳(2018)
김선경 아몬드(2022)
포미니츠(2021)
메노포즈(2018)
린아 레미제라블(2023)
스위니토드(2022)
몬테크리스토(2020)
인순이 우드스탁 뮤직 & 아트 페어 - 포천(2023)
인순이 콘서트 - 전주(2022)
2022 춘천 팸팸 페스타(2022)
이현수 제11회 대구국제뮤지컬페스티벌 - 아름다운 슬픈 날(2017)
화려한 싱글들(2012)
순이야 사랑해(2012)
김도형 영웅(2022)
명성황후(2021)
스위니토드(2019)
백주연 할란카운티(2023)
삼총사(2022)
잭 더 리퍼(2021)
이희정 벤허(2023)
루쓰(2023)
프랑켄슈타인(2021)
임강성 다시 동물원(2023)
은밀하게 위대하게
오선지 걸어가는 작곡가(2022)
오정해 동백꽃 피는 날(2022)
장사익 오정해 콘서트 - 고양(2022)
오정해의 농담 - 정읍(2019)
키 디 아지트 - 키 랜드(2019)
키 팬미팅(2018)
지구를 지켜라(2017)
김아선 오페라의 유령(2023)
드라큘라(2022)
삼총사(2022)
김수아 비듬(2023)
패션의 신 - 광명(2023)
패션의 신 - 과천(2023)
혜은이 김승미 콘서트(2022)
혜은이 콘서트(2020)
혜은이 디너쇼(2019)
송상은 블랙메리포핀스(2023)
눈을 뜻하는 수백 가지 단어들(2022)
언성(2017)
정준하 시티오브엔젤(2019)
청춘페스티벌 2016(2016)
형제는 용감했다(2015)
윤복희 윤복희 콘서트 - 오산(2021)
하모니(2021)
39(2020)
이상은 영웅(2011)
영웅(2011)
명성황후(2011)
이재환 22년 2개월(2023)
인간의 법정(2022)
엑스칼리버(2022)
소찬휘 레트로슈퍼콘서트 - 대구(2023)
박남정 소찬휘 콘서트 - 대구(2023)
2022 구례 자연드림 락페스티벌(2022)
조민아 온에어 시즌 3(2009)
렌트(2009)
온에어(2008)
황정민 리차드3세(2022)
김문정 콘서트(2019)
오이디푸스(2019)
려욱 우드스탁 뮤직 & 아트 페어 - 포천(2023)
팬레터(2021)
썸데이 씨어터 라스트 칸타빌레(2021)
박완규 부활 콘서트(2023)
김경호 박완규 소찬휘 콘서트(2019)
포에버 콘서트 - 가평(2019)
심규선 심규선 콘서트(2023)
심규선 콘서트(2022)
심규선 유승우 콘서트 - 부산(2022)
백재현 오늘을 기억해 - 계룡(2022)
슈퍼 루나틱 - 계룡(2021)
슈퍼 루나틱 - 안동(2020)
김성규 김성규 콘서트(2023)
레드북(2023)
킹키부츠(2022)
이동수 스페셜 라이어(2021)
라이어 1탄(2018)
라이어 1탄(2017)
정의욱 설공찬(2023)
스크루테이프(2023)
스크루테이프(2023)
김신의 삼총사(2023)
삼총사(2022)
고래고래 콘서트(2018)
온유 태양의 노래(2022)
태양의 노래(2021)
태양의 노래(2021)
이신성 연애시대(2013)
로미오와 줄리엣(2013)
결혼(2013)
김지현 호프(2023)
호프(2020)
김미경 남경주 김지현의 토크 뮤직 - 수원(2014)
유나영 투모로우 모닝(2017)
라카지(2014)
라카지(2012)
유정은 청춘연가 - 목포(2022)
영웅을 기다리며 - 부산(2016)
그남자 그여자(2015)
김세용 2016 자라섬 뮤지컬 페스티벌(2016)
빌리 엘리어트(2010)
이용우 제3회 이데일리 문화대상(2016)
클럽 살로메(2015)
댄싱9 시즌2 갈라쇼(2014)
김원식 청춘연가 - 목포(2022)
스페셜 라이어(2021)
라이어 1탄(2018)
조성지 맨 오브 라만차(2021)
스위니토드(2019)
스위니토드(2016)
다나 별이 빛나는 밤에(2016)
위대한 캣츠비 RE
위대한 캣츠비 RE
소유진 갈매기(2022)
82년생 김지영(2022)
리어왕(2021)
양금석 불효자는 웁니다 - 김해(2022)
2018 평창동계올림픽 성공기원 콘서트 - 대전(2017)
2017 새해음악회 - 음성(2017)
선우 트레이스 유(2023)
젠틀맨스 가이드(2020)
셜록홈즈(2020)
김선영 오필리어(2014)
뮤지컬 배우 선영과 함께 하는 크리스마스 콘서트(2013)
백야(2012)
팀 팀 콘서트 (2023)
황태자 루돌프(2014)
퍼밀리어 스토리(2014)
이소정 포미니츠(2022)
베르나르다 알바(2021)
이소정 with 조윤성 성민제 Paco - 부산(2017)
이지명 멸화군(2023)
제16회 대구국제뮤지컬페스티벌 - 산들(2022)
창업(2021)
박진우 레베카(2019)
안나 카레니나(2019)
오! 캐롤(2018)
박지아 마우스트랩(2023)
76 페스티벌 - 심청전을 짓다(2021)
엘리펀트 송(2019)
강연종 하트스트링스 - 부산(2023)
강연종 콘서트 - 대전(2020)
가야의 노래(2019)
서현 서현 팬미팅(2023)
서현 팬미팅(2018)
아니벌써 콘서트(2017)
서현진 신데렐라(2015)
궁(2010)
최원준 사랑은 비를 타고(2014)
막돼먹은 영애씨(2012)
막돼먹은 영애씨(2011)
강인 궁(2012)
제너두(2008)
정진호 2016 자라섬 뮤지컬 페스티벌(2016)
아르센 루팡(2013)
뮤지컬 13(2012)
이광용 외솔 겨레의 등불 최현배 - 울산(2016)
레베카(2014)
엘리자벳(2013)
안두호 마우스트랩(2023)
아가사 - 공주(2022)
서툰 사람들(2022)
이연경 알로하 나의 엄마들(2022)
지붕위의 바이올린(2022)
작은 아씨들(2021)
최종선 영웅(2022)
지저스 크라이스트 수퍼스타(2020)
마리 앙투아네트(2019)
이도국 스페셜 라이어(2021)
브라더 포인트(2019)
제5회 무죽 페스티벌 - 브라더 포인트(2019)
하희라 러브레터(2022)
굿바이걸(2008)
우리가 애인을 꿈꾸는 이유(2004)
신문성 심청전을 짓다(2022)
76 페스티벌 - 심청전을 짓다(2021)
이카이노의 눈(2020)
벤 벤 콘서트(2022)
지소울 벤 콘서트 - 창원(2021)
벤 콘서트(2020)
김영지 남진 콘서트 - 구리(2022)
롤링 21주년 기념공연 vol.3(2016)
라우더스 패밀리 콘서트(2015)
김홍표 대한민국전형적인살인청부업자이야기(2020)
부장들(2019)
서울서울서울(2018)
박성훈 알로하 나의 엄마들(2022)
지붕위의 바이올린(2022)
작은 아씨들(2021)
박은영 미리내 삼대 - 부천(2023)
불편한 편의점(2023)
마이 맘(2015)
윤승욱 신의 손을 빌린 남자 - 안산(2019)
영웅(2017)
에쿠스콘서트콰이어 26회 정기연주회(2015)
K2 어떤가요 콘서트(2022)
K2 김성면 콘서트(2019)
김성면 & 에메랄드캐슬 콘서트(2018)
김사은 삼총사(2014)
삼총사(2013)
사랑은 비를 타고(2011)
오상은 월남스키부대(2014)
김종욱 찾기(2013)
캐치 미 이프 유 캔(2012)
김학준 언틸 더 데이(2012)
언틸 더 데이(2011)
언틸 더 데이(2011)
이석 지킬 앤 하이드 - 김해(2012)
부니부니(2010)
맘마미아 - 부산(2010)
임재청 더 스트레인지(2019)
김구 가다보면 - 인천(2019)
마리아 마리아 - 고양(2014)
박혜경 2017 대구포크페스티벌(2017)
이안 행복드림콘서트(2015)
파크 콘서트 - 성남(2015)
박시은 연애시대(2011)
JESUS JESUS(2008)
홍상진 마마(2019)
프린세스 프링(2018)
갤럭시키즈(2017)
김도원 마리아 마리아(2016)
락시터(2013)
락시터(2012)
박나래 박나래의 농염주의보(2019)
슈퍼 디셈버 페스티벌 - 의정부(2018)
원더우먼 페스티벌(2017)
최윤호 십이야(2010)
테너를 빌려줘 - 부산(2009)
테너를 빌려줘(2009)
이강 이원복의 먼나라 이웃나라 클래식 콘서트(2014)
팝콘(2011)
설공찬전(2010)
고미경 순신(2023)
신과 함께_저승편(2023)
금란방(2022)

In [ ]:
len(play_actor), len(musical_actor)

NameError: ignored

In [ ]:
import pandas as pd
play_actor = pd.DataFrame(play_actor)
musical_actor = pd.DataFrame(musical_actor)

In [ ]:
now = datetime.datetime.now()
play_actor.to_csv("/data/raw/play_actor" + now.strftime('%Y-%m-%d') + ".csv", encoding='utf-8')
musical_actor.to_csv("/data/raw/musical_actor" + now.strftime('%Y-%m-%d') + ".csv", encoding='utf-8')

## 네이버 연극정보 크롤링

In [ ]:
driver.get("https://naver.com")
time.sleep(3)
driver.find_element(By.XPATH, '//*[@id="query"]').send_keys("연극 " + play_list[1][0] + " 기본정보")
driver.find_element(By.XPATH, '//*[@id="query"]').send_keys(Keys.ENTER)
time.sleep(3)
time.sleep(2)
# 출연진 정보
driver.find_element(By.XPATH, '//*[@id="main_pack"]/div[2]/div[1]/div[3]/div/div/ul/li[3]/a').click()
time.sleep(3)
actor = []

response = requests.get(driver.current_url)
html_data = BeautifulSoup(response.text, 'html.parser')
actor_name = html_data.select('div.list_image_info > ul > li > div > div')
for a in actor_name:
  print(a.get_text())
  tag = a.get_text().split(" ")
  actor.append([tag[2], tag[5]])
string = []
for a in actor:
  string.append(", ".join(a))
act = "/".join(string)

  한혜진   사치
  박하선   사치
  임수향   요시노
  서예화   요시노
  류이재   치카
  오한결   후타
  이강욱   멀티

In [ ]:
import requests
from bs4 import BeautifulSoup

driver.maximize_window()
wb = Workbook(write_only=True)
ws = wb.create_sheet('네이버 리뷰 크롤링 테스트')
ws.append(['Name', 'Genre', 'Period', 'Time', 'Place', 'Produce', 'Intro', 'Actor'])

review_site = []
# 네이버 검색창에 입력 후 엔터
for i in range(249):
  info_group = ""
  info_period = ""
  info_time = ""
  info_place = ""
  info_produce = ""
  intro = ""
  driver.get("https://naver.com")
  time.sleep(3)
  driver.implicitly_wait(1)
  driver.find_element(By.XPATH, '//*[@id="query"]').send_keys("연극 " + play_list[i][0] + " 기본정보")
  driver.find_element(By.XPATH, '//*[@id="query"]').send_keys(Keys.ENTER)
  time.sleep(3)

  try:
    # 연극 기본 정보
    info_group = driver.find_element(By.XPATH, '//*[@id="main_pack"]/div[2]/div[2]/div[1]/div/div[1]/dl/div[1]/dd').text
    info_period = driver.find_element(By.XPATH, '//*[@id="main_pack"]/div[2]/div[2]/div[1]/div/div[1]/dl/div[2]/dd').text
    info_time = driver.find_element(By.XPATH, '//*[@id="main_pack"]/div[2]/div[2]/div[1]/div/div[1]/dl/div[3]/dd').text
    info_place = driver.find_element(By.XPATH, '//*[@id="main_pack"]/div[2]/div[2]/div[1]/div/div[1]/dl/div[4]/dd').text
    info_produce = driver.find_element(By.XPATH, '//*[@id="main_pack"]/div[2]/div[2]/div[1]/div/div[1]/dl/div[5]/dd').text
    intro = driver.find_element(By.XPATH, '//*[@id="main_pack"]/div[2]/div[2]/div[2]/div/div[2]').text
    try:
      time.sleep(2)
      # 출연진 정보
      driver.find_element(By.XPATH, '//*[@id="main_pack"]/div[2]/div[1]/div[3]/div/div/ul/li[3]/a').click()
      time.sleep(3)
      actor = []

      response = requests.get(driver.current_url)
      html_data = BeautifulSoup(response.text, 'html.parser')
      actor_name = html_data.select('div.list_image_info > ul > li > div > div')
      for a in actor_name:
        print(a.get_text())
        tag = a.get_text().split(" ")
        actor.append([tag[2], tag[5]])
      string = []
      for a in actor:
        string.append(", ".join(a))
      act = "/".join(string)
    except:
      print("출연자정보X :", i)
  except:
    print("기본정보X : ", i)


  ws.append([play_list[i][0], info_group, info_period, info_time, info_place,info_produce,intro, act])
  print(play_list[i][0], info_group, info_period, info_time, info_place,info_produce,intro, act)

wb.save('/data/raw/네이버 연극정보 크롤링 테스트_231002.xlsx')
#test1 = driver.find_element(By.XPATH, '//*[@id="main_pack"]/div[2]/div[1]/div/h2/span[1]/strong/a')
#test = driver.find_element(By.CSS_SELECTOR, '#sp_nws_all1 > div.news_wrap.api_ani_send > div > a')
#print(exhibition.text)

  고영빈   민준
  김정원   민준
  진승욱   민준
  피설아   수지
  아인   수지
  박선영   수지
  김하늘   수지
  윤계열   남자멀티
  박건엽   남자멀티
  정성화   남자멀티
  김일강   남자멀티
  배설하   여자멀티
  안예슬   여자멀티
  김예은   여자멀티
  조하연   여자멀티
너의목소리가들려 연극 > 코미디극 90분 2018.12.06. (목)~오픈런 월, 금 15:50, 18:00 화 ~ 목 16:00 토, 일 14:00, 16:30, 18:30 * 10/15(일), 10/22(일), 10/29(일) 14:30, 16:40 * 9/28(목), 9/30(토) ~ 10/2(월) 14:00, 16:30, 18:30 * 9/29(금) 공연 없음 * 10/3(화), 10/9(월) 14:30, 16:40 도토리씨어터 설앤수컴퍼니 재개발 지역에 발생한 갑작스러운 화재로 많은 사람들이 죽고 수지는 엄마를 잃게 된다. 방화범으로 몰린 수지는 교도소에 가게 되고... 10년의 수감생활을 마친 수지는 엄마와의 추억이 깃든 옛 동네로 발걸음을 옮긴다. 고영빈, 민준/김정원, 민준/진승욱, 민준/피설아, 수지/아인, 수지/박선영, 수지/김하늘, 수지/윤계열, 남자멀티/박건엽, 남자멀티/정성화, 남자멀티/김일강, 남자멀티/배설하, 여자멀티/안예슬, 여자멀티/김예은, 여자멀티/조하연, 여자멀티
기본정보X :  1
바닷마을다이어리 연극 > 드라마극 110분 2023.10.08. (일)~2023.11.19. (일) 화, 목, 금 19:30
수 15:00, 19:30
토 14:00, 18:00
일 16:00

* 매주 월요일 공연 없음 예술의전당 오페라하우스 자유소극장 좌석배치도 라이브러리컴퍼니  고영빈, 민준/김정원, 민준/진승욱, 민준/피설아, 수지/아인, 수지/박선영, 수지/김하늘, 수지/윤계열, 남자멀티/박건엽, 남자멀티/정성화, 남자멀티/김일강, 남자멀티/배설하, 여자멀티/안예슬, 여자멀티/김예은, 여자멀티/조하연, 여자멀티
  노진원   더 늘근도둑
  전재형   더 늘근도둑
  김상묵   더 늘근도둑
  박철민   덜 늘근도둑
  태항호   덜 늘근도둑
  주우성   덜 늘근도둑
  이호연   수사관
  안태영   수사관
  유일한   수사관
  더 늘근도둑   노진원
  더 늘근도둑   전재형
  더 늘근도둑   김상묵
  덜 늘근도둑   박철민
  덜 늘근도둑   태항호
  덜 늘근도둑   주우성
  수사관   이호연
  수사관   안태영
  수사관   유일한
늘근도둑이야기 연극 > 코미디극 100분 2022.03.05. (토)~오픈런 화, 수 19:30
목 20:00
금 17:00, 20:00
토 15:00, 18:00
일, 공휴일 14:00, 17:00

* 매주 월요일 공연 없음
* 9/28(목), 9/29(금) 14:00 17:00
* 10/2(월), 10/3(일), 10/9(월) 14:00, 17:00
* 10/4(수), 10/10(화) 공연 없음 아트포레스트 (주)나인스토리 대통령 취임 특사로 감옥에서 풀려난 두 늙은 도둑. 노후 대책을 위한 마지막 한탕을 꿈꾸며 '그분'의 미술관에 잠입하게 된다. 엄청난 부를 축척하고 엄청난 권위를 자랑하는 '그분'의 미술관엔 세계적인 현대 미술가들의 작품이 소장되어 있지만 작품의 가치를 모르는 두 늙은 도둑은 '그분'의 금고만을 노린다. 노진원, 더/전재형, 더/김상묵, 더/박철민, 덜/태항호, 덜/주우성, 덜/이호연, 수사관/안태영, 수사관/유일한, 수사관/더, /더, /더, /덜, /덜, /덜, /수사관, 이호연/수사관, 안태영/수사관, 유일한
  안평강   시청
  김동빈   시청
  김무섭   시청
  이수연   성내
  홍리나   성내
  조수현   성내
  설종환   구의
  이유경   방배
  김준   역삼/역장
  김태환   역삼/역장
  신준일   역삼/역장
2호선세입자 연극 > 드라마극 90분 2022.01.14. (금)~오픈런 [9월 공연 시간]
월 ~ 목 17:00
금 17:00, 20:00
토 12:50, 15:00, 17:15, 19:30
일 13:00, 15:30, 18:00

*9/12(화), 9/26(화) 공연 없음

*9/1(금) 17:00
*9/2(토) 13:00,15:30,18:00
*9/3(일) 14:00,16:30
*9/14(목) 17:00,19:30
*9/28(목), 9/29(금) 14:00,16:30

[10월 공연 시간]
월 ~ 목 17:00
금 17:00, 20:00
토 12:50, 15:00, 17:15, 19:30
일, 공휴일 14:00, 16:30

*10/1(일), 10/2(월), 10/3(화), 10/8(일) 13:00,15:30,18:00
*10/25(수) 17:00, 20:00 바탕골소극장 제7회 웰컴 대학로 아버지의 뒤를 이어 기관사가 되고싶은 청년, 이호선 하지만 취업도 실패, 사랑도 실패, 무엇 하나 되는 일이 없다. 간신히 2호선 역무원으로 취직하게 되지만 그마저도 불안한 계약직이다. 애인에게 차이고 술에 취한 채 차고지까지 가게 된 호선은 그곳에서 믿을 수 없는 광경을 목격하게 되는데.. 나갈 수 없기에 남아야 하는 세입자들! 나갈 수 없기에 보내야 하는 호선! 개통 이래 가장 빵빵 터지는 승객들이 온다! 눈을 깜빡이는 순간조차 아까운 코믹감동 휴먼판타지. 안평강, 시청/김동빈, 시청/김무섭, 시청/이수연, 성내/홍리나, 성내/조수현, 성내/설종환, 구의/이유경, 방배/김준, 역삼/역장/김태환, 역삼/역장/신준일, 역삼/역장
  윤주희   마혜리
  강단비   마혜리
  주하영   마혜리
  유이주   마혜리
  박정윤   마혜리
  최하은   마혜리
  김시윤   마혜리
  김현지   마혜리
  김종훈   야한길
  정태영   야한길
  서도운   야한길
  구도진   야한길
  홍대권   야한길
  김도연   야한길
  성엽   야한길
  이수영   금나리
  이슬기   금나리
  고민지   금나리
  남은지   금나리
  문아연   금나리
  이지아   금나리
  고명진   금나리
  정채림   금나리
  서호영   리처드 홍
  최혁   리처드 홍
  이진호   리처드 홍
  오세영   리처드 홍
  임연   리처드 홍
  홍성민   리처드 홍
  손형민   리처드 홍
  이진호   멀티맨
  김보근   멀티맨
  정문석   멀티맨
  임현모   멀티맨
  권순형   멀티맨
  이동규   멀티맨
  김범준   멀티맨
한뼘사이 연극 > 로맨스극 100분 2021.03.19. (금)~오픈런 [9월 공연 일정]
월 ~ 금 15:00, 17:20, 19:30
토 11:50, 14:00, 16:10, 18:20, 20:30
일 13:00, 15:10, 17:20, 19:30

* 9/28(목), 9/29(금) 13:00, 15:10, 17:20, 19:30

[10월 공연 일정]
월 ~ 금 15:00, 17:20, 19:30
토 11:50, 14:00, 16:10, 18:20, 20:30
일 13:00, 15:10, 17:20, 19:30
* 10/8(일)11:50, 14:00, 16:10, 18:20, 20:30

* 10/2(월), 10/3(화), 10/9(월) 13:00, 15:10, 17:20, 19:30 라온아트홀 극단 파릇 한 뼘 남짓한 사이를 둔 4명의 오피스텔 이웃들, 불같은 성격의 걸크러쉬 강력부 마검사와 속마음은 1도 전하지 못하는 까불이, 검사출신 야변호사의 아슬아슬 한뼘사이, 악질 범죄는 사라지고 국민을 위한 나라를 만들겠다는 신입 사회부 금기자와 인생 한방! 뭐 있나!? 나만 이렇게 사는 건 아니잖아? 알고 보면 연약한 남자, 사기꾼 금자의 한껏 좁혀진 한뼘사이! 닿을 듯 말듯한 한뼘사이에서 이들의 아슬아슬 알콩달콩한 이야기가 시작된다! 윤주희, 마혜리/강단비, 마혜리/주하영, 마혜리/유이주, 마혜리/박정윤, 마혜리/최하은, 마혜리/김시윤, 마혜리/김현지, 마혜리/김종훈, 야한길/정태영, 야한길/서도운, 야한길/구도진, 야한길/홍대권, 야한길/김도연, 야한길/성엽, 야한길/이수영, 금나리/이슬기, 금나리/고민지, 금나리/남은지, 금나리/문아연, 금나리/이지아, 금나리/고명진, 금나리/정채림, 금나리/서호영, 리처드/최혁, 리처드/이진호, 리처드/오세영, 리처드/임연, 리처드/홍성민, 리처드/손형민, 리처드/이진호, 멀티맨/김보근, 멀티맨/정문석, 멀티맨/임현모, 멀티맨/권순형, 멀티맨/이동규, 멀티맨/김범준, 멀티맨
기본정보X :  5
옥탑방고양이       윤주희, 마혜리/강단비, 마혜리/주하영, 마혜리/유이주, 마혜리/박정윤, 마혜리/최하은, 마혜리/김시윤, 마혜리/김현지, 마혜리/김종훈, 야한길/정태영, 야한길/서도운, 야한길/구도진, 야한길/홍대권, 야한길/김도연, 야한길/성엽, 야한길/이수영, 금나리/이슬기, 금나리/고민지, 금나리/남은지, 금나리/문아연, 금나리/이지아, 금나리/고명진, 금나리/정채림, 금나리/서호영, 리처드/최혁, 리처드/이진호, 리처드/오세영, 리처드/임연, 리처드/홍성민, 리처드/손형민, 리처드/이진호, 멀티맨/김보근, 멀티맨/정문석, 멀티맨/임현모, 멀티맨/권순형, 멀티맨/이동규, 멀티맨/김범준, 멀티맨
  장우진   독고
  김동준   독고
  이강혁   독고
  조영임   염영숙
  문상희   염영숙
  박은영   염영숙
  정예지   시현
  정이수   시현
  서지영   시현
  한윤서   오선숙
  홍가경   오선숙
  김은지   오선숙
  김준희   경만
  김윤희   경만
  김서준   경만
  차미연   정인경
  장희재   정인경
  임혜진   정인경
  김나온   멀티맨
  지상록   멀티맨
  윤선근   멀티맨
불편한편의점 연극 > 드라마극 100분 2023.04.08. (토)~오픈런 수 ~ 금 19:30
토 13:30, 16:00, 18:30
일 14:00, 17:00

* 9/28(목) 13:30, 16:00, 18:30
* 9/29(금), 10/2(월), 10/3(화), 10/9(월) 14:00, 17:00
* 매주 월요일, 화요일 공연 없음 후암씨어터 극단 지우 서울역에서 노숙 중인 사내 '독고'. 어느 날 70대 여사 '임영숙'의 지갑을 찾아준 인연으로 그녀가 운영하는 편의점 '올웨이즈'에서 야간 알바를 시작한다. 장우진, 독고/김동준, 독고/이강혁, 독고/조영임, 염영숙/문상희, 염영숙/박은영, 염영숙/정예지, 시현/정이수, 시현/서지영, 시현/한윤서, 오선숙/홍가경, 오선숙/김은지, 오선숙/김준희, 경만/김윤희, 경만/김서준, 경만/차미연, 정인경/장희재, 정인경/임혜진, 정인경/김나온, 멀티맨/지상록, 멀티맨/윤선근, 멀티맨
기본정보X :  7
좀비오마이갓       장우진, 독고/김동준, 독고/이강혁, 독고/조영임, 염영숙/문상희, 염영숙/박은영, 염영숙/정예지, 시현/정이수, 시현/서지영, 시현/한윤서, 오선숙/홍가경, 오선숙/김은지, 오선숙/김준희, 경만/김윤희, 경만/김서준, 경만/차미연, 정인경/장희재, 정인경/임혜진, 정인경/김나온, 멀티맨/지상록, 멀티맨/윤선근, 멀티맨
  김기정   한만수
  호천   한만수
  이한   한만수
  이윤경   고은실
  박완형   고은실
  김유림   고은실
  민유리   고은실
  차용환   이경필
  황요셉   이경필
  민들샘   이경필
  엄준연   이경필
  엄선영   김희선
  한아름   김희선&방여사
  권현진   김희선
  박한솔   멀티맨
  이정혁   멀티맨
  유우헌   멀티맨
  여찬구   멀티맨
라면 연극 > 코미디극 100분 2020.04.04. (토)~오픈런 월 ~ 금 14:30, 16:45, 19:00
토 12:00, 14:05, 16:10, 18:15, 20:20
일 12:45, 14:50, 16:55, 19:00

* 9/28(목), 9/29(금) 12:45, 14:50, 16:55, 19:00 해피시어터 (주)엠컬쳐컴퍼니 네 남녀가 만나면서 일어나는 레트로 코믹극 김기정, 한만수/호천, 한만수/이한, 한만수/이윤경, 고은실/박완형, 고은실/김유림, 고은실/민유리, 고은실/차용환, 이경필/황요셉, 이경필/민들샘, 이경필/엄준연, 이경필/엄선영, 김희선/한아름, 김희선&방여사/권현진, 김희선/박한솔, 멀티맨/이정혁, 멀티맨/유우헌, 멀티맨/여찬구, 멀티맨
  이대우   준수
  정회형   준수
  김호준   준수
  김예지   지연
  송다영   지연
  김은수   지연
  임종철   멀티
  김동섭   멀티
  김정원   멀티
  전상혁   멀티
핫식스 연극 > 로맨스극 120분 2018.08.02. (목)~오픈런 월, 금 15:20, 18:30
화 ~ 목 16:30
토, 일 13:20, 16:00, 19:00

* 10/15(일) 10/22(일), 10/29(일) 14:00, 17:10
* 9/28(목), 9/30(토) ~ 10/2(월) 13:20, 16:00, 19:00
* 9/29(금) 공연 없음
* 10/3(화), 10/9(월) 14:00, 17:10 도토리씨어터 설앤수컴퍼니 대학교 때 뜨거운 사랑을 했던 지연과 준수. 시간이 흐를수록 너무 익숙해져서 가족인지 연인인지 짜릿함은 없고 짜증만 늘어난다. 이대우, 준수/정회형, 준수/김호준, 준수/김예지, 지연/송다영, 지연/김은수, 지연/임종철, 멀티/김동섭, 멀티/김정원, 멀티/전상혁, 멀티
기본정보X :  10
3일간의비       이대우, 준수/정회형, 준수/김호준, 준수/김예지, 지연/송다영, 지연/김은수, 지연/임종철, 멀티/김동섭, 멀티/김정원, 멀티/전상혁, 멀티
기본정보X :  11
기형도플레이 연극 > 드라마극 100분 2023.10.19. (목)~2023.10.29. (일) 화 ~ 금 19:30
토, 일 14:00, 18:00

* 10/29(일) 14:00
* 월요일 공연 없음 대학로아트원씨어터3관   이대우, 준수/정회형, 준수/김호준, 준수/김예지, 지연/송다영, 지연/김은수, 지연/임종철, 멀티/김동섭, 멀티/김정원, 멀티/전상혁, 멀티
  차용학   정해원
  최정헌   정해원
  랑연   최정신
  조윤영   최정신
  이봉준   이신우
  지호림   이신우
  장서연   윤이서
  신가은   윤이서
  김다흰   아마쿠사 아키
  오의식   아마쿠사 아키
  박은석   아마쿠사 아키
카페쥬에네스 연극 > 드라마극 100분 2023.09.25. (월)~2023.11.26. (일) 화 ~ 금 20:00
토, 공휴일 15:00, 19:00
일 15:00

* 9/25(월) 20:00
* 9/28(목), 10/3(화), 10/9(월) 15:00, 19:00
* 9/29(금) 공연 없음
* 매주 월요일 공연 없음 대학로 TOM(티오엠) 2 (주) 콘텐츠 합 1920년대 말, 일제강점기의 경성, 가을. 아내의 죽음으로 의열단을 탈퇴한 정해원은 아버지의 유산인 Cafe Jeunesse(청춘)를 운영한다. 어느 날, 술과 차를 팔고 부자 손님들의 귀중품을 거래를 중개하는 한편, 독립군들에게 자금을 지원하던 해원에게 동지이자 친우인 신우와 또 다른 단원 정신이 한 아이를 데리고 찾아온다. 전설적인 독립투사이자, 해원에게는 친형제와도 같은 동지 윤이안의 동생 이서. 신우와 정신, 그리고 해원은 작전명 ‘파란’을 통해 이서를 포함한 독립투사들의 아이들을 탈출시킬 계획을 세우고 카페 지하에 아이들을 숨기는 한 편, 직원들로 위장해 정보를 모으고 무기를 구하는 등 ‘파란’ 작전의 성공을 위해 혼신의 힘을 다하지만 한 남자의 등장으로 모든 것이 달라진다. 아마쿠사 아키. 경성 경무국에 새로 부임한 아키는 해원의 명성을 듣고 찾아왔다며 거절할 수 없는 거래를 부탁하는데... ‘장담하는데, 정 선생이라면 그 물건의 가치를 알아보실 겁니다.’ 차용학, 정해원/최정헌, 정해원/랑연, 최정신/조윤영, 최정신/이봉준, 이신우/지호림, 이신우/장서연, 윤이서/신가은, 윤이서/김다흰, 아마쿠사/오의식, 아마쿠사/박은석, 아마쿠사
기본정보X :  13
2호선세입자-연천       차용학, 정해원/최정헌, 정해원/랑연, 최정신/조윤영, 최정신/이봉준, 이신우/지호림, 이신우/장서연, 윤이서/신가은, 윤이서/김다흰, 아마쿠사/오의식, 아마쿠사/박은석, 아마쿠사
기본정보X :  14
★추석특집★코미디의맛/쇼미더퍼니       차용학, 정해원/최정헌, 정해원/랑연, 최정신/조윤영, 최정신/이봉준, 이신우/지호림, 이신우/장서연, 윤이서/신가은, 윤이서/김다흰, 아마쿠사/오의식, 아마쿠사/박은석, 아마쿠사
  김중   오상우
  지상록   오상우
  이상희   김지연
  김도경   멀티녀
  주우성   멀티남
수상한흥신소 연극 > 드라마극 100분 2021.06.21. (월)~오픈런 [8/1(화) ~ 8/18(금)]
월 ~ 금 14:30, 17:00
토 12:00, 14:30, 17:00, 19:30
일 13:00. 15:30, 18:00
* 8/15(화) 12:00, 14:30, 17:00, 19:30

[8/19(토) ~ 8/31(목)]
월 ~ 금 14:30
토 12:00, 14:30, 17:00, 19:30
일 13:00. 15:30, 18:00 소극장 선물 1관 홈페이지 블로그 영혼을 보는 청년 오상우. 그는 영혼들의 이루지 못한 소원을 들어주는 서비스센터를 운영하고 있다. 여느 날과 마찬가지로 영혼들의 의뢰를 해결하던 상우. 서비스센터 앞 쓰레기 무단 투기의 범인을 찾기 위해 쓰레기봉투를 뒤지던 중 의문의 버킷리스트를 발견하고, 이후 그가 벌인 일로 인해 걷잡을 수 없는 사태가 벌어지고 마는데... 김중, 오상우/지상록, 오상우/이상희, 김지연/김도경, 멀티녀/주우성, 멀티남
기본정보X :  16
카르멘 연극 > 드라마극 100분 2023.09.08. (금)~2023.10.01. (일) 화 ~ 금 19:30
토, 일 15:00

* 9/28(목) 15:00
* 9/29(금) 공연 없음
* 매주 월요일 공연 없음 세종문화회관 M씨어터 좌석배치도   김중, 오상우/지상록, 오상우/이상희, 김지연/김도경, 멀티녀/주우성, 멀티남
기본정보X :  17
딜리버리 연극 > 코미디극 80분 2023.09.28. (목)~2023.11.26. (일) 화 ~ 금 19:30
토 15:00, 18:00
일, 공휴일 14:00, 17:00

* 9/28(목), 9/30(토), 10/1(일), 10/2(월), 10/7(토), 10/8(일) 15:00, 18:00
* 9/29(금) 16:00
* 10/3(화), 10/9(월) 14:00, 17:00
* 10/4(수), 10/10(화) 공연 없음
* 매주 월요일 공연 없음 여우별아트홀   김중, 오상우/지상록, 오상우/이상희, 김지연/김도경, 멀티녀/주우성, 멀티남
  양동원   고연출
  윤재성   이달수
  범승제   고연출
  김희현   고연출
  엄민욱   고연출
  박지오   고연출
  이정수   박지혜
  고명진   박지혜
  홍유림   박지혜
  양시아   박지혜
  이준송   이달수
  김진우   이달수
  이학재   이달수
  도한울   이달수
  최솔   유기자
  최성빈   유기자
  남아진   유기자
  이성연   유기자
  김상훈   고연출
  이창주   고연출
  전재진   고연출
  시원   박지혜
  정재희   박지혜
  최유경   박지혜
  김정규   이달수
  김창우   이달수
  나준영   이달수
  함우주   이달수
  김단하   유기자
  박애림   유기자
  윤수아   유기자
  윤혜윤   유기자
  최하은   박지혜
  고석기   대본 연출
스위치 연극 > 공포극 90분 2017.07.18. (화)~오픈런 월 ~ 금 15:00, 17:30
토 13:30, 15:40, 17:50, 20:00
일 13:30, 15:40, 17:50

*9/28(목) 15:40, 17:50
*9/29(금) 공연 없음
*9/30(토), 10/1(일), 10/2(월), 10/3(화) 15:40, 17:50, 20:00
*10/9(월) 13:30, 15:40, 17:50, 20:00 아스가르드 씨어터 아루또 손대는 작품마다 대박행진을 이끌어낸 연극계 흥행신화의 주인공 고연출. 극장은 신작 <로미오와 줄리엣> 연습에 한창이다. 극의 주인공으로 출연하게 된 지혜와 달수는 성공에 눈이 먼 고연출의 강압적인 훈련방식에 점점 지쳐가고, 급기야 극장에서 환청을 듣거나 귀신을 보는 등 기이한 현상들을 경험하게 된다. 한편, 과거 극장에서 일어난 불미스러운 사건을 조사하던 유기자는 고연출의 연속된 공연 흥행과 과거의 사건이 밀접한 관련이 있음을 직감하고 그의 수상한 행적을 쫓기 시작한다. 양동원, 고연출/윤재성, 이달수/범승제, 고연출/김희현, 고연출/엄민욱, 고연출/박지오, 고연출/이정수, 박지혜/고명진, 박지혜/홍유림, 박지혜/양시아, 박지혜/이준송, 이달수/김진우, 이달수/이학재, 이달수/도한울, 이달수/최솔, 유기자/최성빈, 유기자/남아진, 유기자/이성연, 유기자/김상훈, 고연출/이창주, 고연출/전재진, 고연출/시원, 박지혜/정재희, 박지혜/최유경, 박지혜/김정규, 이달수/김창우, 이달수/나준영, 이달수/함우주, 이달수/김단하, 유기자/박애림, 유기자/윤수아, 유기자/윤혜윤, 유기자/최하은, 박지혜/고석기, 대본
기본정보X :  19
이머시브씨어터카지노       양동원, 고연출/윤재성, 이달수/범승제, 고연출/김희현, 고연출/엄민욱, 고연출/박지오, 고연출/이정수, 박지혜/고명진, 박지혜/홍유림, 박지혜/양시아, 박지혜/이준송, 이달수/김진우, 이달수/이학재, 이달수/도한울, 이달수/최솔, 유기자/최성빈, 유기자/남아진, 유기자/이성연, 유기자/김상훈, 고연출/이창주, 고연출/전재진, 고연출/시원, 박지혜/정재희, 박지혜/최유경, 박지혜/김정규, 이달수/김창우, 이달수/나준영, 이달수/함우주, 이달수/김단하, 유기자/박애림, 유기자/윤수아, 유기자/윤혜윤, 유기자/최하은, 박지혜/고석기, 대본
지상의여자들 연극 > 드라마극 100분 2023.10.07. (토)~2023.10.12. (목) 화 ~ 목 19:30
토 19:00
일 15:00, 19:00

* 월요일 공연 없음 국립정동극장 세실 좌석배치도 제23회 SPAF 지상의 여자들
D-4
연극 2023.10.07. ~ 2023.10.12.
극단 돌파구 〈지상의 여자들〉
공연종료
연극 2022.10.27. ~ 2022.10.30.
＇집에사는몬스터＇ 연극 > 드라마극 100분 2023.09.28. (목)~2023.10.03. (화) 목, 월 19:30
금, 토 19:00
일 15:00, 19:00
화 15:00 LG아트센터 서울 U+ 스테이지 라마플레이 공연중
집에 사는 몬스터
연극
2023.09.28. ~ 2023.10.03.
공연종료
집에 사는 몬스터
연극
2019.05.17. ~ 2019.05.26.
공연종료
집에 사는 몬스터
연극
2018.08.20. ~ 2018.09.02.
공연종료
집에 사는 몬스터 〈Monster in the Hall〉
연극
2018.01.13. ~ 2018.01.16.
  한규혁   최정우
  현동석   최정우
  김예나   양아영
  김태린   양아영
  이재연   임덕원
  양철진   임덕원
  박은선   장현진
  홍대교   신영복

출연자정보X : 22
사춘기메들리 연극 > 로맨스극 100분 2018.03.10. (토)~오픈런 토 13:00
일 14:00

* 9/28(목) 14:00
* 매주 월요일 ~ 금요일 공연 없음 아티스탄홀 마루프로덕션, 마스터프로덕션 전근이 잦은 아버지의 직장 때문에 친구도 없이 전학을 다녀야 했던 정우는 한적한 시골 마을에 전학을 오게 된다. 정우는 다시 전학을 가게 될 것이라는 사실을 알게 된 후, 관심 없던 아영에게 고백을 하고 덕원을 괴롭히던 일진에게도 결투를 신청한다.
기본정보X :  23
TheFather 연극 > 드라마극 100분 2023.09.19. (화)~2023.10.01. (일) 화 ~ 금 19:30
토, 일 16:00

* 월요일 공연 없음 세종문화회관 S씨어터
  정휘욱   김요한
  최창빈   김요한
  김윤   김요한
  박정윤   김요아
  윤지원   김요아
  김민서   김요아
  김락현   이무길
  이준경   이무길
  조영광   이무길

출연자정보X : 24
진짜나쁜소녀 연극 > 드라마극 95분 2023.03.17. (금)~오픈런 [9월 공연 시간]
화 ~ 금 17:00, 19:30
토 14:00, 16:15, 18:30
일, 공휴일 14:00, 16:30

[10월 공연 시간]
화 ~ 금 17:00, 19:30
토 14:00, 16:15, 18:30
일, 공휴일 14:00, 16:30

* 매주 월요일 공연 없음
*9/28(목) 14:00, 16:30
*9/29(금) 공연 없음
*9/30(토) 14:00, 16:15, 18:30
*10/2(월) 공연 없음
*10/3(화), 10/9(월) 14:00, 16:30 JTN 아트홀 1관 좌석배치도 ㈜나인진엔터테인먼트 잔인하게 살해당한 유명 여배우 황지희 살인 사건의 유력한 용의자로 지목된 이무길. 이무길은 자신의 무죄를 입증하기 위해 정치인, 대기업만 상대하는 승률 100프로 냉혈 변호사 김요한을 찾는다. 재판까지 한 달 남은 상황에서 무길은 요한의 동생 김요아를 납치하고 요한에게 거래를 제안한다. '네 동생 김요아를 살리고 싶으면 나의 무죄를 입증해' 이무길의 별장에서 마주한 두 사람, 요한은 완벽한 승소와 동생을 구하기 위해 처음부터 사건을 재구성해야 하고 완벽한 진실을 요구한다. 결국 1심에서 무죄를 받아낸다. 하지만, 재판 과정에서 무길은 요아를 납치하지 않았다는 것, 요아가 살인 사건과 연관성이 있다는 것이 밝혀진다. 사라진 김요아는 어디 있으며, 황지희 살인 사건의 진범은 누구인가. 검사 측의 항소를 대비하기 위해 다시 이무길 별장에서 마주한 두 사람, 각자의 숨겨진 진실이 밝혀진다.
기본정보X :  25

기본정보X :  26
모든날모든순간 연극 > 드라마극 80분 2023.09.08. (금)~2023.10.30. (월) 월, 수, 목, 금 20:00
토 15:00, 18:00
일, 공휴일 14:00, 17:00

* 10/2(월) 20:00
* 10/4(수) 공연 없음
* 매주 화요일 공연 없음 지즐소극장
기본정보X :  27
괴물B
기본정보X :  28
극적인하룻밤
기본정보X :  29
월드다방,#정답을작성해주세요,순례네국밥
기본정보X :  30
공포 연극 > 연극 140분 2014.09.25. (목)~2014.10.05. (일) 서강대학교 메리홀 홈페이지
기본정보X :  31
나의PS파트너
기본정보X :  32
신뺑파전2 연극 > 드라마극 90분 2023.10.07. (토) 토 15:00 남한산성아트홀 대극장 좌석배치도
  고민지   고시민 외
  고용선   나레이터 외
  김보경   김시민 외
  이강호   슈퍼맨
  이시래   이시민 외
  장우영   장시민 외
  한지혜   한시민 외
부동산오브슈퍼맨 연극 > 드라마극 150분 2023.10.14. (토)~2023.10.22. (일) 화 ~ 금 19:30
토, 일 15:00

* 월요일 공연 없음 대학로예술극장 소극장 좌석배치도 홈페이지 블로그 더 이상 전투도 괴물도 없는 지금 이 시대! 한물 간 영웅 슈퍼맨은 한국에서 전세 대출을 받아 전세를 살고 있다. 2년 계약 만기가 되어가던 어느 날, 슈퍼맨은 갑자기 집주인이 바뀌었다는 청천벽력 같은 소식을 듣게 되는데... 고민지, 고시민/고용선, 나레이터/김보경, 김시민/이강호, 슈퍼맨/이시래, 이시민/장우영, 장시민/한지혜, 한시민
  김준희   오영준
  권오율   오영준
  이호준   오영준
  신정만   김부장
  맹상열   김부장
  김현   김부장
  강대수   싸부
  오치운   싸부
  황원상   싸부
  신현규   삼동이
  김상록   삼동이
  김영규   삼동이
  한병수   슈퍼할배
  양현석   슈퍼할배
  박창희   슈퍼할배
  정다운   선화
  이연우   선화
  김민성   선화
망원동브라더스 연극 > 드라마극 90분 2022.12.01. (목)~오픈런 수 ~ 금 19:30
토 14:00, 17:00
일 14:00

* 6/6(화) 14:00
* 6/7(수) 공연 없음
* 매주 월요일, 화요일 공연 없음 제이엘씨어터 극단 지우 망원동 옥탑방에 살고 있는 영준은 지금 백수이지만 실은 이미 데뷔한 만화가. 어느 날 그의 옥탑방에 하나둘씩 객들이 찾아 들기 시작하는데... 김준희, 오영준/권오율, 오영준/이호준, 오영준/신정만, 김부장/맹상열, 김부장/김현, 김부장/강대수, 싸부/오치운, 싸부/황원상, 싸부/신현규, 삼동이/김상록, 삼동이/김영규, 삼동이/한병수, 슈퍼할배/양현석, 슈퍼할배/박창희, 슈퍼할배/정다운, 선화/이연우, 선화/김민성, 선화
기본정보X :  35
이리의땅 연극 > 드라마극 130분 2023.10.06. (금)~2023.10.08. (일) 금 19:00
토 14:00, 19:00
일 14:00 CKL스테이지   김준희, 오영준/권오율, 오영준/이호준, 오영준/신정만, 김부장/맹상열, 김부장/김현, 김부장/강대수, 싸부/오치운, 싸부/황원상, 싸부/신현규, 삼동이/김상록, 삼동이/김영규, 삼동이/한병수, 슈퍼할배/양현석, 슈퍼할배/박창희, 슈퍼할배/정다운, 선화/이연우, 선화/김민성, 선화
기본정보X :  36
택시안에서-부산       김준희, 오영준/권오율, 오영준/이호준, 오영준/신정만, 김부장/맹상열, 김부장/김현, 김부장/강대수, 싸부/오치운, 싸부/황원상, 싸부/신현규, 삼동이/김상록, 삼동이/김영규, 삼동이/한병수, 슈퍼할배/양현석, 슈퍼할배/박창희, 슈퍼할배/정다운, 선화/이연우, 선화/김민성, 선화
기본정보X :  37
택시안에서-서울       김준희, 오영준/권오율, 오영준/이호준, 오영준/신정만, 김부장/맹상열, 김부장/김현, 김부장/강대수, 싸부/오치운, 싸부/황원상, 싸부/신현규, 삼동이/김상록, 삼동이/김영규, 삼동이/한병수, 슈퍼할배/양현석, 슈퍼할배/박창희, 슈퍼할배/정다운, 선화/이연우, 선화/김민성, 선화
기본정보X :  38
달동네-부산       김준희, 오영준/권오율, 오영준/이호준, 오영준/신정만, 김부장/맹상열, 김부장/김현, 김부장/강대수, 싸부/오치운, 싸부/황원상, 싸부/신현규, 삼동이/김상록, 삼동이/김영규, 삼동이/한병수, 슈퍼할배/양현석, 슈퍼할배/박창희, 슈퍼할배/정다운, 선화/이연우, 선화/김민성, 선화
기본정보X :  39
인.투       김준희, 오영준/권오율, 오영준/이호준, 오영준/신정만, 김부장/맹상열, 김부장/김현, 김부장/강대수, 싸부/오치운, 싸부/황원상, 싸부/신현규, 삼동이/김상록, 삼동이/김영규, 삼동이/한병수, 슈퍼할배/양현석, 슈퍼할배/박창희, 슈퍼할배/정다운, 선화/이연우, 선화/김민성, 선화
기본정보X :  40
하마티아3부작:롤링앤롤링       김준희, 오영준/권오율, 오영준/이호준, 오영준/신정만, 김부장/맹상열, 김부장/김현, 김부장/강대수, 싸부/오치운, 싸부/황원상, 싸부/신현규, 삼동이/김상록, 삼동이/김영규, 삼동이/한병수, 슈퍼할배/양현석, 슈퍼할배/박창희, 슈퍼할배/정다운, 선화/이연우, 선화/김민성, 선화
기본정보X :  41
하마티아3부작:쿠쿠       김준희, 오영준/권오율, 오영준/이호준, 오영준/신정만, 김부장/맹상열, 김부장/김현, 김부장/강대수, 싸부/오치운, 싸부/황원상, 싸부/신현규, 삼동이/김상록, 삼동이/김영규, 삼동이/한병수, 슈퍼할배/양현석, 슈퍼할배/박창희, 슈퍼할배/정다운, 선화/이연우, 선화/김민성, 선화
기본정보X :  42
하마티아3부작:한국의역사       김준희, 오영준/권오율, 오영준/이호준, 오영준/신정만, 김부장/맹상열, 김부장/김현, 김부장/강대수, 싸부/오치운, 싸부/황원상, 싸부/신현규, 삼동이/김상록, 삼동이/김영규, 삼동이/한병수, 슈퍼할배/양현석, 슈퍼할배/박창희, 슈퍼할배/정다운, 선화/이연우, 선화/김민성, 선화
이장 연극 > 드라마극 90분 2023.10.26. (목)~2023.10.29. (일) 목, 금 19:30
토 18:00
일 15:00, 19:00 국립정동극장 세실 좌석배치도 제23회 SPAF D-23
이장
연극
2023.10.26. ~ 2023.10.29.
공연종료
이장(移葬) - 수원
연극
2022.07.02. ~ 2022.07.02.
공연종료
이장
연극
2021.10.08. ~ 2021.10.24.
기본정보X :  44
연습3.극작연습-물고기로죽기 연극 > 드라마극 70분 2023.10.20. (금)~2023.10.22. (일) 금 20:00
토 17:00
일 14:00, 18:00 국립정동극장 세실 좌석배치도 제23회 SPAF
기본정보X :  45
싸움의기술,졸_2.0
기본정보X :  46
에너지_보이지않는언어 연극 > 드라마극 90분 2023.10.28. (토)~2023.10.29. (일) 토 15:00, 20:00
일 15:00 아르코예술극장 소극장 좌석배치도 제23회 SPAF
기본정보X :  47
노셔널히스토리 연극 > 드라마극 75분 2023.10.12. (목)~2023.10.15. (일) 목, 금 19:30
토, 일 16:00 아르코예술극장 좌석배치도 제23회 SPAF
기본정보X :  48
SPAF패키지
기본정보X :  49
SPAF하마티아3부작패키지
기본정보X :  50
이프온리크리스마스특별공연-광주
기본정보X :  51
이프온리크리스마스특별공연-대구
기본정보X :  52
이프온리크리스마스특별공연-대학로
기본정보X :  53
러브액츄얼리첫번째사연_크리스마스특별공연-부산
기본정보X :  54
99%-화성
기본정보X :  55
띨뿌리-화성
기본정보X :  56
-전주
기본정보X :  57
당신에게닿는길 연극 > 드라마극 105분 2023.10.05. (목)~2023.10.29. (일) 화 ~ 금 19:30
토, 일 15:00

* 매주 월요일 공연 없음 홍익대 대학로 아트센터 소극장 홈페이지
기본정보X :  58
플라멩코별곡 연극 > 드라마극 50분 2023.10.01. (일) 일 16:00 소극장 산울림 제8회 판 페스티벌
기본정보X :  59
나의불편한,망원동연적
기본정보X :  60
“뷰티풀라이프”-대구
기본정보X :  61
#정답을작성해주세요
소년소녀모험백서 연극 > 드라마극 60분 2023.10.26. (목) 목 19:00 대학로 민송아트홀 2관 제8회 청소년을 위한 공연예술축제(청공축제) 어린 시절, 톰과 친구들에게는 떠나지 않으면 안 될 이유들이 있었다. 그것은 무엇이었을까? 톰과 허크가 보여주는 모험과 용기, 폴리 이모와 톰, 허크와 허크 아버지가 일깨워주는 가족 간의 사랑, 톰에게 갑자기 찾아온 사랑, 베키와 톰이 이뤄가는 순수한 첫사랑. 그 모든 시간을 사랑, 모험, 용기로 손잡고 함께 걷는 소설 읽는 연극
기본정보X :  63
내엄마수연씨-대구
기본정보X :  64
내엄마수연씨-청주
기본정보X :  65
자전거여행 연극 > 드라마극 2023.10.13. (금)~2023.10.14. (토) 금 17:00
토 15:00 대전광역시청소년위캔센터
기본정보X :  66
조씨고아,복수의씨앗
기본정보X :  67
지수가누구야
푸른늑대의후예 연극 > 드라마극 90분 2023.10.27. (금) 금 19:00 대학로 민송아트홀 1관 제8회 청소년을 위한 공연예술축제(청공축제) 어느 작은 시골 마을 편의점에서 담배 도난 사건이 발생한다. 사건의 범인으로 '자연스레' 인근 아동 보호 시설에 살고 있는 고3 주영이 지목당한다. 주영은 진범을 잡기 위해 나선다. 한편, 같은 시설 출신인 채린은 몽골 10대의 성인식을 주제로 웹툰을 그리고 있다. 하지만 좀처럼 스토리를 전개시키지 못하며 괴로워한다. 둘은 고군분투하며 서로를 통해 본인들이 가지고 있던 편견과 두려움을 깨달아간다.
기본정보X :  69
하트비트 연극 > 연극 2015.08.03. (월) 김천문화예술회관 대공연장 홈페이지
TheMostBoringShowintheWorld 연극 > 드라마극 50분 2023.10.21. (토) 토 15:00, 18:00 대학로 민송아트홀 1관 제8회 청소년을 위한 공연예술축제(청공축제) This is the most boring show in the world. Nothing happens at all. It doesn't have a plot, nor any scenery. Like I said, this is the most boring show in the world. 이건 세상에서 가장 지루한 쇼야. 아무 일도 일어나지 않아. 줄거리도 없고, 무대 배경이나 장치도 없어. 내가 말했듯이, 이건 세상에서 가장 지루한 쇼야.
   XXL레오타드 안나수이 손거울 - 서울   2023.10.24.~2023.10.24.
   XXL 레오타드 안나수이 손거울 XXL Leotard Anna Sui Hand Mirror   2022.07.29.~2022.07.31.
   XXL 레오타드 안나수이 손거울 - 부산   2022.05.19.~2022.05.20.
   XXL레오타드 안나수이 손거울 - 원주   2021.12.01.~2021.12.01.
   연극 'XXL레오타드 안나수이 손거울' - 고양   2020.08.21.~2020.08.23.
   XXL레오타드 안나수이 손거울   2020.02.06.~2020.02.09.
   XXL 레오타드 안나수이 손거울 - 대전   2019.12.20.~2019.12.25.
   XXL 레오타드 안나수이 손거울 - 안산   2017.11.02.~2017.11.04.
   XXL레오타드 안나수이 손거울   2016.12.01.~2016.12.11.
   XXL 레오타드 안나수이 손거울 - 안산   2015.10.19.~2015.10.25.
XXL레오타드안나수이손거울 연극 > 드라마극 80분 2023.10.24. (화) 화 19:00 대학로 민송아트홀 2관 제8회 청소년을 위한 공연예술축제(청공축제) D-21
XXL레오타드 안나수이 손거울 - 서울
연극
2023.10.24. ~ 2023.10.24.
공연종료
XXL 레오타드 안나수이 손거울 XXL Leotard Anna Sui Hand Mirror
연극
2022.07.29. ~ 2022.07.31.
공연종료
XXL 레오타드 안나수이 손거울 - 부산
연극
2022.05.19. ~ 2022.05.20.
공연종료
XXL레오타드 안나수이 손거울 - 원주
연극
2021.12.01. ~ 2021.12.01.
공연종료
연극 'XXL레오타드 안나수이 손거울' - 고양
연극
2020.08.21. ~ 2020.08.23.
공연종료
XXL레오타드 안나수이 손거울
연극
2020.02.06. ~ 2020.02.09.
공연종료
XXL 레오타드 안나수이 손거울 - 대전
연극
2019.12.20. ~ 2019.12.25.
공연종료
XXL 레오타드 안나수이 손거울 - 안산
연극
2017.11.02. ~ 2017.11.04.
공연종료
XXL레오타드 안나수이 손거울
연극
2016.12.01. ~ 2016.12.11.
공연종료
XXL 레오타드 안나수이 손거울 - 안산
연극
2015.10.19. ~ 2015.10.25.
다음 , 손거울/, 안나수이/, 안나수이/, 손거울/, 안나수이/, 손거울/, 안나수이/, 안나수이/, 손거울/, 안나수이
기본정보X :  72
12인의성난사람들-청주       , 손거울/, 안나수이/, 안나수이/, 손거울/, 안나수이/, 손거울/, 안나수이/, 안나수이/, 손거울/, 안나수이
기본정보X :  73
1초       , 손거울/, 안나수이/, 안나수이/, 손거울/, 안나수이/, 손거울/, 안나수이/, 안나수이/, 손거울/, 안나수이
기본정보X :  74
선녀씨이야기 연극 > 드라마극 90분 2023.10.06. (금)~2023.10.08. (일) 금 19:30
토, 일 15:00 대학로아트원씨어터3관   , 손거울/, 안나수이/, 안나수이/, 손거울/, 안나수이/, 손거울/, 안나수이/, 안나수이/, 손거울/, 안나수이
기본정보X :  75
오늘도극한직업 연극 > 드라마극 80분 2023.10.13. (금)~2023.10.15. (일) 금 19:30
토 14:00, 18:00
일 15:00 대학로아트원씨어터3관   , 손거울/, 안나수이/, 안나수이/, 손거울/, 안나수이/, 손거울/, 안나수이/, 안나수이/, 손거울/, 안나수이
기본정보X :  76
2023산울림판페스티벌패키지       , 손거울/, 안나수이/, 안나수이/, 손거울/, 안나수이/, 손거울/, 안나수이/, 안나수이/, 손거울/, 안나수이
기본정보X :  77
2023전태일       , 손거울/, 안나수이/, 안나수이/, 손거울/, 안나수이/, 손거울/, 안나수이/, 안나수이/, 손거울/, 안나수이
기본정보X :  78

In [ ]:
wb.save('/data/raw/네이버 연극정보 크롤링 테스트_231001.xlsx')

In [ ]:
wb = Workbook(write_only=True)
ws = wb.create_sheet('네이버 리뷰 크롤링 테스트')
ws.append(['Name', 'ID', 'Score', 'Review'])

for j in range(30):
  # 링크로 이동
  driver.get(exhib_review_link_2['link'][j])
  time.sleep(2)
  test1 = driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[1]/div/div[1]/h3/span[2]/em/span')
  print(test1.text)
  # 리뷰 5개씩 크롤링 # 이걸 여러개 ...
  try:
    for t in range(100): # 최대 500개씩
      for i in range(1, 6):
        name = exhib_review_link_2['전시회 이름'][j]
        id = driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[' + str(i) + ']/review-list-item/div/div/div[1]/a[2]/span[1]').text
        score = driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[' + str(i) + ']/review-list-item/div/div/div[3]/div/span').text
        review = driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[' + str(i) + ']/review-list-item/div/div/p/span').text
        ws.append([name, id, score, review])
        print(name, id, score, review)
      driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[2]/a[2]').click()
      time.sleep(3)
  except:
    continue

#//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[1]/review-list-item/div/div
#//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[2]/review-list-item/div/div

wb.save('/data/raw/네이버 리뷰 크롤링 테스트_230925.xlsx')

## 네이버 리뷰 크롤링

In [ ]:
exhib_list = exhib_string.values.tolist()
exhib_list

[['거장의 시선, 사람을 향하다 - 영국 내셔널갤러리 명화전'],
 [' 일리야 밀스타인'],
 ['이경준 사진전: 원 스텝 어웨이'],
 ['백희나 그림책전'],
 ['2023년 9,10월-어둠속의대화'],
 ['럭스:시적해상도'],
 ['에르베 튈레展'],
 ['모네 인사이드'],
 ['스티키몬스터랩: 스틸 라이프'],
 ['스폰지밥의 우당탕탕 시간여행展'],
 ['요시고 사진전 - 부산'],
 ['진격의 거인전 FINAL in SEOUL'],
 [' 반고흐 인 서울'],
 ['문도 멘도: 판타스틱 시티 라이프'],
 ['스즈메의 문단속 展 in SHINSEGAE'],
 [' 오스틴 리: 패싱타임'],
 ['인사이드미 : 잃어버린 나의 감정을 찾아서'],
 ['2023년 9,10월-어둠속의대화'],
 ['알폰스무하 이모션 인 서울'],
 ['세르주 블로크展 : KISS'],
 ['동물 없는 동물원 展'],
 ['CAT ART : 고양이 미술사'],
 ['알폰스 무하: 더 골든 에이지'],
 ['빈센트 발 : ART OF SHADOW'],
 ['에곤실레와 클림트'],
 [' 창경궁 야경투어'],
 ['에바 알머슨 특별전 : 에바 알머슨, Andando'],
 ['팀보타 누적관람객 300만 - 탐화림 : 화림이 품은 탐의 이야기'],
 ['덕수궁 야경투어'],
 [' 어린왕자 인 서울'],
 ['2023국제농업박람회 - 순천'],
 [' 두근두근 도라에몽展'],
 ['맥스달튼 전시전 EP.2 영화의 순간들'],
 ['제22회 서울카페쇼 2023'],
 ['극장판 명탐정 코난: 흑철의 어영'],
 ['극장판 명탐정 코난: 흑철의 어영'],
 [' 반고흐 인 서울'],
 ['스즈메의 문단속 展 in SHINSEGAE'],
 [' 로렌 차일드 : 요정처럼 생각하기 展'],
 [' 2023 울산국제아트페어'],
 ['진격의 거인전 FINAL in SEOUL'],
 ['진격의 거인전 FINAL in SEOUL'],
 [' 빛의 시어터 입장권'],
 [' 아르떼뮤지엄'],
 [' 환희컵 박물관_환타지컵 박물관+장길환 미술관'],
 [' 용평리조트 뮤지엄 딥다이브'],
 ['강릉 참소리축음기＆에디슨과학박물관'],
 [' 디자인 가구 컬렉션 “어반베이스전＂'],
 [' 헤이리 93뮤지엄 에로틱 성박물관'],
 [' 코버월드+산사원 패키지'],
 [' 가평 남송미술관 단독상품'],
 [' 국립낙동강생물자원관'],
 [' 인피티니 플라잉 공연'],
 [' MCY파크+바니베어뮤지엄PKG'],
 ['다이노베이 DINO BAY'],
 [' 김해가야투어패스'],
 ['월드아트 서커스'],
 [' 라이크디즈위드 교동점_이쿵 개인전 〈Everyday Dream〉'],
 [' 라이크디즈위드 김광석거리점_'],
 [' 이월드 도라에몽 PKG '],
 [' 라이언 홀리데이 인 부산 체험관 입장권'],
 [' K-일러스트레이션페어 서울 2024'],
 ['아라리오뮤지엄 인 스페이스'],
 [' 데이비드 호크니: Bigger ＆ Closer '],
 [' 미술관에 피는 꽃 Ⅱ - 부산'],
 [' MSCHF : NOTHING IS SACRED'],
 [' 아르떼뮤지엄'],
 [' 국제아웃도어캠핑＆레포츠페스티벌 더 파이널 파트1'],
 ['조선셰프 서유구'],
 [' 뉴미디어뮤지컬'],
 [' 더마파크+노형수퍼마켙'],
 [' 더마파크+세계자동차＆피아노박물관'],
 [' 더마파크+카멜리아힐'],
 [' 러브랜드+아리랑 혼 공연'],
 [' 러브랜드+아트서커스'],
 [' 러브랜드+제주레일바이크'],
 [' 목장카페드르쿰다+아리랑혼 공연'],
 [' 아르떼뮤지엄'],
 [' 아이바가든 입장권'],
 [' 아트서커스'],
 [' 알제이 체험스튜디오 이용권'],
 [' 원더아일랜드'],
 [' 피규어뮤지엄'],
 [' 헬로키티아일랜드+노형수퍼마켙'],
 [' 헬로키티아일랜드+스카이워터쇼'],
 ['노형수퍼마켙'],
 ['불빛정원＆인생사진관'],
 ['아라리오뮤지엄 동문모텔Ⅰ＆ Ⅱ 통합권'],
 ['아라리오뮤지엄 탑동시네마'],
 ['아라리오뮤지엄 탑동시네마＆동문모텔I,II 통합권'],
 ['아르떼뮤지엄'],
 ['제주민속촌'],
 [' 청주 공룡월드 이용권'],
 [' 헤이리예술마을 '],
 [' 헤이리예술마을  10월 이용권'],
 [' 헤이리예술마을 _9월 이용권'],
 ['헤이리 미니어처 뮤지엄'],
 ['헤이리 한국 스토리 뮤지엄'],
 ['《I Like To Watch》'],
 ['2002 한일 월드컵 20주년 기념 특별전'],
 ['2023 어린이 현대미술 - 안성'],
 ['2023 인형극 페스티벌 - 이천'],
 ['강원종합박물관 _마진율변경'],
 ['경복궁의 인문학산책'],
 ['경주 코오롱호텔 타임 애프터 타임 전시회'],
 ['괴짜전'],
 ['구하우스미술관 관람권'],
 ['국립 고궁박물관 인문학산책'],
 ['극장판 엉덩이 탐정: 미스터리 가면 ~최강의 대결 - 부천'],
 ['더마파크+헬로키티아일랜드'],
 ['덕수궁의 인문학산책'],
 ['데이비드 호크니 ＆ 브리티시 팝아트 - 부산'],
 ['라이프 사진전 : 더 라스트 프린트'],
 ['마리오폰테의 트웰브'],
 ['미구엘 슈발리에 디지털 뷰티 시즌2'],
 ['바다 탐험대 옥토넛 어보브 앤 비욘드 : 육지 넘어 하늘까지!'],
 ['번개맨: 더 비기닝 - 부천'],
 ['볼로냐 일러스트 50주년 기념전'],
 ['부산 뮤지엄 원 ‘상실의 징후들＇'],
 ['북파크 라운지'],
 ['빅토리아 티렉스 '],
 ['빈센트 발 : ART OF SHADOW'],
 ['서울올림픽 35주년 기념전 〈Futuredays : One is All, All is One〉'],
 ['선릉 인문학산책'],
 ['성곡미술관 오픈콜: 이진영 《콘크리트 프루프 Concrete Proof》'],
 ['손철주의 ‘오래된 그림공부’'],
 ['시크릿 오브 컬러 올림피아 자그놀리'],
 ['안면도 오마이갤러리 20% 할인 입장권'],
 ['안젤름 키퍼 : 〈가을〉 - 대전'],
 ['안희선 가이드의 시간 여행 : 서울역사박물관 편'],
 ['앤서니 브라운의 행복극장展 - 광주'],
 ['앤서니브라운의 원더랜드 뮤지엄'],
 ['에드가 플랜스: In My Coffee Time'],
 ['에바 알머슨 특별전 : 에바 알머슨, Andando'],
 ['여주 쎈토이박물관 '],
 ['여주곤충박물관 입장권＆체험'],
 ['영화감독 정병길 개인전 : 자유.꿈.영화 '],
 ['오스틴 리 : 패싱 타임 아트스튜디오'],
 ['용인어린이상상의숲 요리조리스튜디오 〈상상파티시엘〉'],
 ['유동룡미술관'],
 ['일리야 밀스타인'],
 ['전남 영암곤충박물관 '],
 ['제주 빛의 벙커 10월 입장권 세잔＆칸딘스키 몰입형 예술전시'],
 ['제주 빛의 벙커 입장권 세잔＆칸딘스키 몰입형 예술전시'],
 ['창경궁의 인문학산책'],
 ['창덕궁의 인문학산책'],
 ['춘천 애니메이션박물관＆토이로봇관 '],
 ['피규어뮤지엄w 할인 티켓'],
 ['한국만화박물관 입장권'],
 ['헤이리 파주공룡박물관'],
 ['후지시로 세이지 북촌스페이스'],
 ['ART ROAD SHOWCASE ＆ ART EXHIBITION in KOREA 2023 : 아트로드 - 아트원정대 붓 들고 세계로'],
 ['TEA_time']]

In [ ]:
driver.maximize_window()

review_site = []
# 네이버 검색창에 입력 후 엔터
for i in range(153):
  driver.get("https://naver.com")
  time.sleep(3)
  driver.implicitly_wait(1)
  driver.find_element(By.XPATH, '//*[@id="query"]').send_keys(exhib_string[i])
  driver.find_element(By.XPATH, '//*[@id="query"]').send_keys(Keys.ENTER)
  time.sleep(3)


  # 전시 정보창이 있는지 확인하기 위함
  #exhibition = driver.find_element(By.XPATH, '//*[@id="main_pack"]/div[2]')
  #time.sleep(3)

  # 있다면 ...
  try:
    # 전시 정보 더보기로 이동
    driver.find_element(By.XPATH, '//*[@id="main_pack"]/div[2]/div[2]/div/div/div[3]/a/div').click()
    time.sleep(2)
    # 전시 예매로 이동
    driver.find_element(By.XPATH, '//*[@id="main_pack"]/div[2]/div[2]/div[1]/div/div[3]/div/ul/li[1]/a').click()
    time.sleep(2)
    # 예매자 리뷰 더보기 클릭
    driver.find_element(By.CSS_SELECTOR, '#container > div > div > div.wrap_review_lst > a > span').click()
    time.sleep(3)
    print(driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[1]/div/div[1]/h3/span[1]').text)
    # 리뷰 사이트 append
    review_site.append(driver.current_url)
  except:
    review_site.append('')



#test1 = driver.find_element(By.XPATH, '//*[@id="main_pack"]/div[2]/div[1]/div/h2/span[1]/strong/a')
#test = driver.find_element(By.CSS_SELECTOR, '#sp_nws_all1 > div.news_wrap.api_ani_send > div > a')
#print(exhibition.text)
print(review_site)

예매자 리뷰
예매자 리뷰
예매자 리뷰
예매자 리뷰
예매자 리뷰
예매자 리뷰
예매자 리뷰
예매자 리뷰
예매자 리뷰
예매자 리뷰
예매자 리뷰
예매자 리뷰
예매자 리뷰
['https://booking.naver.com/review/bizes/899755', '', '', '', '', '', '', '', 'https://booking.naver.com/review/bizes/949610', 'https://booking.naver.com/review/bizes/955615', '', '', '', 'https://booking.naver.com/review/bizes/875642', '', '', '', '', '', '', 'https://booking.naver.com/review/bizes/968616', '', 'https://booking.naver.com/review/bizes/974375', 'https://booking.naver.com/review/bizes/958812', '', '', '', '', '', '', '', 'https://booking.naver.com/review/bizes/958915', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'https://booking.naver.com/review/bizes/882663', '', '', '', '', '', '', '', 'https://booking.naver.com/review/bizes/837936', '', '', '', '', '', '', '', 'https://booking.naver.com/review/bizes/958812', '', '', '', '', 'https://booking.naver.com/review/bizes/929368', '', '', '', '', '', 'https://booking.naver.com/review/bizes/969234', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [ ]:
wb = Workbook(write_only=True)
ws = wb.create_sheet('네이버 리뷰 크롤링 테스트')
ws.append(['Name', 'ID', 'Score', 'Review'])

for j in range(30):
  # 링크로 이동
  driver.get(exhib_review_link_2['link'][j])
  time.sleep(2)
  test1 = driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[1]/div/div[1]/h3/span[2]/em/span')
  print(test1.text)
  # 리뷰 5개씩 크롤링 # 이걸 여러개 ...
  try:
    for t in range(100): # 최대 500개씩
      for i in range(1, 6):
        name = exhib_review_link_2['전시회 이름'][j]
        id = driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[' + str(i) + ']/review-list-item/div/div/div[1]/a[2]/span[1]').text
        score = driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[' + str(i) + ']/review-list-item/div/div/div[3]/div/span').text
        review = driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[' + str(i) + ']/review-list-item/div/div/p/span').text
        ws.append([name, id, score, review])
        print(name, id, score, review)
      driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[2]/a[2]').click()
      time.sleep(3)
  except:
    continue

#//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[1]/review-list-item/div/div
#//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[2]/review-list-item/div/div

wb.save('/data/raw/네이버 리뷰 크롤링 테스트_230925.xlsx')

In [ ]:
review_site

['https://booking.naver.com/review/bizes/899755',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'https://booking.naver.com/review/bizes/949610',
 'https://booking.naver.com/review/bizes/955615',
 '',
 '',
 '',
 'https://booking.naver.com/review/bizes/875642',
 '',
 '',
 '',
 '',
 '',
 '',
 'https://booking.naver.com/review/bizes/968616',
 '',
 'https://booking.naver.com/review/bizes/974375',
 'https://booking.naver.com/review/bizes/958812',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'https://booking.naver.com/review/bizes/958915',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'https://booking.naver.com/review/bizes/882663',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'https://booking.naver.com/review/bizes/837936',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'https://booking.naver.com/review/bizes/958812',
 '',
 '',
 '',
 '',
 'https://booking.naver.com/review/bizes/929368',
 '',
 '',
 '',
 '',
 '',
 'https://booking.naver.com/review/bizes/969234',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '']

In [ ]:
exhib_rank['link'] = review_site

In [ ]:
exhib_rank.to_csv('/data/raw/크롤링 리뷰 링크.csv', index=None)

## 리뷰 링크 데이터 불러오기

In [ ]:
import pandas as pd
exhib_rank = pd.read_csv('/data/raw/크롤링 리뷰 링크_230925.csv', encoding='utf-8')
exhib_rank = pd.DataFrame(exhib_rank)
exhib_rank

,전시회 이름,link,Unnamed: 2
0,"거장의 시선, 사람을 향하다 - 영국 내셔널갤러리 명화전",https://booking.naver.com/review/bizes/899755,NaN
1,［얼리버드］ 일리야 밀스타인,https://booking.naver.com/review/bizes/963297,NaN
2,［얼리버드］이경준 사진전: 원 스텝 어웨이,NaN,NaN
3,백희나 그림책전,https://booking.naver.com/review/bizes/923312,NaN
4,"［북촌］2023년 9,10월-어둠속의대화(DIALOGUE IN THE DARK)",NaN,NaN
...,...,...,...
148,한국만화박물관 입장권,NaN,NaN
149,헤이리 파주공룡박물관,NaN,NaN
150,후지시로 세이지 북촌스페이스,NaN,NaN
151,ART ROAD SHOWCASE ＆ ART EXHIBITION in KOREA 20...,NaN,NaN
152,TEA_time,NaN,NaN

In [ ]:
exhib_review_link = exhib_rank[['전시회 이름', 'link']]
exhib_review_link

,전시회 이름,link
0,"거장의 시선, 사람을 향하다 - 영국 내셔널갤러리 명화전",https://booking.naver.com/review/bizes/899755
1,［얼리버드］ 일리야 밀스타인,https://booking.naver.com/review/bizes/963297
2,［얼리버드］이경준 사진전: 원 스텝 어웨이,NaN
3,백희나 그림책전,https://booking.naver.com/review/bizes/923312
4,"［북촌］2023년 9,10월-어둠속의대화(DIALOGUE IN THE DARK)",NaN
...,...,...
148,한국만화박물관 입장권,NaN
149,헤이리 파주공룡박물관,NaN
150,후지시로 세이지 북촌스페이스,NaN
151,ART ROAD SHOWCASE ＆ ART EXHIBITION in KOREA 20...,NaN
152,TEA_time,NaN

In [ ]:
pd.isnull(exhib_review_link).sum()

전시회 이름      0
link      123
dtype: int64

In [ ]:
exhib_review_link_2 = exhib_review_link
exhib_review_link_2.dropna(axis=0)
exhib_review_link_2 = exhib_review_link_2.reset_index(drop=True)

In [ ]:
exhib_review_link_2.count()

전시회 이름    30
link      30
dtype: int64

In [ ]:
exhib_review_link_2

,전시회 이름,link
0,"거장의 시선, 사람을 향하다 - 영국 내셔널갤러리 명화전",https://booking.naver.com/review/bizes/899755
1,［얼리버드］ 일리야 밀스타인,https://booking.naver.com/review/bizes/963297
2,백희나 그림책전,https://booking.naver.com/review/bizes/923312
3,［9월예매］모네 인사이드,https://booking.naver.com/review/bizes/974352
4,스티키몬스터랩: 스틸 라이프,https://booking.naver.com/review/bizes/949610
5,스폰지밥의 우당탕탕 시간여행展,https://booking.naver.com/review/bizes/955615
6,요시고 사진전 - 부산,https://booking.naver.com/review/bizes/885136
7,진격의 거인전 FINAL in SEOUL,https://booking.naver.com/review/bizes/512380
8,문도 멘도: 판타스틱 시티 라이프,https://booking.naver.com/review/bizes/875642
9,알폰스무하 이모션 인 서울,https://booking.naver.com/review/bizes/944048
10,동물 없는 동물원 展,https://booking.naver.com/review/bizes/968616
11,［9월 예매］알폰스 무하: 더 골든 에이지,https://booking.naver.com/review/bizes/974375
12,［얼리버드］빈센트 발 : ART OF SHADOW,https://booking.naver.com/review/bizes/958812
13,［굿바이할인］에곤실레와 클림트,https://booking.naver.com/review/bizes/876433
14,"［얼리버드］에바 알머슨 특별전 : 에바 알머슨, Andando",https://booking.naver.com/review/bizes/966445
15,［굿바이할인］ 어린왕자 인 서울,https://booking.naver.com/review/bizes/706439
16,［ 대구전시 ］ 두근두근 도라에몽展,https://booking.naver.com/review/bizes/958915
17,［대구］ 라이크디즈위드 교동점_이쿵 개인전 〈Everyday Dream〉,https://booking.naver.com/review/bizes/765654
18,［대구］ 라이크디즈위드 김광석거리점_(미니 개인전: 기억과 상상),https://booking.naver.com/review/bizes/750911
19,［서울/코엑스］ K-일러스트레이션페어 서울 2024,https://booking.naver.com/review/bizes/463542
20,2002 한일 월드컵 20주년 기념 특별전,https://booking.naver.com/review/bizes/715056
21,괴짜전,https://booking.naver.com/review/bizes/882663
22,마리오폰테의 트웰브,https://booking.naver.com/review/bizes/837936
23,부산 뮤지엄 원 ‘상실의 징후들＇,https://booking.naver.com/review/bizes/918001
24,빈센트 발 : ART OF SHADOW,https://booking.naver.com/review/bizes/958812
25,시크릿 오브 컬러 올림피아 자그놀리,https://booking.naver.com/review/bizes/929368
26,앤서니 브라운의 행복극장展 - 광주,https://booking.naver.com/review/bizes/884227
27,앤서니브라운의 원더랜드 뮤지엄,https://booking.naver.com/review/bizes/933458
28,에드가 플랜스: In My Coffee Time,https://booking.naver.com/review/bizes/969234
29,"에바 알머슨 특별전 : 에바 알머슨, Andando",https://booking.naver.com/review/bizes/966445

In [ ]:
exhib_review_link_2['link'][0]

'https://booking.naver.com/review/bizes/899755'

In [ ]:
wb = Workbook(write_only=True)
ws = wb.create_sheet('네이버 리뷰 크롤링 테스트')
ws.append(['Name', 'ID', 'Score', 'Review'])

for j in range(30):
  # 링크로 이동
  driver.get(exhib_review_link_2['link'][j])
  time.sleep(2)
  test1 = driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[1]/div/div[1]/h3/span[2]/em/span')
  print(test1.text)
  # 리뷰 5개씩 크롤링 # 이걸 여러개 ...
  try:
    for t in range(100): # 최대 500개씩
      for i in range(1, 6):
        name = exhib_review_link_2['전시회 이름'][j]
        id = driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[' + str(i) + ']/review-list-item/div/div/div[1]/a[2]/span[1]').text
        score = driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[' + str(i) + ']/review-list-item/div/div/div[3]/div/span').text
        review = driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[' + str(i) + ']/review-list-item/div/div/p/span').text
        ws.append([name, id, score, review])
        print(name, id, score, review)
      driver.find_element(By.XPATH, '//*[@id="container"]/review-list/div/div/div/div[2]/a[2]').click()
      time.sleep(3)
  except:
    continue

#//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[1]/review-list-item/div/div
#//*[@id="container"]/review-list/div/div/div/div[1]/div/div[3]/ul/li[2]/review-list-item/div/div

wb.save('/data/raw/네이버 리뷰 크롤링 테스트_230925.xlsx')

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
"이 그림 본적 있어"라며 아는 척도 할 수 있을거 같습니다. 이렇게 작품을 아이들에게 노출 시켜주는것만으로도 공부가 될수 있네요
아는 엄마들에게 열심히 홍보했습니다
즐거운 추억이었습니다
［9월예매］모네 인사이드 chy**** 5 미디어 아트여서 그런거 모네, 르누아르, 세잔 등 일대기를 볼 수 있었던 좋은 전시가 된것 같아요 백화점 안에 있어서 전시보고 백화점 구경도 하고 편하고 재미있게 다녀온것 같습니당 ✌🏻
［9월예매］모네 인사이드 타미8 4 화가의 일대기를 작품과 매치시켜 이야기를 하듯 설명을 곁들여 화가의 작품세계에 쉽게 접근할 수 있었고 이해하기도 좋은 시간이였습니다. 모네의 마지막작품을 원화로 보고싶어 프랑스 오랑주리에 가고싶다는 생각이 들었습니다.
［9월예매］모네 인사이드 soar48 4 미디어 아트로 모네를 만날 수 있어 더욱 실감나고 황홀합니다.
［9월예매］모네 인사이드 mei**** 3
［9월예매］모네 인사이드 peacemaker2227 5 믿고 가는 그라운드시소입니다^^ 흥미진진하게 미술 교양 수업 듣고 나온 기분이예요.
［9월예매］모네 인사이드 green9 4 모네를 좋아하기 때문에 그리고 미디어아트도 좋아해서 좋은 전시회 보고 왔습니다.
전시회라기 보다는 상영이라고 하는 것이 맞겠지요.
편안하세 앉아서 멋진 전시회 감상 잘했어요.
［9월예매］모네 인사이드 따가운뒤통수 5
［9월예매］모네 인사이드 mei**** 1.5 35분 영상에 포토타임 20분 정도인데.. 전시개념보다는 미디어아트라 보면 맞고..
모네인사이드가 알폰스무하 더 골든에이지보다 실속이 없었다
모네만 보고 9900원 낼 바에야 15000원으로 무하전까지 보고 나오는 게 돈이 덜 아까울 듯
［9월예매］모네 인사이드 초코4178 5 모네 그림들 너무 이쁨!!
［9월예매］모네 인사이드 shara0225 4.5 아주 좋았어요
［9월예매］모네 인사이드 큐앤에이 4 작품을 영상으로 접하니 더 생생하고 좋았어요.
모네의 일생에 대한 이야기로 감상에 더욱 재미를 느꼈습니다!👏🏻👏🏻👏🏻
［9월예매］모네 인사이드 zbr**** 4
［9월예매］모네 인사이드 syj**** 5
［9월예매］모네 인사이드 BeyondTheGrooth 3 영화 장편까지는 아니고
단편 하나 정도 본다고 생각하면 되요

두 전시 같이 보는 티켓 값은 장편 하나 정도 되겠네요

겸사겸사 볼만해요
기념품은 딱히 손이 가지는 않아요

쉬는 날 기분 전환 겸 괜찮았어요
［9월예매］모네 인사이드 Milain 4 엄마랑 같이 왔는데 좋았어요! 근데 살짝 어지럽긴 했어요 🫨
［9월예매］모네 인사이드 이건업ㅅ겠지 4 영상은 화려하고 좋앗으나 설명이 꽤길고 흥미롭기보단 지루한게 더 컸습니다.. 그림과 영상은 너무 예뻣네요
［9월예매］모네 인사이드 로랑37 4 모네의 일생을 비디오아트로 쉽고 재밌고 감각적으로 보여줘서 좋았어요 마지막에 사진 찍을 시간도 주시고요! 이걸 보고 오르세 가서 모네 작품을 봤다면 좋았을 것 같네요 ㅎ
［9월예매］모네 인사이드 sszbqlr51 4.5 아이와 함께 관람했어요.
영상이 너무 아름다워요.
［9월예매］모네 인사이드 ekz**** 4.5 모네 좋았습니다
［9월예매］모네 인사이드 바로잡기12 5 자유롭게 앉아서 이야기와 콘텐츠를 즐기고 자유로운 시간도 있습니다.
［9월예매］모네 인사이드 dld**** 5 색감이 너무 아름답고 영상미가 예뻐요
스토리있는 구성 좋아요
［9월예매］모네 인사이드 blu**** 5 모네 좋아하시는 분들 꼭 가세요! 전시 따분하게 느끼시는 분들도 재밌게 볼 수 있는 전시에요~~
정시에 나래이션과 함께 시작하는 스토리 있는 영상전시이니 꼭 10분전 도착하셔서 두면을 바라볼 수 있는 입구쪽 사이드 좌석이나 정면 자리 잡으시고 영상 사영 전 책자 내용 후루룩 읽고 보시면 더 좋으실 것 같아요~ 모네의 생애와 함께 설명이 되어 그 그림이 어떻게 그려졌는지 알 수 있어 좋았습니다! 그리고 사람 덜한 오전 전시 추천합니다!
［9월예매］모네 인사이드 yamche782 5
［9월예매］모네 인사이드 하하남매0 2.5 어린이.유아 할인이없는이유를 알았다
오지말라는 눈치주는 분위기를 좀 느낀거같다..

그림자체는 좋았고 짧아서 아쉬울정도로 더 보고싶었다
［9월예매］모네 인사이드 alw**** 4 2개 공간에서 진행되는데 한쪽은 큰 화면
한쪽은 다른 공간에 비해 작은 화면으로 볼 수 있더라구요
마지막엔 아예 사진을 찍는 시간이 있어서 다같이 나가서 사진을 찍더라구요.. 차라리 공간이 두개이다보니 한쪽 공간에서만 사진 찍고 다른 한쪽은 영상을 계속 볼 수 있도록 진행하는 건 어땠을까 싶은 생각이 들었어요
그래도 모네의 그림을 큰 화면으로 볼 수 있어 참 좋았습니다~
［9월예매］모네 인사이드 kyunnnn 4.5 생각보다 짧다고느껴져서 아쉬웠지만 와.. 영상자체에 너무놀랐고 역시 모네는 색감이 장난아니였어요
［9월예매］모네 인사이드 ntmdgml60 5 두번째 방문.. 역시 좋았어요~
［9월예매］모네 인사이드 폴라리스6855 5 천장까지 모두 미디어아트로 채워질수 있었으면 좋았을텐데 조금 아쉽긴했지만 저렴한 가격으로 전시회 잘 봤어요^^
［9월예매］모네 인사이드 lov**** 5 모네 좋아하시는 분들은 매우 만족하실꺼같아요.
저의 최애 화가로 꼽는 모네 인생과 작품을
한번에 미디어로 관람할 수 있어서 좋았어요.
환상적인 시간이었습니다.
［9월예매］모네 인사이드 퀸지쌤 5 평일 오후3시 관람이라 한산하니 조용히 감상할 수 있어서 좋았어요. 정말 아름답고 가성비 좋은 전시!ㅎㅎ 편안하게 앉아서 온전히 감상할 수 있는 시간이었습니다
［9월예매］모네 인사이드 1324mnju 5 한편의 영화를 보는 느낌으로 시간이 금방갔어요. 그림도 좋았지만 모네에 대해서 알게되어 다음에 모네 작품을 감상할때 많은 도움이 될것같습니다.
［9월예매］모네 인사이드 라엘5399 2.5 정확히 10분전에 가야돼요. 대기할 장소가 마땅치 않아 다시 내려갔다 왔네요. 전시 막바지라 평일 5시에 사람은 거의 없었어요.
［9월예매］모네 인사이드 하하하하50 5 정말 갔던 전시회 중 최고였어요
가족이랑 같이 갔는데 모두가 모네에게 빠졌답니다
다음에 꼭 다시 올거 같아요
강추
이왕이면 좀 아는 예술가일 때 오시는 것을 추천 !
［9월예매］모네 인사이드 골목좋아합니다 5 너무 좋은 영상 잘봤습니다.
4면과 바닥까지 쏴주는 빔덕분에
보는 내내 즐거웠습니다
［9월예매］모네 인사이드 뚱또롱34 5 쪼았어용
19
스티키몬스터랩: 스틸 라이프 하야안우유 5 스티키 팬으로써 감동의 시간이였습니다.
시간 가는지 모르고 구경하다보니 2시간이 훌쩍...!
너무 추천합니다.
스티키몬스터랩: 스틸 라이프 ssujunging 5 스티키 좋아하는 사람이면 무조건 좋아합니다!!!
디테일 미쳤고 소품도 되게 귀엽고 힙하고 하여튼 되게 잘 꾸며져있어요 ㅎㅎ 너무 귀여워서 초반부부터 막 다들 하나하나 다 찍느라 주말에 가면 엄청 구경하기가 버거울거같아요 전 일요일 오후에 가서 괜찮았어요! 굿즈같은거 진짜 잘 안사는 스타일인데 너무 잘해놔서 굿즈 하나 사야겠다하고 샵갔는데 굿즈는 아쉬웠어요 살게 없었음 ㅠ 인형이나 필로우 키링 그립톡 스티커 이런거있으면 진짜 잘될거같은데.. 아쉽고요ㅠ 귀여워서 사진은 많이 찍었으나 직접 가서 봐야합니다 ^^
스티키몬스터랩: 스틸 라이프 RANGU 5 정말 너무너무 귀엽습니다...
얼리버드로 가서 저렴하게 관람하고 왔어요!
스티키몬스터랩: 스틸 라이프 kag**** 4 좋았습니다
스티키몬스터랩: 스틸 라이프 또치3772 5 너무 다 귀엽고~ 재밌었어요👍😁
스티키몬스터랩: 스틸 라이프 PS79 4.5 기대감을 안 가지고 가벼운 마음으로 가시는 편이
전시를 즐기기에 훨씬 잘 즐길 수 있을 듯 합니다.
스티키몬스터랩: 스틸 라이프 신화철87 4.5 몬스터들로 구성된 전시라 좀 유치할 거라 생각했는데, 생각보다 볼만하고 괜찮았습니다! 친한 후배가 왜 가보라는 지 알겠더라고요! 전시 잘 봤고, 그라운드시소도 관람 많이 하도록 할게요~!! ㅎㅎㅎㅎ
스티키몬스터랩: 스틸 라이프 소년82호 5 세상에나 네상에나 몬스터들이 사는 세상은 이리 귀엽군요..

어른들도 아이들도 정말 좋아할만한 전시 같습니다

정말 강추강추^^
스티키몬스터랩: 스틸 라이프 Tiamatt 5 강추
스티키몬스터랩: 스틸 라이프 홍님98 5
스티키몬스터랩: 스틸 라이프 쩐슬 5 2D의 귀여움과 3D의 귀여움은 차원이 다르다.
심장아프니까 조심하세요...
스티키몬스터랩: 스틸 라이프 스윗피오니 4.5 기대 안하고 갔었는데 퀄리티가 장난아니어서 좋았던 전시였어요
스티키몬스터랩: 스틸 라이프 chl**** 5 생각외로 너무 디테일하고 좋었어요 ;) 다음레도 보러갈게요
스티키몬스터랩: 스틸 라이프 레쓰고 5 미쳤어요... 세번봤어요...🫶🏻
스티키몬스터랩: 스틸 라이프 누룽지맛비비빅 5 항상 sml을 좋아해왔던 사람이라 기대가 컸는데 그 기대보다도 만족스러운 전시였습니다. 구성도 알찼고 그것에 맞춰 전시 된 디오라마들이 너무 세심해서 시간이 된다면 또 한 번 가보고 싶네요. 정말 추천합니다!
스티키몬스터랩: 스틸 라이프 희서늬 5 진짜 추천!! 돈이 안아까움여!!
스티키몬스터랩: 스틸 라이프 traveling R 5 스티키몬스터랩을 좋아하는 분들이라면 절대절대 후회하지 않을 전시예요.
디테일은 물론이고 색감, 전시 흐름도 너무 좋아요
보는 내내 "귀여워 미쳤다" 라는 말만 계속 했어요ㅠㅠㅠ
스티키몬스터랩: 스틸 라이프 Sanghak 5 귀여운 몬스터들이 우리의 일상을 너무나 재미있게 표현해소 진짜 공감되는 귀요미둘이다~~!!
스티키몬스터랩: 스틸 라이프 유빙고45 4.5 삶의 희노애락을 표현한 듯함
175
스폰지밥의 우당탕탕 시간여행展 51427 5
스폰지밥의 우당탕탕 시간여행展 민지4255 5
스폰지밥의 우당탕탕 시간여행展 둥뢍 5 어릴때부터 좋아했어서
들어가자마자 너무 설레고 뭉클했어요
저는 어른이 되었지만
스폰지밥은 여전히 귀엽고 밝네요ㅠㅠ
색감도 쨍하니 이쁘고 방마다 컨셉이 있어서
보는재미가 쏠쏠했어용 ㅎㅎ
스폰지밥 덕후라면 완전 강추입니다👍
스폰지밥의 우당탕탕 시간여행展 이타다끼마스요 5 사진 찍기 좋아요 ㅎㅎ 그리고 전시는 짧지만 퀄리티 좋아서 만족했어요!!
평일 12시조금 넘어서 갔는데 생각보다 사람이 그렇게 없어서 편하게 사진 찍을 수 있었어요~.
스폰지밥의 우당탕탕 시간여행展 gus**** 5 지인이 추천해서 남자친구랑 다녀왔는데 전시회 꾸며놓은 것도 너무 귀여웠고 무엇보다 사진이 찌이이인짜
잘 나와요!! 안내원 분들도 친절하시고 사람이 많아도 질서정연하게 착착 다녀서 넘넘 좋았습니당!
스폰지밥의 우당탕탕 시간여행展 Du23 4 오랜만에 스폰지밥을 봐서 좋았어요~ 전시회 퀄리티도 좋고 포토존이 많아서 나름 재밌고 괜찮았습니다~
스폰지밥의 우당탕탕 시간여행展 맛없는곳은피해가자 0.5 이걸 1인당 15000원을 받아먹고있네ㅋㅋㅋㅋ
다신안감 ㅎㅎ
스폰지밥의 우당탕탕 시간여행展 세라62 4.5 재밌었고 손거울도 받고 좋았지만 주말이라 그런지 사람이 너무 많아서 제대로 못 읽기도 하고 좀 힘들었어요
스폰지밥의 우당탕탕 시간여행展 끄아악21 4 다른 리뷰처럼 사람이 너무 많았어요.
막상 들어가면 볼 전시물은 많지 않은데 사진을 찍기위해 기다리는 시간이 오히려 길어요.
그래도 전시물이 귀엽고, 스펀지밥 좋아하시면 가볼 만 해요.
최대한 할인 받아서 가세요.
스폰지밥의 우당탕탕 시간여행展 AcidGreen 3 전시 자체는 가격에 비해 아쉬운 부분이 있지만 스폰지밥의 팬이라면 한번은 볼만 합니다. 전시장의 출구로 나오면 관람 여부와 관계없이 스토어에 갈 수 있는 점은 좋습니다. 구매욕구를 자극하는 아이템들이 꽤 있습니다. 포토카드 퀄리티도 좋은 편입니다.

전시 관람에 돈이 아까울 것 같아 고민이라면 캐릭터 상품점이나 포토카드만 이용하는 것도 괜찮을 것 같고, 휴일 3시 이후부터는 전시 입장 대기가 길어지는 편이니 2시 이전에 관람하는 것을 추천하고 싶네요^^
스폰지밥의 우당탕탕 시간여행展 냥발장0w0 5 지난번 스펀지밥 전시회때도 왔는데 그때와는 또다른 시간여행 컨셉으로 디테일도 잘 살리고 다 귀엽고 스탭분들도 친절하셨습니다
스폰지밥의 우당탕탕 시간여행展 박경민424 5
스폰지밥의 우당탕탕 시간여행展 NIKEJIN 5 너무 재밌었어용 ><ㅋㅋ
스폰지밥의 우당탕탕 시간여행展 하꼬4 4 비싼감이 없지 않아 있어요
스폰지밥의 우당탕탕 시간여행展 미똥구리 5 혼자 다녀왔음에도 정말 만족한 곳! 퀄리티가 미쳤구요 곳곳이 다 포토존입니다 •• 돈이 정말 아깝지 않음! 평일 오후에 가니까 여유롭게 잘 봤고 포토카드도 줄 없이 세개나 뽑고 왔으니 평일에 댕겨오세요!!! 굿즈도 넘 귀여워서 텅장댐
스폰지밥의 우당탕탕 시간여행展 은솔방울9 4.5 친구랑 같이갔는데 포토존도 많고 재밌었어요!!ദ്ദി˙∇˙)ว
스폰지밥의 우당탕탕 시간여행展 뚤뚤은뚠뚠 5 개관한지 얼마 안돼서 갔는데.. 평일이라 설마설마 하면서 갔는데 사람 너무많아서 ㅠㅠ거의 못즐겼어요 카페는 대기가 200팀 넘어서 들어가지도 못했네요 ㅠ 규모는 전에 도라에몽 전시랑 비슷한것같아요
스폰지밥의 우당탕탕 시간여행展 Tw 5 재밌었오요!!
스폰지밥의 우당탕탕 시간여행展 니9621 4.5 스폰지밥 덕후로서 너무 좋았어요.
주말에 가서 첨에는 줄서느라 바빴지만 뒤로 갈수록 여유있어요.
조금 더 많았으면 싶은 아쉬움도 있어요~!
더 많은 굿즈가 생기면 좋겠네요~
스폰지밥의 우당탕탕 시간여행展 best part24 2.5 그냥 사진찍기용으로 줄서서 지나가기만 하니까 자유롭게 관람하기가 힘들다
스폰지밥의 우당탕탕 시간여행展 AHIN32 5 너무너무좋았어요!!! 고퀄리티 포토존 진짜 굿굿ㅎㅎ 스폰지밥과 사진찍기 동심으로돌아간듯해서 너무좋았습니다ㅎㅎ
스폰지밥의 우당탕탕 시간여행展 이름이엄서 5 퀄 진짜
미쳤어요 짱임요 사람 엄청 많지만 기다려서 볼 가치ㅡ잇어요
진짜 꼭 가보세요
스폰지밥의 우당탕탕 시간여행展 현지6236 5 너무재밌구 중간에 사진찍어주시는 직원분덕분에 편히 왔어여!!
스폰지밥의 우당탕탕 시간여행展 굥이90 3.5 스펀지밥을 좋아하는 사람이라면 남녀노소 할 거없이 추억하기 좋은 곳 같습니다, 냉방이 약해서 조금 덥기도 했고 자유롭게 전시하고 싶었으나 줄서기를 하고 있어서 그 줄에서 대기하다가 포토존에서 사진만찍고 금방 다시 줄을 서야하는 시스템 처럼 되어 있습니다, 그냥 포토존이 많은 전시회라고 생각하면 될 것 같습니다. 다음에는 인원수 제한을 해서 자유롭게 다니며 구경할 수 있는 전시회가 되었으면 좋겠습니다~
스폰지밥의 우당탕탕 시간여행展 c1sp08 5 주말에 다녀와서 사람은 많았지만, 나름 질서정연하게 진행되어 너무 좋았어요👍🏻👍🏻 뭣보다 스텝분들 엄청 착하셨어요:)
스폰지밥의 우당탕탕 시간여행展 뇽밥 4 퀄리티는 좋았지만 생각만큼은 아니구 전시를 줄 서서 보는 점에서 ,, 4점 입니닷 ,,
스폰지밥의 우당탕탕 시간여행展 gre**** 5 사진이 이쁘게 잘 나오고 전시관도 생각보다 여러군데라 사진 찍는 거 좋아하는 분들에게 추천해요. 평일에도 사람은 꽤 있는편이에요.
스폰지밥의 우당탕탕 시간여행展 마시써잉 5 얼리버드로 예약해서 10500원에 갔아요
다들 줄서서 사진만찍고 끝나고 돈 아깝다셧는데
스폰지밥 덕후인 저는 만족스러웟어요
예상보다도 더 잘꾸며져있었구요
만 오천원이여도 저는 갔을듯요 ~~ 금요일 오후 5시반쯤 방문했는데 생각보다 수월하게 봤어요 대기도 짤막짤막하고~~
근데 카페는 너무 느끼하더라구요….. ㅜ
스폰지밥의 우당탕탕 시간여행展 wjs**** 4.5 짧긴 하지만 스폰지밥 찐팬들이라면 신나게 놀고도 남아요ㅋㅋㅋ 찐팬들은 추천합니당
스폰지밥의 우당탕탕 시간여행展 jjy1000j 5 진짜진짜 옛날 생각 많이 났던 스펀지밥 전시봐서 너무 좋았고 사진찍기도 너무 좋았어요!!!
스폰지밥의 우당탕탕 시간여행展 하루비51 4.5 아이와 단둘이 데이트하기 좋으네요~~ 사진맛집 인정 👍
스폰지밥의 우당탕탕 시간여행展 작은선지 2.5 생각보다 별로 였어요
스폰지밥의 우당탕탕 시간여행展 Kelly37 1.5 My boyfriend and I went to the exhibit in 2021, so we decided to come again. We were disappointed. Compared to 2021, there was almost nothing to do. You couldn’t touch anything, couldnt sit on anything, nothing to interact with. Only looking was boring, and there wasnt any real recognizable Spongebob areas either. The price is too expensive as well, it should be free since you couldnt do anything.
스폰지밥의 우당탕탕 시간여행展 mun**** 3.5 일요일 11시쯤 갔는데 줄이 심하게 길지는 안았어요~ 아이가 좋아할줄 알았는데 그냥 그렇더라구요ㅋ 체험거리도 없고 너무 짧았습니다
스폰지밥의 우당탕탕 시간여행展 아샤79 4 스폰지밥은 좋음. 다만… 볼만한 내용에 비해 가격이 좀 과한듯
스폰지밥의 우당탕탕 시간여행展 자콩51 0.5 여러분 절대절대 가지마세용..완전 별로입니다~~ 돈아까워요 그돈으로 건물에서 맛있는거사먹고 카페가셔요,,^_^ 진짜 사진 찍는줄 기다리구 찍고 빠지고 찍고 빠지고~~ 끝,, 진짜 돈아까워서 나오자마자 이게 다냐며ㅎㅎㅎㅎㅎㅎ
스폰지밥의 우당탕탕 시간여행展 0102da 1.5 줄서서봐야함, 비용대비볼것도없음, 불친절
스폰지밥의 우당탕탕 시간여행展 짱구야별이될래 2.5 사람많다는말에 일욜 10시반에갔어요
그냥 줄서서 순서대로 사진찍는분위기
체험없고 사진만 찍고오는거네요
직원분들 사진 참 열심히 찍어주세요
스폰지밥의 우당탕탕 시간여행展 ddo**** 4 진짜 재밌었어요! 다만 사전구매 하고 가도 대기를 해야되서 좀 아쉬웠습니다ㅠㅠ
스폰지밥의 우당탕탕 시간여행展 ss5719 2 별로에요 사람 너무 많아서 입구 쪽에서만 20분은 서있었음. 오로지 인스타 사진 업로드용 포토스팟 전시회. 콜라보 카페만 가는게 좋은 것 같아요.
스폰지밥의 우당탕탕 시간여행展 ytzz 0.5 아이들보여줄라고 전시회관람을간건데..
자유롭게 돌아다니면서 관람은 커녕..
그냥입장부터 끝날때까지 줄따라가면서 사진찍기..
실망..아이들도 스펀지밥 본다고 기대하고갔는데 실망..
스폰지밥의 우당탕탕 시간여행展 고양이가 좋은 고등어 5 9월 2일 방문
11시 50분쯤 방문했는데 사람이 진짜 많아서 오픈런을 하거나 늦은 시간에 오시는 걸 추천드려요!
그래도 포토존이 엄청 많고 퀄리티가 좋아서 티켓값이 아깝지는 않았어요!
직원분들이 사진 엄청 잘 찍어주십니다..👍
찍어주실 분이 없으시다면 고민없이 부탁해보세요~♡
그리고 직원분들이 포토존 사진 찍는 줄이 기니까 안찍으실 분들은 넘어가라고 안내해주셔서 다음 일정에 피해 안 갈 수 있었던 거 같아요!
스폰지밥의 우당탕탕 시간여행展 SY5064 4 재밌게 보냈습니다~
스폰지밥의 우당탕탕 시간여행展 타요타요49 5 아이가 너무 좋아했어요~
관람료가 비싼편이지만 아이가 좋아하니 만족해요
평일 오후에 방문했는데 사람이 많지는 않았는데
사진을 오래 찍는분들이 많아서..
저도 아이 사진 찍느라 계속 기다렸네요 ㅎㅎ
스폰지밥의 우당탕탕 시간여행展 베이유50 4 짱귀 넘귀 흑흑 사랑해 스폰지밥 ㅜㅜ
사진 많이 찍는 사람있으면 제대로 보기에 불편하지만 애들이 귀여우니까요 꼭 가세용
스폰지밥의 우당탕탕 시간여행展 Loae 2 몇년전에 열렸던 스폰지밥 전시회 퀄리티 생각하고 가서 그런가 다 아쉬웠어요. 뭔가 게임 같은 체험도 없고, 그렇다고 캐릭터들과 막 사진을 찍기에 좋은 것도 아니고, 그러다보니 당연히 전시도 엄청 짧게 느껴지고요. 굿즈들도 뭔가 다 아쉬운 것들 밖에 없고 잘 모르겠어요.
스폰지밥의 우당탕탕 시간여행展 osj**** 4 친구들과 즐거운 시간 보냈어요
스폰지밥의 우당탕탕 시간여행展 주노햄 4 스폰지밥 좋아하시면 흥미로운 전시회 입니다 ㅎㅎ 포토존도 많고 해서 재밌게 보다가 나왔습니다!
스폰지밥의 우당탕탕 시간여행展 jon**** 4 스폰지밥 팬이라서 오랜만에 가서 동심을 느끼고 온 기분이었습니다 :)
매번 생각하고 뜻을 되새기는 전시회를 가다가 오늘처럼 사진 찍고 즐기다 온 건 오랜만인 것 같아요!

그래도 아쉬운 건 너무 짧다는 게(30분만에 나옴) 아쉬웠고 사진도 막 그렇게 왕창 찍을만한 포인트가 많지 않아서 아쉽긴했습니다. 찐 스폰지밥 팬이라면 가시는 걸 추천드려요!

아 그리고 매표소 옆에서 포토카드(비키니시티운전면허증, 집게리아 직원증)를 3,000원에 뽑을 수 있어서 전시회 구경 하시고 기념품으로 가져가셔도 좋을 것 같습니다 :)
스폰지밥의 우당탕탕 시간여행展 Luu62 4 재밌어요. 굿즈 종류 더 다양하면 좋겠어요.
스폰지밥의 우당탕탕 시간여행展 농담곰85 5 재밌게 잘 보고 왔습니다~ 데이트하기에도 좋아요!
스폰지밥의 우당탕탕 시간여행展 jean19 4 스폰지밥이 귀엽습니다. 사진찍기 좋은 전시회입니다. 체험할 수 있는 코너가 있으면 좋을 것 같습니다.
스폰지밥의 우당탕탕 시간여행展 가가84 5 즐거운 시간 잘 보냈습니다.
스폰지밥의 우당탕탕 시간여행展 그냥만든닉네임 0.5 걍 인스타 사진찍기용
스폰지밥의 우당탕탕 시간여행展 뽐뽐7 5 친구들이랑 갔는데 너무 재밌게 구경했어요ㅎㅎ
스폰지밥의 우당탕탕 시간여행展 MING PD 2 사람이 너무 많아서 생각보다 사진 찍기 어려웠어요ㅜ 한 발자국 이동하고 사진찍고 이런 느낌이라 구경이란 느낌이 안 들었습니다ㅜ 가더라도 좀 사람 없을 때 (끝물) 가는 걸 추천드려요!
스폰지밥의 우당탕탕 시간여행展 Oㅇ0 4 포토카드 뽑는 줄이 기니 여기 먼저 줄 서시는거 추천해요 입장줄은 금방 빠지더라고요(일요일 낮 기준 20분 정도) 전시 퀄리티는 작년에 비해 낮아진듯합니다
스폰지밥의 우당탕탕 시간여행展 ine**** 3 사람이 너무너무너무너무너무 많아요 예약대기가 있으니 어느정도 사람인원을 맞춰서 들여보내는구나 생각했는데 그게 아니라 그냥 줄줄이 들여보내네요 줄서서 사진찍고 또 줄서고 그냥 줄서서 기다렸다가 사진찍고 지나옴 평일에 갔어야했네요.. 어느정도는 인원수 정해서 들여보내면 좋겠어요 하지만 전시회퀄리티는 높았어요 잘만듦!! 짧아서 아쉽지만 스폰지밥세계온것같고 좋았어요
스폰지밥의 우당탕탕 시간여행展 OㅡO70 4 아기자기하구 컬러풀해서 사진 남기기 좋았습니다. 다만 주말에 사람들이 많은데 전시가 순서대로 스토리가 있어서 동선상 스팟마다 사진 찍고 하려면 다들 줄 서서 따라올 수 밖에 없기 때문에 뒷사람들이 바로 뒤에서 지켜보고 있어서 여유있게 찍을 수가 없고 포즈 취하기 좀 민망하다는 점... 사진 빨리 찍고 다음 스팟으로 가기 바빠서 아쉬웠어요..
스폰지밥의 우당탕탕 시간여행展 쭈그리75 5 어렸을 때 봤던 회차들 새록새록 기억납니다ㅋㅋㅋㅎㅎㅎㅋㅎㅋ
보는 내내 너무 신났어요
스폰지밥의 우당탕탕 시간여행展 나요링 5 너무 즐겁게 잘 즐기고왔습니다! 볼거리도 다양하고 짧은감이 있긴하지만 해피~한 시간💗👍🏻
스폰지밥의 우당탕탕 시간여행展 chaenee92 4 스펀지밥 즐겨보셨으먄 데이트 장소로 👍🏻
아주 기여운 사진을 건졋다!!
그러나 주말엔 사람이 너어어어문 많은 관계로 비추! 사람이 많아서 사진찍기 다소 민망할 수도 잇슴!
글고 다들 도장도 찍던데 나는 찾지 못햇다ㅏㅏㅏ…
포토부스는 너어어어무 줄이 길어서 그냥 포기
그러나!! 돈이 아깝지 않을 정도로 ㄱ ㅣ여움!!🌝
스폰지밥의 우당탕탕 시간여행展 smiliee 1.5
스폰지밥의 우당탕탕 시간여행展 몽챰 3.5 포토스팟이 가득합니다 참여형 컨텐츠는 없습니다
스폰지밥의 우당탕탕 시간여행展 cksal723 3
스폰지밥의 우당탕탕 시간여행展 shg**** 5 재밌었어요 !사람이 너무 많아서 일찍 가시는걸 추천 드려요~
스폰지밥의 우당탕탕 시간여행展 죠죠죠31 4.5 너무 귀여워요 근데 줄서서 사진 찍구 약간 정신 없이 찍게 되는 거 같아요 예상은 해서 괜찮았어요
가볍게 보기 좋은 거 같아요
스폰지밥의 우당탕탕 시간여행展 소수지사랑님 3 좋아하는 만화 캐릭터라 갔는데. 생각보다 짧아서… 돈이 쫌… 아꿉 ㅜㅜ
미리 표를 구매해도 대기 시간도 많이 걸리고
예매할때 시간울 나눠서 했으면 아까운 시간을 허비 하지 않았울 꺼 같은 아쉬움이 크네요
스폰지밥의 우당탕탕 시간여행展 예율콩 5 남자친구랑 갔는대 너무 재밌고 평소애 스폰지밥을 조아햐소 더 조았어요
스폰지밥의 우당탕탕 시간여행展 eje**** 1 전시는 만족했으나 다 그런건 아니였는데 불친절한 직원이 있어서 내내 기분이 안좋았습니다 아이한테 만지지 말라고 계속 말하고 있었고 주의를 주면서 사진을 찍고 있었는데 실수로 만진 아이한테 소리를 지르며 만지면 안된다고 큰소리가 났고 그이후아이는 깜짝놀래서 울라고도 하고 위축이되서 사진을 찍을라고 하지 않았습니다 주의를 주는건 괜찮은데 너무 윽박지르는 식의 주의는 기분이 안좋네요 그점만 나아지면 괜찮을꺼같아요
스폰지밥의 우당탕탕 시간여행展 gin**** 5 너무 귀엽고~ 볼거리가 많아요!!
사진도 찍을곳도 많아요^^
스폰지밥의 우당탕탕 시간여행展 mp**** 3 전시관람 내용에 비해서 넘 비싸다. 옆에 팝퍼블 음식 전부 넘 비싸고 맛은 최악. 특히 롤케이크 불량식품 맛. 내인생 최악의 음식이였음. 음료도… 다른 테이블 사람들도 먹다 남김.
스폰지밥의 우당탕탕 시간여행展 흥해라흥칫뿡 4 생각보다 규모가 작아서 아쉬웠습니다. 주제가 시간여행이라고 어떤 스토리를 기대하시면 안되고 그냥 컨셉입니다. 전시 다 보시고 스티커 꼭 얻고 가세요.
스폰지밥의 우당탕탕 시간여행展 앉은해 3 30분이면 보는 분량, 규모에 아쉬운 점이 있었으나 그것을 감안할 정도로 유명한 에피소드의 디테일을 다 살린 높은 완성도의 전시물들이 좋았습니다. 다만 가족이나 친구단위보다는 커플 2인이 많으며 눈살이 찌푸려지는 정도로 높은 수위의 과도한 스킨쉽을 하는 커플 손님이 많음에도 불구하고 제지하는 스태프가 없던 것이 아쉽습니다.
스폰지밥의 우당탕탕 시간여행展 택조39 5
스폰지밥의 우당탕탕 시간여행展 쑤티치 3.5 귀여운 전시였어요~ 평일 오전에 가니 여유롭고 좋네요. 대기도 없었고! 좀 더 다양한 체험존이 있었음 더 좋았을 듯 해요.
스폰지밥의 우당탕탕 시간여행展 창희언니하투 5 다들 가시져! 근데 이것만 보러 가기엔 짧아요 ㅎ
영화도 보러 가시면서 이것두 보러 가세용
스폰지밥의 우당탕탕 시간여행展 iro**** 5 제 인생 최고였어요 진짜 스폰지밥 빠돌이 20년짼데 너무 행복한 시간이었어요 정말.... 황홀했습니다
스폰지밥의 우당탕탕 시간여행展 토토8485 5 완전 재밌고 구성도 알차고 오랜만에 스폰지밥이랑 뚱이랑 추억 여행온 기분이었습니다!
스폰지밥의 우당탕탕 시간여행展 규인네 5 부산레서 서울까지 놀러간 이유가 여기 때문인데
종류가 그렇게 많지는 않아서 좀 아쉬웠긴 했지만 그래도 친구랑 재밌는 시간 보낸거 같아서 좋아요. 많이들 구경하고 사진찍고 가세여~~
스폰지밥의 우당탕탕 시간여행展 화이트티거 5
스폰지밥의 우당탕탕 시간여행展 김은빈3257 5 귀여움
스폰지밥의 우당탕탕 시간여행展 무녱 5 너무 귀엽고 재밌었어용 😀😀
스폰지밥의 우당탕탕 시간여행展 유메1026 3 그리 넓진않아요 스폰지밥 좋아하고 사진찍기 좋아하는 사람들이면 갈만한 곳이네요
스폰지밥의 우당탕탕 시간여행展 꽃님이32 2.5 생각보다 넓지는 않아서 아쉬웠어요ㅠ
스폰지밥의 우당탕탕 시간여행展 꼬마전구00 4 평일인데도 사람 많았어요 스폰지밥 파인애플 집이 있었으면 좋았을텐데 없어서 좀 아쉬웠어요... 제가 방문했던 날 에어컨이 안 나와서 너무 덥고 힘들었어요 원래 그런건지 그 날만 그랬던건진 모르겠지만 손풍기 챙겨가세요!!
스폰지밥의 우당탕탕 시간여행展 jinjingji 4 월요일인데도 생각보다 사람이 많았어요
하지만 어른손님이 많아서 질서는 아주 굿 이요
포토존이 진짜 많았어요
앞에 어떤 두 분이 아주 열심히 찍는 바람에 정체가 생기고 대기줄이 길어 졌어요
그래서 그 제일 이쁜 포토존 스폰지밥 엄청 많은 곳 ㅜㅜ 직원분이 정체 땜에 찍어주시겠다고 ㅠㅠ 굳이 ~ 다들 흐뭇이 기다리는데 ~ 앞에 그 두분은 맘껏 찍고 그 뒤 손님들은 직원이 찍어주고 싶은 수량만큼만 ~ 이거 뭐지 ? 다들 어색 ~ 그 후에고 그 두분은 남의 시선 아랑곳하지 않고 모든곳에서 열촬 ~ 부러웠다 … 다들 질서를 너무 잘 지켜서 묵언의 배려가 되버림 ~ 누두도 앞찔러 가지 않고 앞 사람이 다찍길 기다린다 ~ 시선이 부담되 아들은 얼음 ~ ㅎㅎㅎ 인기 좀 식으면 한번 더 가자 ~
스폰지밥의 우당탕탕 시간여행展 예니워니89 2 생각보다 너무 별로였어요..ㅠㅠ
천천히 구경하면서 찍었던거같은데 20분?도안걸린듯.. 사전예매로 샀으니망정이지..제값주고가기엔 너무 너무 너무 아까울꼬같아여ㅠㅠㅠ.. 이벤트 도장찍으라고 주길래 안에 테마별로 게임이나 참여하는 뭔가있나 기대하고 들어갔더니..걍 마지막에 책상위 도장3개가 덩그러니있더라구요 ^^; 이벤트도없고;; 정말 실망ㅠㅠ
스폰지밥의 우당탕탕 시간여행展 임양75 4 아산에서 출발하니 2시간이 걸리더라고요~~스폰지밥은 40대인 제가 어린시절부터 보던 만화이기에 아이들과 함께했습니다~~아이들도 좋아라하고 저도 재미있었어요~~생각보다 넓지 않아 간 시간보단 짧게 보고왔지만 만족합니다^^
스폰지밥의 우당탕탕 시간여행展 포송쓰 5 주말동안 다녀왔는데 어른들이 젤 많았어요(저포함)
다들 동심으로 돌아간듯 땨햐햐햐 따라 웃기도하고
색감도 넘 예뻐서 놀랐어서 뭔가 시간여행이라 그런지는 몰라도 길따라가니 한눈에 볼 수 있더라구요
다시 또 가고싶어요
스폰지밥의 우당탕탕 시간여행展 vjvlfpem101 5
스폰지밥의 우당탕탕 시간여행展 pink3566 2.5 사진찍으러 간다면 강추..
스폰지밥의 우당탕탕 시간여행展 eu**** 5 주말이라 대기시간도 길었지만 들어갔을때 대만족~직원분들이 사진도 잘찍어주시고 친절하시고
보는것 사진찍기에 너무 좋은 시간이였음~
데이트하기 최고~!!!아이와도 같이 하기최고였음 👍
스폰지밥의 우당탕탕 시간여행展 비니75 5 정말 기엽고 기엽고,,,그렇습니다
스폰지밥 좋아하면 가세용~~
굿즈는 별로 없긴합니다ㅠ
스폰지밥의 우당탕탕 시간여행展 스누피892 0.5 주말에 갔는데 사람이 너무 많아서 입장하는데만 1시간이 넘게 웨이팅 하고 가격대비 볼 것도 너무 없네요.
스폰지밥의 우당탕탕 시간여행展 육삼삼포병 3 일단 안에 들어가면 자유관람이 아니고 놀이기구 타려고 기다리는 줄처럼 줄줄이 따라가면서 사진찍는 수준…평생에 소원이라던 우리아이가 한숨 쉼
스폰지밥의 우당탕탕 시간여행展 신기호호할머니 5 전시가 너무 귀엽고 재밌었는데 생각보다 전시가 짧은 느낌이라서 아쉬웠어요! 그래도 사진이랑 많이 찍을 수 있어 좋았습니다ㅎㅎ
스폰지밥의 우당탕탕 시간여행展 sunkite96 5 사람이 정말 많아서 주말 웨이팅은 1시간 반은 기본 예상하셔야 할 것 같아요..!
스펀지밥 카페는 대기 4시간 떠서 결국 못갔습니다...!
입장하면 질서있게 사진은 찍는데, 패키지 모임처럼 앞사람 사진 찍는거 구경하고
저 찍는거 구경 당해야해요....ㅎㅎ
그래도 너무 귀엽고 재밌었어요
스폰지밥의 우당탕탕 시간여행展 sun**** 3.5 아이들이 너무 가보고싶다고해서 다녀왔어요~
전시라보다는 포토스팟이라고 생각하는게 더 맞을것같아요~
줄서서 차례대로 사진찍고 끝.. 좀.. 아쉬웠어요^^;;
스폰지밥의 우당탕탕 시간여행展 챈니95 3 사람 너무 많아요~ 토요일 방문해서 8시마감이랬는데 5시에 이미 웨이팅 마감됨!! 멀리서 찾아올 분들은 웨이팅 마감까지 고려해서 일찍 오시는걸 추천해요.
스폰지밥의 우당탕탕 시간여행展 BAD BATCH 5 너무재밌었어요 3년전에 갈려고했는데 지금가서 보니까 조형물이나 캐릭터가 보기좋더라고여
스폰지밥의 우당탕탕 시간여행展 성연이96 5
스폰지밥의 우당탕탕 시간여행展 yun**** 5
스폰지밥의 우당탕탕 시간여행展 다으니얌 4 웨이팅이 길어서 한시간을 기다렸지만 그 기다린만큼 즐겁고 재밌는 전시관람했고 스폰지밥 이랑 스펀지밥 친구들 너무 귀여웠습니다
스폰지밥의 우당탕탕 시간여행展 밍이레인 3 입장권가격도비싼가격도있었고,좀 짧았다라는생각이 들었습니다.
스폰지밥의 우당탕탕 시간여행展 Hyeyeong 5 생각보다 정말 잘 꾸며놔서 구경하는 재미가 있었어요! 평일에 가니 포토카드 제외 웨이팅은 심하지 않았습니다. 스폰지밥 친구들과 사진을 찍으려면 몇 분 정도는 기다려야 하지만, 다른 인기 있는 전시에 비하면 웨이팅이 그리 길지 않은 편이에요~! 스폰지밥 친구들과 기분 전환하기에 좋은 전시입니다 ㅎㅎ
스폰지밥의 우당탕탕 시간여행展 ㅇㅅㅂ3510 3 귀여워요
저런 고퀄 모형들이 많이 있어요
애들 용 느낌이 많이 나긴 해요 ㅋㅋㅋ 성인 둘이 가기엔 쪼금 돈아까운 느낌..
스폰지밥의 우당탕탕 시간여행展 감자나라감자 4 분명 여기저기 사진찍을데가 많은데 한줄로 쭈루룩서서 한 부스당 한군데에서만 찍고 가요… 왜그럴까요
줄이 좀 있긴 한데 첫날보다는 아닌것같아요 줄도 점점 줄어들것같아요
스폰지밥의 우당탕탕 시간여행展 다연루 5 입장 전 포토카드 줄이 짧다면 포카먼저 발급받고 입장하는걸 추천합니다!
전시가 너무 잘꾸며져있어요. 만족스럽습니다
스폰지밥의 우당탕탕 시간여행展 졔919 2.5 귀여워요 귀엽긴 한데 사람이 진짜 그냥 짱 많고
사진 찍기 민망할정도로 다들 줄서서 구경함...
15,000원 내고 가기엔 뭔가 전체적으로 아쉬웠어요
스폰지밥의 우당탕탕 시간여행展 SB2318 3 대학생 둘이 갔는데 생각보다 별거 없었어요..들어가서도 동선마다 사진 찍는 대기줄이 계속 있었고, 가격대비 아쉽다는 생각들었습니다
스폰지밥의 우당탕탕 시간여행展 빠나나999 5 귀여워요ㅎㅎ평일에 가야 사람이 없어요!
스폰지밥의 우당탕탕 시간여행展 jang1210 3 사람 많아서 처음부터 끝까지 줄서서 사진찍어야함
목요일 3시에 갔은데 ㅠㅠ
스폰지밥의 우당탕탕 시간여행展 꿈피는 꽃 0.5 돈아까움
스폰지밥의 우당탕탕 시간여행展 뿡뿡61 4 사람이 너무많아서 사진을 부랴부랴 찍음..
2시쯤 되니깐 사람많아져서 웨이팅까지 걸엇네요…
하필 제 앞에서 끊겨서 웨이팅 1번…
스폰지밥의 우당탕탕 시간여행展 은빈9271 5 진짜 너무 귀엽고 재미있어요 또 한번 더 가도 좋을거 같아요!!!!
스폰지밥의 우당탕탕 시간여행展 이수빈5275 5 너무너무 귀엽고 재밌었어요
스폰지밥의 우당탕탕 시간여행展 lh**** 4 괞찮긴 했는데 사람 이 많았구 사진 찍어 주신 직원분
너무 대충 찍으신 거 같아요..
스폰지밥의 우당탕탕 시간여행展 바로나82 5 여자친구가 너무 좋아해서 갔어요 ㅎㅎ 생각보다 아기자기 사진찍기 좋아요 후딱 지나가서 더좋아요 ㅋㅋㅋ
스폰지밥의 우당탕탕 시간여행展 이사랑60 5 사진 찍을 만한 곳이 많아서 좋았어요!
스폰지밥의 우당탕탕 시간여행展 김연희71 5 재밌었어요~ 귀여운 작품이 너무 많아서 사진많이 찍었어요~
스폰지밥의 우당탕탕 시간여행展 핑크초코51 5 초딩딸이 너무 좋아했어요
포토존이 많아요
스폰지밥의 우당탕탕 시간여행展 OG9다롱 2 스펀지밥 정말 좋아하는 사람으로서 기대하면서 갔는데
너무 귀엽긴하지만 너무 짧았습니다...사람이 많아서 오래걸렸지 없었으면 솔직히 10분이면 봤을 것 같은느낌..너무 아쉬워요...
스폰지밥의 우당탕탕 시간여행展 여율리 4 여유있게 구경하면서 돌아보진 못 했어요.
사람도 무척이나 많고 다들 사진 찍으려 줄 서 있고..

굿즈샵에서도 아크릴 상품 상자 벌려서 좋아하는 캐릭터만 가져가는 거 보고 관리가 안되는 구나 싶었습니다.
스폰지밥의 우당탕탕 시간여행展 소르님 5 즐겁고 좋아요
스폰지밥의 우당탕탕 시간여행展 하봉99 3.5 사람이 많아 좀 힘들었지만 아이가좋아해서 다행이였습니다 다음에 한가할때 한번더 방문하려고요~~
스폰지밥의 우당탕탕 시간여행展 차은우99 5 와우 너무 좋았어요 생각보다 여러가지가 있었어요
스폰지밥의 우당탕탕 시간여행展 재이잉 0.5 공짜 전시회도 아니고, 관람 안내를 한다는 느낌보다는 빨리 보고 나가라 는 식으로 정말 불쾌함
스폰지밥의 우당탕탕 시간여행展 디디324 2.5 스토리텔링이 전 혀 없음... 걍 피규어 여러개 세워놓은 포토존임
스폰지밥의 우당탕탕 시간여행展 달님9127 5 저의 최애 스펀지밥을 보다니이이!! 저의 동심을 지켜주셔서 감사해요...
스폰지밥의 우당탕탕 시간여행展 우어으어 5 정말 좋았습니다 각 방별로 에피소드의 내용이 잘 구현되어있었고 너무나 어릴적 스펀지밥 한 에피소드에 들어온 것이 행복했습니다 짱이었어요!
스폰지밥의 우당탕탕 시간여행展 qfg**** 3 오로지 사진찍기 위해서라면 좋아요 처음부터 끝까지 내내 줄서서 사진찍어서 관람은 힘들어요
스폰지밥의 우당탕탕 시간여행展 soe**** 0.5 사람만 많고 사진 찍을 때마다 사람들 눈치보여서 제대로 사진도 못 찍고 오네요……1시간도 안 돼서 나올 정도 이구요… 별로 볼건 없구 들어가서 나올때 징징이 표정마냥 하고 나오게 될겁니다….ㅎ 가보면 무슨 뜻인지 알게될걸요…?^^
스폰지밥의 우당탕탕 시간여행展 lullaby19 1 아이들이 가고싶대서 갔는데 진짜볼거리없더라구요 딱 초딩 아이들 키즈카페느낌이던데 성인들끼리와서도 사진많이들 찍으시더라구요 1인 8천원수준의 제주도 관광지 느낌입니다
스폰지밥의 우당탕탕 시간여행展 gy**** 2
스폰지밥의 우당탕탕 시간여행展 lislil 5 사진 많이 찍으세요 ㅎㅎ
스폰지밥의 우당탕탕 시간여행展 순덕40 5
스폰지밥의 우당탕탕 시간여행展 해피송송77 4.5 사진찍기좋아요.초5와갔는데 좋았어요.
스폰지밥의 우당탕탕 시간여행展 nsn04171 3.5 재밌었어요 잘보고왔습니다~!
스폰지밥의 우당탕탕 시간여행展 SummersLikes 4 너무너무 귀여운 스폰지밥!
세트가 꽤 많고 퀄리티가 좋아서 즐겁게 봤어요😗
웨이팅이 좀 오래 걸렸지만 태블릿에 등록하고 다른 곳에서 구경하다 오면 됩니다!

후기👉🏻https://m.blog.naver.com/summerslikes/223184562960
스폰지밥의 우당탕탕 시간여행展 산다라봄 0.5 진짜 돈낭비 사람 엄청많아서 사진도 못찍음 절대 안가길 추천
스폰지밥의 우당탕탕 시간여행展 belllllllllla 3 70분 기다려 들어갔고 사진 찍으려면 계속 줄서서 기다려야함
스폰지밥의 우당탕탕 시간여행展 맨땅 5 스폰지밥 너무 좋았어요!!! 제 최애 애니인데
전시로 보니까 넘조아요 그리고 굿즈 진짜 귀여워요 꼭 사세욥!!!! 아 그리고 스폰지밥 카페는 빨리 마감됩니당 !
스폰지밥의 우당탕탕 시간여행展 hihi9637 5 아이들만 가는곳인줄알았는데 어른만있어서 놀랬어요ㅎㅎ 사진찍고 즐기기 좋았습니다
스폰지밥의 우당탕탕 시간여행展 이민정532 5 행복했어요!!! 너무!!!

https://m.blog.naver.com/lisd0220/223185636167
스폰지밥의 우당탕탕 시간여행展 hw**** 5 와....너무 재밌다...
스폰지밥의 우당탕탕 시간여행展 토마토9733 0.5 아.진짜. 최...악이네요. 볼것없고 가격대비 너무 허접했어요.
스폰지밥의 우당탕탕 시간여행展 pob**** 1.5 사람이 많아요 좀 나중에 갈껄 후회합니다
스폰지밥의 우당탕탕 시간여행展 dream9 5
스폰지밥의 우당탕탕 시간여행展 안녕시드니 5 퀄리티가 상당히 좋았어요 ㅎㅎ 이야기 흐름대로 따라가면 스펀지밥의 시간여향을 함께하는 것 같았답니다 ㅎㅎ
스폰지밥의 우당탕탕 시간여행展 mine564 3 이 나이에 스폰지밥보러 줄을서다니ㅎㅎㅎ
옛날에 티비에서보던 캐릭터봐서 재미있었어요
줄이너무길었고 예약을했어도 인원이 차면 들어갈수가없다고해서 완전당황 ,당혹스러웠지만 다행히 들여보내주셔서 줄서서 열심히 사진찍고왔어요
도장찍으면 선물준다했는데 선물로 스티커한장받았어요ㅎㅎ
체험부스?가있었는데 끝나가는시간이라 체험은못했어요 기념품도 못샀어요...
사진많이찍고싶고 스폰지밥캐릭터좋아하면 또가도좋을것같아요
스폰지밥의 우당탕탕 시간여행展 수님8 5 스펀지밥
카페랑 전시 모두 관람 했는데
넘 귀여운 전시였음
사진찍기 좋아요
스폰지밥의 우당탕탕 시간여행展 tls**** 1.5 이런 것도 전시회라고 만든 건가ㅠ 자유롭게 돌아다니긴 커녕 줄 지어서 다니느라 사진 찍으려면 앞 사람 뒷 사람 온갖 눈치 다 보이고.. 내가 원하는 사진은 단 한 장도 못 건짐ㅜㅜ 공간적 제약 때문에 이렇게밖에 진행 못 하는 거 같은데 그래도 돈 낸 소비자 입장에서는 매우매우 아쉬움만 남을 뿐인 전시회네요.. 전시회 내내 징징이 표정으로 돌아다님 ㄹㅇ 사람은 또 오질라게 많아서 겁나 피곤…^^ 글두 스폰지밥은 죄 업서요 귀여웠슴… 무튼 가는 건 자유지만 그닥 추천은 안 합니다~
스폰지밥의 우당탕탕 시간여행展 son**** 4 옛날에 많이 봤던 스폰지밥을 실물로 보다니🥹
일단 세트장마다 공들인게 보여서 재밌게 관람했습니다. 스폰지밥 좋아하시는 분들은 가보는 걸 추천!!
스폰지밥의 우당탕탕 시간여행展 cksduddlcjsw 5

In [ ]:
# print(rows[:2])
text = []
for i, row in enumerate(rows):
    # if i >2 : break
    #print(row.text)
    text.append(row.text)
#text/html/body/table/tbody/tr[2]/td[3]/div/div/div[2]/div/table/tbody/tr[1]/td[2]/span
#body > table > tbody > tr:nth-child(2) > td:nth-child(3) > div > div > div.con > div > table > tbody
#body > table > tbody > tr:nth-child(2) > td:nth-child(3) > div > div > div.con > div > table > tbody > tr:nth-child(1) > td.RKtxt > span
#body > table > tbody > tr:nth-child(2) > td:nth-child(3) > div > div > div.con > div > table > tbody > tr:nth-child(153)