# 장르+줄거리

### 전처리

In [1]:
!pip install konlpy

Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 54.9 MB/s eta 0:00:00
Collecting JPype1>=0.7.0 (from konlpy)
  Downloading JPype1-1.4.1-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (465 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 kB 47.4 MB/s eta 0:00:00
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from konlpy) (4.9.3)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.10/dist-packages (from konlpy) (1.23.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from JPype1>=0.7.0->konlpy) (23.2)
Installing collected packages: JPype1, konlpy
Successfully installed JPype1-1.4.1 konlpy-0.6.0

In [2]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2023.6.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.1)

In [3]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [4]:
!pip install sentence_transformers

Collecting sentence_transformers
  Downloading sentence-transformers-2.2.2.tar.gz (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 3.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: transformers<5.0.0,>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (4.35.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (4.66.1)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (2.1.0+cu118)
Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (0.16.0+cu118)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.23.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (1.11.3)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (3.8.1)
Collecting sentencepiece (from sentence_transformers)
  Downloading sentencepiece-0.1.99-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 28.6 MB/s eta 0:00:00
Requirement already satisfied: huggingface-hub>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from sentence_transformers) (0.19.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (2023.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (2.31.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (6.0.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (4.5.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.4.0->sentence_transformers) (23.2)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence_transformers) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence_transformers) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence_transformers) (3.1.2)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->sentence_transformers) (2.1.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (2023.6.3)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (0.15.0)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers<5.0.0,>=4.6.0->sentence_transformers) (0.4.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->sentence_transformers) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->sentence_transformers) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence_transformers) (3.2.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision->sentence_transformers) (9.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.6.0->sentence_transformers) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.4.0->sentence_transformers) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.6.0->sentence_transformers) (1.3.0)
Building wheels for collected packages: sentence_transformers
  Building wheel for sentence_transformers (setup.py) ... done
  Created wheel for sentence_transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=edcbe94018652af754fb1bf9d74c4b80190b2d6760b9e061b4bc4f7cd29794c6
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence_transformers
Installing collected packages: sentencepiece, sentence_transformers
Successfully installed sentence_transformers-2.2.2 sentencepiece-0.1.99

In [5]:
import torch
import pandas as pd
import numpy as np

from bs4 import BeautifulSoup
from urllib.request import urlopen
import os
import re
from konlpy.tag import Okt, Kkma, Komoran
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

import networkx
from tqdm.autonotebook import tqdm

import seaborn as sns
import matplotlib.pyplot as plt

from gensim.models import word2vec
import itertools

In [7]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('jhgan/ko-sroberta-multitask')

.gitattributes:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/4.86k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/744 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

(…)imilarity_evaluation_sts-dev_results.csv:   0%|          | 0.00/931 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/443M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

(…)milarity_evaluation_sts-test_results.csv:   0%|          | 0.00/302 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/156 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/495k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/585 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/248k [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

In [8]:
df = pd.read_excel('../data/raw/theater_top77.xlsx')
df = df.drop(df.columns[0], axis=1)
# df = df.drop(df.columns[2], axis=1)
df.head(3)

,Title,Text_clear_num,연극 이름,공연소개,줄거리,장르
0,연극 〈운빨로맨스〉- 대학로,점에 살고 점에 죽는 점보늬의 호랑이띠 남자와 하룻밤 보내기 프로젝트목숨이 걸린 중...,!로맨틱코미디 연극〈운빨로맨스〉! - 대구,NaN,점에 살고 점에 죽는 점보늬의 호랑이띠 남자와 하룻밤 보내기 프로젝트 목숨이 걸린 ...,"로맨스, 코믹, 공감/힐링"
1,(리얼타임 코믹연극) 택시안에서 - 서울,웃음 감동 사랑이 시작되는 리얼타엄 코믹연극 공연시간 투 콩감백배 다양한에피소드와 ...,(리얼타임 코믹연극) 택시안에서 - 부산,NaN,쾌활하고 유쾌한 택시 운전사 민수 그리고 하영과 소희 두 남녀의 운명적인 만남!\n...,"코믹, 로맨스, 공감/힐링"
2,(코믹연극) 달동네-부산,전사 오픈런 부족 초대합니다 개스 테 그를 코 뻔 부 토사 사으소시 서사으 냈 이거...,(코믹연극) 달동네-부산,NaN,"정음의 아버지 경민은 행정착오로 인해 월남전 참전 중 전사자 처리가 되고,........","코믹, 감동, 드라마"

In [9]:
df1 = df[['Title', '줄거리', '장르']]
df1.head(3)

,Title,줄거리,장르
0,연극 〈운빨로맨스〉- 대학로,점에 살고 점에 죽는 점보늬의 호랑이띠 남자와 하룻밤 보내기 프로젝트 목숨이 걸린 ...,"로맨스, 코믹, 공감/힐링"
1,(리얼타임 코믹연극) 택시안에서 - 서울,쾌활하고 유쾌한 택시 운전사 민수 그리고 하영과 소희 두 남녀의 운명적인 만남!\n...,"코믹, 로맨스, 공감/힐링"
2,(코믹연극) 달동네-부산,"정음의 아버지 경민은 행정착오로 인해 월남전 참전 중 전사자 처리가 되고,........","코믹, 감동, 드라마"

In [10]:
df1['장르']=df1['장르'].str.split(',')
df1['장르'] = df1['장르'].apply(lambda x : (' ').join(x))
df1.head(3)

<ipython-input-10-64c876e4423b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['장르']=df1['장르'].str.split(',')
<ipython-input-10-64c876e4423b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['장르'] = df1['장르'].apply(lambda x : (' ').join(x))

,Title,줄거리,장르
0,연극 〈운빨로맨스〉- 대학로,점에 살고 점에 죽는 점보늬의 호랑이띠 남자와 하룻밤 보내기 프로젝트 목숨이 걸린 ...,로맨스 코믹 공감/힐링
1,(리얼타임 코믹연극) 택시안에서 - 서울,쾌활하고 유쾌한 택시 운전사 민수 그리고 하영과 소희 두 남녀의 운명적인 만남!\n...,코믹 로맨스 공감/힐링
2,(코믹연극) 달동네-부산,"정음의 아버지 경민은 행정착오로 인해 월남전 참전 중 전사자 처리가 되고,........",코믹 감동 드라마

In [11]:
df1['줄거리'] = df1['줄거리'].apply(lambda x: re.sub(r'[^가-힣a-zA-Z\s]', '', str(x)))
df1.head(3)

<ipython-input-11-7b1018866824>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['줄거리'] = df1['줄거리'].apply(lambda x: re.sub(r'[^가-힣a-zA-Z\s]', '', str(x)))

,Title,줄거리,장르
0,연극 〈운빨로맨스〉- 대학로,점에 살고 점에 죽는 점보늬의 호랑이띠 남자와 하룻밤 보내기 프로젝트 목숨이 걸린 ...,로맨스 코믹 공감/힐링
1,(리얼타임 코믹연극) 택시안에서 - 서울,쾌활하고 유쾌한 택시 운전사 민수 그리고 하영과 소희 두 남녀의 운명적인 만남\n남...,코믹 로맨스 공감/힐링
2,(코믹연극) 달동네-부산,정음의 아버지 경민은 행정착오로 인해 월남전 참전 중 전사자 처리가 되고\n잘못된 ...,코믹 감동 드라마

In [12]:
# 줄거리 전체 + 장르 합쳐서 새로운 열 생성
df_data = df1.drop(df1[(df1['장르']=='') | (df1['줄거리'] =='')].index)
df_data['genres_keywords'] = df1['장르'] + " " +(df1['줄거리'])

In [13]:
df = pd.read_excel("../data/raw/musical_top77.xlsx")
df = df.drop(df.columns[0], axis=1)
# df = df.drop(df.columns[2], axis=1)
df.head()

,Title,Text_clear_num,뮤지컬 이름,공연소개,줄거리,장르
0,"2023 〈스웨그에이지 : 외쳐, 조선〉 - 인천",인기 우리의 작은 외침이 세상을 바꾼파 우리의 작은 외침이 세상을 바꾼다 우리들의 ...,"2023 〈스웨그에이지 : 외쳐, 조선〉 - 인천",NaN,시조'가 국가이념인 상상 속의 '조선'\n삶의 고단함과 역경을 시조 속에 담아 훌훌...,"역사극, 판타지"
1,2023 창작뮤지컬어워드 NEXT,창작뮤지컬어워드 충무마트센터가 가능성 있는 참작뮤지컬 발굴을 플랫품인 창작뮤지컬머워...,2023 창작뮤지컬어워드 NEXT,None,헌책방을 운영하는 에이미는 여느 날과 다름없이 책들에게 인사를 건네며 하루를 시작한...,드라마
2,2023 최현우 Answer - 성남,적 서니 정남아트센터 오페라하우스 이하늘이엔티 빅탑엔터테인언트 지라온플레이 년간의 ...,2023 최현우 Answer - 성남,NaN,"마술사로 걸어온 27년\n2,700여회 공연, 200만 명 관객 돌파\n세계가 인정...","마술, 판타지"
3,2023~24 최현우 Answer,마포아트센터 아트홀 맥 외는 이라을레이 이라오 저아아개 년간의 마술 노하우를 집대성...,2023~24 최현우 Answer,NaN,"마술사로 걸어온 27년\n2,700여회 공연, 200만 명 관객 돌파\n세계가 인정...","마술, 판타지"
4,2023송승환의 오리지널 난타(대전),렵 노역 톨 한받때약교야트을좌적매치도 슈 태빼 도시 해외공연투어 장기공연의 힘 오직...,NaN,NaN,세 명의 요리사가 하루 일과를 시작한다. 즐겁게 요리를 준비하는 동안 지배인의 깜짝...,"코믹, 액션"

In [14]:
df1 = df[['Title', '줄거리', '장르']]
df1.head(3)

,Title,줄거리,장르
0,"2023 〈스웨그에이지 : 외쳐, 조선〉 - 인천",시조'가 국가이념인 상상 속의 '조선'\n삶의 고단함과 역경을 시조 속에 담아 훌훌...,"역사극, 판타지"
1,2023 창작뮤지컬어워드 NEXT,헌책방을 운영하는 에이미는 여느 날과 다름없이 책들에게 인사를 건네며 하루를 시작한...,드라마
2,2023 최현우 Answer - 성남,"마술사로 걸어온 27년\n2,700여회 공연, 200만 명 관객 돌파\n세계가 인정...","마술, 판타지"

In [15]:
df1['장르']=df1['장르'].str.split(',')
df1['장르'] = df1['장르'].apply(lambda x : (' ').join(x))

df1['줄거리'] = df1['줄거리'].apply(lambda x: re.sub(r'[^가-힣a-zA-Z\s]', '', str(x)))
df_data = df1.drop(df1[(df1['장르']=='') | (df1['줄거리'] =='')].index)
df_data['genres_keywords'] = df1['장르'] + " " +(df1['줄거리'])

<ipython-input-15-7bf060d3e4ab>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['장르']=df1['장르'].str.split(',')
<ipython-input-15-7bf060d3e4ab>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['장르'] = df1['장르'].apply(lambda x : (' ').join(x))
<ipython-input-15-7bf060d3e4ab>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['줄거리'] = df1['줄거리'].apply(lambda x: re.sub(r'[^가-힣a-zA-Z\s]', '', str(x)))

### 장르 + 줄거리 유사도

In [16]:
from sentence_transformers import SentenceTransformer, util

embedder = SentenceTransformer('jhgan/ko-sroberta-multitask')
embedder.max_seq_len = 128

titles = df_data['Title'].tolist()
stories = df_data['genres_keywords'].tolist()

# Fit model to corpus qnd push to GPU
story_embeddings = embedder.encode(stories, convert_to_tensor=True)

In [17]:
def semantic_search(input_data):
  title_list = []
  story_list = []
  score_list = []

  results = pd.DataFrame()
  # Find the closest 5 stories of the corpus for each query sentence based on cosine similarity
  top_k = min(6, len(story_embeddings))

  # If the input is too short to be a story or its not in the dataset
  if len(input_data) < 20 and input_data not in titles:
    print('Title Not Found')

  # If input is in the dataset
  elif input_data in titles:
    query_embeddings = embedder.encode(str(df_data[df_data['Title'] == input_data]['genres_keywords'])[5:-33], convert_to_tensor=True)

    # Use cosine-similarity and torch.topk to find the highest 5 scores
    cos_scores = util.pytorch_cos_sim(query_embeddings, story_embeddings)[0]
    top_results = torch.topk(cos_scores, k=65)

    input_data_2 = input_data.replace('.', '.\n')
    print("\n\n======================")
    print("    TOP RESULTS")
    print("======================\n")

    # For score, index in torch.topk(cos_scores, k=top_k) use index  locator for feature lists
    # push score to cpu and convert to 1D array
    for score, idx in zip(top_results[0], top_results[1]):
      title_list.append(titles[idx])
      story_list.append(stories[idx])
      score_list.append(score.cpu().numpy().flatten())

    results['Title'] = title_list
    results['Story'] = story_list
    results['Score'] = score_list
    # return dictionary
    return results.iloc[1:, :]

  # If the input is long enough to be a story which is in the dataset
  elif len(input_data) > 20 and input_data not in titles:
    # Find the closest 5 stories of the corpus for each query sentence based on cosine similarity
    query_embeddings = embedder.encode(input_data, convert_to_tensor=True)

    # Use cosine-similarity and torch.topk to find the highest 5 scores
    cos_scores = util.pytorch_cos_sim(query_embeddings, story_embeddings)[0]
    top_results = torch.topk(cos_scores, k=top_k)

    input_data = input_data.replace('.', '.\n')
    print(input_data)
    print("\n\n======================")
    print("    TOP RESULTS")
    print("======================\n")

    # For score, index in torch.topk(cos_scores, k=top_k) use index  locator for feature lists
    # push score to cpu and convert to 1D array
    for score, idx in zip(top_results[0], top_results[1]):
      title_list.append(titles[idx])
      story_list.append(stories[idx])
      score_list.append(score.cpu().numpy().flatten())

    # Push results to dictionary columns
    results['Title'] = title_list
    results['Story'] = story_list
    results['Score'] = score_list
    # return dictionary
    return results

In [18]:
### 뮤지컬 장르+줄거리 임베딩
from sentence_transformers import SentenceTransformer, util

embedder = SentenceTransformer('jhgan/ko-sroberta-multitask')
embedder.max_seq_len = 128

titles = df_data['Title'].tolist()
stories = df_data['genres_keywords'].tolist()

# Fit model to corpus qnd push to GPU
story_embeddings = embedder.encode(stories, convert_to_tensor=True)

In [19]:
def semantic_search_1(input_data):
  title_list = []
  story_list = []
  score_list = []

  results = pd.DataFrame()
  # Find the closest 5 stories of the corpus for each query sentence based on cosine similarity
  top_k = min(6, len(story_embeddings))

  # If the input is too short to be a story or its not in the dataset
  if len(input_data) < 20 and input_data not in titles:
    print('Title Not Found')

  # If input is in the dataset
  elif input_data in titles:
    query_embeddings = embedder.encode(str(df_data[df_data['Title'] == input_data]['genres_keywords'])[5:-33], convert_to_tensor=True)

    # Use cosine-similarity and torch.topk to find the highest 5 scores
    cos_scores = util.pytorch_cos_sim(query_embeddings, story_embeddings)[0]
    top_results = torch.topk(cos_scores, k=65)

    input_data_2 = input_data.replace('.', '.\n')
    print("\n\n======================")
    print("    TOP RESULTS")
    print("======================\n")

    # For score, index in torch.topk(cos_scores, k=top_k) use index  locator for feature lists
    # push score to cpu and convert to 1D array
    for score, idx in zip(top_results[0], top_results[1]):
      title_list.append(titles[idx])
      story_list.append(stories[idx])
      score_list.append(score.cpu().numpy().flatten())

    results['Title'] = title_list
    results['Story'] = story_list
    results['Score'] = score_list
    # return dictionary
    return results.iloc[1:, :]

  # If the input is long enough to be a story which is in the dataset
  elif len(input_data) > 20 and input_data not in titles:
    # Find the closest 5 stories of the corpus for each query sentence based on cosine similarity
    query_embeddings = embedder.encode(input_data, convert_to_tensor=True)

    # Use cosine-similarity and torch.topk to find the highest 5 scores
    cos_scores = util.pytorch_cos_sim(query_embeddings, story_embeddings)[0]
    top_results = torch.topk(cos_scores, k=top_k)

    input_data = input_data.replace('.', '.\n')
    print(input_data)
    print("\n\n======================")
    print("    TOP RESULTS")
    print("======================\n")

    # For score, index in torch.topk(cos_scores, k=top_k) use index  locator for feature lists
    # push score to cpu and convert to 1D array
    for score, idx in zip(top_results[0], top_results[1]):
      title_list.append(titles[idx])
      story_list.append(stories[idx])
      score_list.append(score.cpu().numpy().flatten())

    # Push results to dictionary columns
    results['Title'] = title_list
    results['Story'] = story_list
    results['Score'] = score_list
    # return dictionary
    return results

In [26]:
semantic_search("뮤지컬 〈문스토리〉")

======================
    TOP RESULTS
======================

,Title,Story,Score
1,뮤지컬 〈렛미플라이〉,역사극 드라마 아폴로 호가 달을 향해 쏘아 올려진 년의 밤\n동네 최고의 수선장이...,[0.52778757]
2,뮤지컬 〈판〉,코믹 블랙코미디 감동 세기 말 조선 서민들 사이에서 흉흉한 세상을 풍자하는 패관...,[0.4148951]
3,"2023 〈스웨그에이지 : 외쳐, 조선〉 - 인천",역사극 판타지 시조가 국가이념인 상상 속의 조선\n삶의 고단함과 역경을 시조 속에...,[0.4006812]
4,뮤지컬 〈빨래〉,드라마 감동 공감/힐링 서울살이 년 차인 나영과 솔롱고 작가의 꿈을 안고 서울에...,[0.39863056]
5,뮤지컬 〈투모로우 모닝〉,로맨스 공감/힐링 통통 튀는 매력 존 캣의 풋풋함과\n책 캐서린의 무르익은 감...,[0.39050323]
...,...,...,...
60,뮤지컬 〈구텐버그〉,역사극 중세 독일의 작은 마을 슐리머\n포도즙을 짜던 평범한 남자 구텐버그가\n인쇄...,[0.1908222]
61,런던레코드,드라마 감동 런던 외곽에 위치한 낡고 오래된 레코드 샵 주인 존은 오늘도 하루를 ...,[0.16762534]
62,뮤지컬 프리즌,관객 참여형 코믹 락 밴드 연습생들 감옥 가다 가수의 꿈을 안고 혹독한 준비를 해...,[0.15406935]
63,난타(NANTA) - 명동공연,코믹 액션 세 명의 요리사가 하루 일과를 시작한다 즐겁게 요리를 준비하는 동안 지...,[0.1449534]
64,2023송승환의 오리지널 난타(대전),코믹 액션 세 명의 요리사가 하루 일과를 시작한다 즐겁게 요리를 준비하는 동안 지...,[0.1449534]

In [21]:
semantic_search_1("뮤지컬 〈문스토리〉")

======================
    TOP RESULTS
======================

,Title,Story,Score
1,뮤지컬 〈렛미플라이〉,역사극 드라마 아폴로 호가 달을 향해 쏘아 올려진 년의 밤\n동네 최고의 수선장이...,[0.52778757]
2,뮤지컬 〈판〉,코믹 블랙코미디 감동 세기 말 조선 서민들 사이에서 흉흉한 세상을 풍자하는 패관...,[0.4148951]
3,"2023 〈스웨그에이지 : 외쳐, 조선〉 - 인천",역사극 판타지 시조가 국가이념인 상상 속의 조선\n삶의 고단함과 역경을 시조 속에...,[0.4006812]
4,뮤지컬 〈빨래〉,드라마 감동 공감/힐링 서울살이 년 차인 나영과 솔롱고 작가의 꿈을 안고 서울에...,[0.39863056]
5,뮤지컬 〈투모로우 모닝〉,로맨스 공감/힐링 통통 튀는 매력 존 캣의 풋풋함과\n책 캐서린의 무르익은 감...,[0.39050323]
...,...,...,...
60,뮤지컬 〈구텐버그〉,역사극 중세 독일의 작은 마을 슐리머\n포도즙을 짜던 평범한 남자 구텐버그가\n인쇄...,[0.1908222]
61,런던레코드,드라마 감동 런던 외곽에 위치한 낡고 오래된 레코드 샵 주인 존은 오늘도 하루를 ...,[0.16762534]
62,뮤지컬 프리즌,관객 참여형 코믹 락 밴드 연습생들 감옥 가다 가수의 꿈을 안고 혹독한 준비를 해...,[0.15406935]
63,난타(NANTA) - 명동공연,코믹 액션 세 명의 요리사가 하루 일과를 시작한다 즐겁게 요리를 준비하는 동안 지...,[0.1449534]
64,2023송승환의 오리지널 난타(대전),코믹 액션 세 명의 요리사가 하루 일과를 시작한다 즐겁게 요리를 준비하는 동안 지...,[0.1449534]

In [28]:
a = semantic_search_1("뮤지컬 〈문스토리〉")
a

======================
    TOP RESULTS
======================

,Title,Story,Score
1,뮤지컬 〈렛미플라이〉,역사극 드라마 아폴로 호가 달을 향해 쏘아 올려진 년의 밤\n동네 최고의 수선장이...,[0.52778757]
2,뮤지컬 〈판〉,코믹 블랙코미디 감동 세기 말 조선 서민들 사이에서 흉흉한 세상을 풍자하는 패관...,[0.4148951]
3,"2023 〈스웨그에이지 : 외쳐, 조선〉 - 인천",역사극 판타지 시조가 국가이념인 상상 속의 조선\n삶의 고단함과 역경을 시조 속에...,[0.4006812]
4,뮤지컬 〈빨래〉,드라마 감동 공감/힐링 서울살이 년 차인 나영과 솔롱고 작가의 꿈을 안고 서울에...,[0.39863056]
5,뮤지컬 〈투모로우 모닝〉,로맨스 공감/힐링 통통 튀는 매력 존 캣의 풋풋함과\n책 캐서린의 무르익은 감...,[0.39050323]
...,...,...,...
60,뮤지컬 〈구텐버그〉,역사극 중세 독일의 작은 마을 슐리머\n포도즙을 짜던 평범한 남자 구텐버그가\n인쇄...,[0.1908222]
61,런던레코드,드라마 감동 런던 외곽에 위치한 낡고 오래된 레코드 샵 주인 존은 오늘도 하루를 ...,[0.16762534]
62,뮤지컬 프리즌,관객 참여형 코믹 락 밴드 연습생들 감옥 가다 가수의 꿈을 안고 혹독한 준비를 해...,[0.15406935]
63,난타(NANTA) - 명동공연,코믹 액션 세 명의 요리사가 하루 일과를 시작한다 즐겁게 요리를 준비하는 동안 지...,[0.1449534]
64,2023송승환의 오리지널 난타(대전),코믹 액션 세 명의 요리사가 하루 일과를 시작한다 즐겁게 요리를 준비하는 동안 지...,[0.1449534]

In [29]:
print(type(a))

<class 'pandas.core.frame.DataFrame'>

In [31]:
selected_columns = a[['Title', 'Score']]
selected_columns['Score'] = selected_columns['Score'].apply(lambda x: x[0])
selected_columns

<ipython-input-31-534d2ed530bf>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_columns['Score'] = selected_columns['Score'].apply(lambda x: x[0])

                          Title     Score
1                   뮤지컬 〈렛미플라이〉  0.527788
2                       뮤지컬 〈판〉  0.414895
3   2023 〈스웨그에이지 : 외쳐, 조선〉 - 인천  0.400681
4                      뮤지컬 〈빨래〉  0.398631
5                 뮤지컬 〈투모로우 모닝〉  0.390503
..                          ...       ...
60                   뮤지컬 〈구텐버그〉  0.190822
61                        런던레코드  0.167625
62                      뮤지컬 프리즌  0.154069
63             난타(NANTA) - 명동공연  0.144953
64         2023송승환의 오리지널 난타(대전)  0.144953

[64 rows x 2 columns]

In [32]:
plot_genre_weight = selected_columns.set_index(keys=['Title'])
plot_genre_weight

                                Score
Title
뮤지컬 〈렛미플라이〉                  0.527788
뮤지컬 〈판〉                      0.414895
2023 〈스웨그에이지 : 외쳐, 조선〉 - 인천  0.400681
뮤지컬 〈빨래〉                     0.398631
뮤지컬 〈투모로우 모닝〉                0.390503
...                               ...
뮤지컬 〈구텐버그〉                   0.190822
런던레코드                        0.167625
뮤지컬 프리즌                      0.154069
난타(NANTA) - 명동공연             0.144953
2023송승환의 오리지널 난타(대전)         0.144953

[64 rows x 1 columns]

# 별점 가중치 함수


*   변수가 적절히 잘 쓰였는지 확인(코드 이해)
*   변경할 점 있으면 변수 바꾼다.

연극 별점가중치

In [33]:
# 연극_평점
import pandas as pd
play_star = pd.read_excel("../data/raw/playTop77_star.xlsx")
play_star

      Unnamed: 0            Title           ID  Star        Date
0           5316  연극 〈운빨로맨스〉- 대학로    seeun0***     5  2023.10.10
1           5317  연극 〈운빨로맨스〉- 대학로     isoo9***     5  2023.10.10
2           5318  연극 〈운빨로맨스〉- 대학로    rkgml5***     5  2023.10.09
3           5324  연극 〈운빨로맨스〉- 대학로       da9***     5  2023.10.03
4           5325  연극 〈운빨로맨스〉- 대학로      4322***     5  2023.09.28
...          ...              ...          ...   ...         ...
9725        9818          그곳에 있었다     judy7***     5  2023.09.14
9726        9819          그곳에 있었다      ddhj***     5  2023.09.03
9727        9820          그곳에 있었다   gustnr4***     5  2023.09.03
9728        9821          그곳에 있었다  pinkhwan***     5  2023.09.03
9729        9822          그곳에 있었다     prais***     4  2023.09.02

[9730 rows x 5 columns]

In [34]:
print(type(play_star))

<class 'pandas.core.frame.DataFrame'>

In [35]:
star = play_star['Star']
print(play_star.shape[0])
num_play = play_star.shape[0]
print(type(num_play))

9730
<class 'int'>


코드 설명
1.   1+review_count: 리뷰 수에 1을 더함. 분모가 0이되는 것을 방지하기 위해.
2.   항목 추가

In [36]:
# user_ratings : 별점리스트, review_count: 전체 행개수
def calculate_weighted_rating (user_ratings, review_count, base_weight=1.0):

  # 가중치 계산
  weight = base_weight*( 1.0 + review_count)    # 사람 수가 적을수록 가중치 감소/ 기본 가중치값 먼저 필요

  # 평균 별점 계산
  average_rating = sum(user_ratings)/len(user_ratings)   # 작품명 같은 것끼리 계산

  # 가중 평균 별점 계산
  weighted_rating = average_rating*weight

  return weighted_rating

## 데이터 함수 적용

*   같은 작품끼리 어떻게 묶을 것인지 정해야함
*   for문 이용해서 작품마다 함수 돌려야함

In [37]:
# 일단 작품이름 같은 것끼리 묶어야함
# 묶은 것에서 user_rating 리스트 만들기
# 묶은 것 아이템 개수=작품별 리뷰 개수 계산
# for문 이용해서 작품 하나씩 들어가서 돌려야함.
# 결과  --> 작품: 가중치 이런식으로 아웃풋.

In [38]:
# 제목별로 별점 그룹화
grouped_title = play_star.groupby('Title')['Star'].apply(list).reset_index()
type(grouped_title)

pandas.core.frame.DataFrame

In [39]:
# 별점 가중치 함수 데이터에 적용

review_count = 100
weighted_ratings = {}

for row in grouped_title.itertuples():
  title = row.Title
  user_ratings = row.Star

  # 가중 평균 계산 함수 호출
  weighted_rating = calculate_weighted_rating(user_ratings, review_count=len(user_ratings))
  weighted_ratings[title] = weighted_rating


for title, weighted_rating in weighted_ratings.items():
    print(f"Title: {title}, Weighted Rating: {weighted_rating}")

Title: (리얼타임 코믹연극) 택시안에서 - 서울, Weighted Rating: 1005.744075829384
Title: (코믹연극) 달동네-부산, Weighted Rating: 73.92857142857143
Title: 10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀, Weighted Rating: 2462.819607843137
Title: 2023 연극 〈친정엄마와 2박 3일〉 - 고양, Weighted Rating: 33.142857142857146
Title: 2시간탈출 졸탄쇼, Weighted Rating: 653.7720588235295
Title: 3대가 웃고 우는 연극 〈염쟁이 유씨〉, Weighted Rating: 68.92307692307693
Title: 4D공포연극 〈스위치〉, Weighted Rating: 2457.9555555555557
Title: ★평점9.5★ 코미디의맛/쇼미더퍼니, Weighted Rating: 2124.7640449438204
Title: 공포스릴러연극〈두여자〉- 대구, Weighted Rating: 310.0
Title: 공포연극 조각, Weighted Rating: 617.7890625
Title: 공포연극 ［자취］, Weighted Rating: 966.81
Title: 국민 코믹 연극 〈오백에삼십〉 - 대학로 세우아트센터 1관, Weighted Rating: 2800.8966725043783
Title: 그곳에 있었다, Weighted Rating: 57.81818181818182
Title: 나의 장례식에 와줘, Weighted Rating: 73.92857142857143
Title: 대학로 1위 연극 〈쉬어매드니스〉, Weighted Rating: 2432.7607843137253
Title: 대학로 청소년연극 〈사춘기메들리〉, Weighted Rating: 716.9444444444445
Title: 로맨틱코미디 〈슬기로운 신혼생활〉, Weighted Rating: 533.8981481481482
Title: 모든 날 모든 순간, Weighted Rating: 83.9375
Title: 뮤직드라마 〈불편한 편의점〉, Weighted Rating: 1122.717299578059
Title: 연극 〈굿닥터〉, Weighted Rating: 134.8148148148148
Title: 연극 〈극적인 하룻밤〉, Weighted Rating: 240.72
Title: 연극 〈기형도 플레이〉, Weighted Rating: 23.75
Title: 연극 〈나의PS파트너〉, Weighted Rating: 241.9375
Title: 연극 〈바닷마을 다이어리〉, Weighted Rating: 115.625
Title: 연극 〈뷰티풀라이프〉, Weighted Rating: 2556.936170212766
Title: 연극 〈수상한흥신소〉, Weighted Rating: 322.96875
Title: 연극 〈운빨로맨스〉- 대학로, Weighted Rating: 3498.9073033707864
Title: 연극 〈카페 쥬에네스〉, Weighted Rating: 409.009900990099
Title: 연극 너의 목소리가 들려, Weighted Rating: 2188.986301369863
Title: 연극 죽여주는 이야기, Weighted Rating: 1595.971875
Title: 연극 한뼘사이, Weighted Rating: 2957.9134775374378
Title: 연극 핫식스, Weighted Rating: 1385.9676258992806
Title: 연극〈늘근도둑이야기〉, Weighted Rating: 2458.811764705882
Title: 이머시브씨어터 카지노, Weighted Rating: 1377.9035714285715
Title: 좀비연극 오마이갓, Weighted Rating: 2070.966346153846
Title: 진짜나쁜소녀, Weighted Rating: 654.7794117647059
Title: 코미디 연극〈딜리버리〉, Weighted Rating: 226.72340425531917
Title: 코믹감동 휴먼판타지 연극 〈2호선 세입자〉, Weighted Rating: 2811.601639344262
Title: 행오버, Weighted Rating: 958.7462686567164
Title: ［2023 SPAF］ 극단 돌파구 〈지상의 여자들〉, Weighted Rating: 97.65
Title: ［서울 대학로］연극 라면, Weighted Rating: 2428.8969696969693

In [40]:
def star_weight(excel):
  import pandas as pd
  star_df = pd.read_excel(excel)
  star = star_df['Star']
  num_play = star_df.shape[0]

  # 일단 작품이름 같은 것끼리 묶어야함
  # 묶은 것에서 user_rating 리스트 만들기
  # 묶은 것 아이템 개수=작품별 리뷰 개수 계산
  # for문 이용해서 작품 하나씩 들어가서 돌려야함.
  # 결과  --> 작품: 가중치 이런식으로 아웃풋.

  # 제목별로 별점 그룹화
  grouped_title = star_df.groupby('Title')['Star'].apply(list).reset_index()
  type(grouped_title)

  # 별점 가중치 함수 데이터에 적용

  review_count = 100
  weighted_ratings = {}

  for row in grouped_title.itertuples():
    title = row.Title
    user_ratings = row.Star

    # 가중 평균 계산 함수 호출
    weighted_rating = calculate_weighted_rating(user_ratings, review_count=len(user_ratings))
    weighted_ratings[title] = weighted_rating


  for title, weighted_rating in weighted_ratings.items():
      print(f"Title: {title}, Weighted Rating: {weighted_rating}")
  return weighted_ratings

In [41]:
play_weighted_ratings = star_weight("../data/raw/playTop77_star.xlsx")
musical_weighted_ratings = star_weight("../data/raw/musicalTop77_star.xlsx")

Title: (리얼타임 코믹연극) 택시안에서 - 서울, Weighted Rating: 1005.744075829384
Title: (코믹연극) 달동네-부산, Weighted Rating: 73.92857142857143
Title: 10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀, Weighted Rating: 2462.819607843137
Title: 2023 연극 〈친정엄마와 2박 3일〉 - 고양, Weighted Rating: 33.142857142857146
Title: 2시간탈출 졸탄쇼, Weighted Rating: 653.7720588235295
Title: 3대가 웃고 우는 연극 〈염쟁이 유씨〉, Weighted Rating: 68.92307692307693
Title: 4D공포연극 〈스위치〉, Weighted Rating: 2457.9555555555557
Title: ★평점9.5★ 코미디의맛/쇼미더퍼니, Weighted Rating: 2124.7640449438204
Title: 공포스릴러연극〈두여자〉- 대구, Weighted Rating: 310.0
Title: 공포연극 조각, Weighted Rating: 617.7890625
Title: 공포연극 ［자취］, Weighted Rating: 966.81
Title: 국민 코믹 연극 〈오백에삼십〉 - 대학로 세우아트센터 1관, Weighted Rating: 2800.8966725043783
Title: 그곳에 있었다, Weighted Rating: 57.81818181818182
Title: 나의 장례식에 와줘, Weighted Rating: 73.92857142857143
Title: 대학로 1위 연극 〈쉬어매드니스〉, Weighted Rating: 2432.7607843137253
Title: 대학로 청소년연극 〈사춘기메들리〉, Weighted Rating: 716.9444444444445
Title: 로맨틱코미디 〈슬기로운 신혼생활〉, Weighted Rating: 533.8981481481482
Title: 모든 날 모든 순간, Weighted Rating: 83.9375
Title: 뮤직드라마 〈불편한 편의점〉, Weighted Rating: 1122.717299578059
Title: 연극 〈굿닥터〉, Weighted Rating: 134.8148148148148
Title: 연극 〈극적인 하룻밤〉, Weighted Rating: 240.72
Title: 연극 〈기형도 플레이〉, Weighted Rating: 23.75
Title: 연극 〈나의PS파트너〉, Weighted Rating: 241.9375
Title: 연극 〈바닷마을 다이어리〉, Weighted Rating: 115.625
Title: 연극 〈뷰티풀라이프〉, Weighted Rating: 2556.936170212766
Title: 연극 〈수상한흥신소〉, Weighted Rating: 322.96875
Title: 연극 〈운빨로맨스〉- 대학로, Weighted Rating: 3498.9073033707864
Title: 연극 〈카페 쥬에네스〉, Weighted Rating: 409.009900990099
Title: 연극 너의 목소리가 들려, Weighted Rating: 2188.986301369863
Title: 연극 죽여주는 이야기, Weighted Rating: 1595.971875
Title: 연극 한뼘사이, Weighted Rating: 2957.9134775374378
Title: 연극 핫식스, Weighted Rating: 1385.9676258992806
Title: 연극〈늘근도둑이야기〉, Weighted Rating: 2458.811764705882
Title: 이머시브씨어터 카지노, Weighted Rating: 1377.9035714285715
Title: 좀비연극 오마이갓, Weighted Rating: 2070.966346153846
Title: 진짜나쁜소녀, Weighted Rating: 654.7794117647059
Title: 코미디 연극〈딜리버리〉, Weighted Rating: 226.72340425531917
Title: 코믹감동 휴먼판타지 연극 〈2호선 세입자〉, Weighted Rating: 2811.601639344262
Title: 행오버, Weighted Rating: 958.7462686567164
Title: ［2023 SPAF］ 극단 돌파구 〈지상의 여자들〉, Weighted Rating: 97.65
Title: ［서울 대학로］연극 라면, Weighted Rating: 2428.8969696969693
Title: 난타(NANTA) - 명동공연, Weighted Rating: 790.8518518518518
Title: 더 맨 얼라이브 〈초이스〉, Weighted Rating: 867.8483146067415
Title: 뮤지컬 〈22년 2개월〉, Weighted Rating: 2417.826
Title: 뮤지컬 〈곤 투모로우〉, Weighted Rating: 2451.8940000000002
Title: 뮤지컬 〈구텐버그〉, Weighted Rating: 2463.918
Title: 뮤지컬 〈김종욱 찾기〉, Weighted Rating: 1086.85201793722
Title: 뮤지컬 〈레미제라블〉 - 부산, Weighted Rating: 565.6363636363636
Title: 뮤지컬 〈레베카〉 10주년 기념공연, Weighted Rating: 2424.84
Title: 뮤지컬 〈렛미플라이〉, Weighted Rating: 1644.9249249249249
Title: 뮤지컬 〈멤피스〉, Weighted Rating: 2438.868
Title: 뮤지컬 〈문스토리〉, Weighted Rating: 1328.8498168498168
Title: 뮤지컬 〈블랙메리포핀스〉, Weighted Rating: 2416.824
Title: 뮤지컬 〈비더슈탄트〉, Weighted Rating: 2426.844
Title: 뮤지컬 〈사칠〉, Weighted Rating: 2463.918
Title: 뮤지컬 〈삼총사〉, Weighted Rating: 537.8899082568807
Title: 뮤지컬 〈셜록홈즈 : 앤더슨가의 비밀〉, Weighted Rating: 1881.7279596977332
Title: 뮤지컬 〈쇼맨_어느 독재자의 네 번째 대역배우〉, Weighted Rating: 2484.96
Title: 뮤지컬 〈오페라의 유령〉 - 서울, Weighted Rating: 10.0
Title: 뮤지컬 〈왓 이프〉, Weighted Rating: 1687.864161849711
Title: 뮤지컬 〈위윌락유〉, Weighted Rating: 712.8827586206896
Title: 뮤지컬 〈이토록 보통의〉, Weighted Rating: 2210.902222222222
Title: 뮤지컬 〈인사이드 윌리엄〉 2023, Weighted Rating: 2456.904
Title: 뮤지컬 〈칠칠〉, Weighted Rating: 2212.831509846827
Title: 뮤지컬 〈킴즈〉, Weighted Rating: 840.8323699421965
Title: 뮤지컬 〈타오르는 어둠 속에서〉, Weighted Rating: 2447.886
Title: 뮤지컬 〈투모로우 모닝〉, Weighted Rating: 115.82608695652175
Title: 뮤지컬 〈판〉, Weighted Rating: 2093.9738095238095
Title: 뮤지컬 〈프리다〉, Weighted Rating: 2395.782
Title: 뮤지컬 〈후크〉, Weighted Rating: 2434.86
Title: 뮤지컬 더데빌 : 에덴 (Musical THE DEVIL : EDEN), Weighted Rating: 1422.2710843373493
Title: 뮤지컬 드라큘라 (Dracula：The Musical), Weighted Rating: 2444.88
Title: 뮤지컬 스크루테이프의 편지, Weighted Rating: 79.6875
Title: 뮤지컬 썸데이, Weighted Rating: 530.9622641509434
Title: 뮤지컬 프리즌, Weighted Rating: 305.77777777777777
Title: 뮤지컬 ＇벤허＇, Weighted Rating: 2426.8929292929292
Title: 뮤직드라마 당신만이, Weighted Rating: 200.9
Title: 쇼 뮤지컬 〈시스터즈 (SheStars!)〉, Weighted Rating: 2334.864300626305
Title: 써니텐, Weighted Rating: 861.8971428571429
Title: 이은결 ［더 일루션 - 마스터피스］, Weighted Rating: 158.96774193548387
Title: ［청주,세종］뮤지컬 빌의구둣방, Weighted Rating: 86.8235294117647

# 배우 가중치 함수

## PlayDB 누적조회순 랭킹 불러오기

---

 - actor_dic 딕셔너리 구조

{ 배우 : { 'index': 순위, 'masterpiece' : [최근공연 3개 리스트] } }

In [42]:
import pandas as pd
def actor_lanking(csv):
  actor_csv = pd.read_csv(csv, encoding='utf-8')
  actor_csv.columns = ["index", "actor_name", "masterpiece"]

  # 랭킹에 있는 배우들의 작품만 따로 추출 (작품명이 \n으로 이어진 하나의 문자열이기 때문에, 리스트화 시킬 예정)
  actor_mp = actor_csv['masterpiece'].to_list()

  actor_dic = actor_csv.set_index('index').T.to_dict()  # 딕셔너리 형태로 변환

  # key: actor_name, value: index, masterpiece
  for key, value in actor_dic.items():
    temp = value['masterpiece']
    temp2 = temp.split('\n')
    value['masterpiece'] = temp2
  return actor_dic

In [43]:
play_actor_dic = actor_lanking("../data/rawtheater_actor_rank.csv")
play_actor_dic

{0: {'actor_name': '최성희', 'masterpiece': ['몽실(2009)']},
 1: {'actor_name': '김다현',
  'masterpiece': ['루쓰(2023)',
   '더 그레이티스트 뮤지컬 콘서트 - 용인(2022)',
   '미세스 다웃파이어(2022)']},
 2: {'actor_name': '김지현',
  'masterpiece': ['그날들 - 대구(2023)', '그날들(2023)', '스위니토드(2022)']},
 3: {'actor_name': '박호산',
  'masterpiece': ['기형도 플레이(2023)', '오셀로(2023)', '무제의 시대(2022)']},
 4: {'actor_name': '윤주상',
  'masterpiece': ['타클라마칸(2018)',
   '웃어요 덕구씨(2016)',
   '2012 세계국립극장페스티벌 - 인물실록 봉달수(2012)']},
 5: {'actor_name': '조재현',
  'masterpiece': ['블랙버드(2016)',
   '2016 여우락페스티벌 - 2 조재현 황석정 두번째달(2016)',
   '에쿠우스(2015)']},
 6: {'actor_name': '이현수',
  'masterpiece': ['제11회 대구국제뮤지컬페스티벌 - 아름다운 슬픈 날(2017)',
   '화려한 싱글들(2012)',
   '순이야 사랑해(2012)']},
 7: {'actor_name': '송영창',
  'masterpiece': ['브로드웨이 42번가(2018)', '모래시계(2017)', '올드위키드송(2016)']},
 8: {'actor_name': '송승환',
  'masterpiece': ['더 드레서(2021)', '더 드레서(2020)', '뮤 하트(2019)']},
 9: {'actor_name': '김성녀',
  'masterpiece': ['심청이와 춘향이가 온다－의정부(2023)',
   '죽음의 배 & 갈매기 - 수원(2023)',
   '장수상회(2023)']},
 10: {'actor_name': '이상은',
  'masterpiece': ['영웅(2011)', '영웅(2011)', '명성황후(2011)']},
 11: {'actor_name': '조민아',
  'masterpiece': ['온에어 시즌 3(2009)', '렌트(2009)', '온에어(2008)']},
 12: {'actor_name': '김소희',
  'masterpiece': ['햄릿 걷는 인간(2023)', '세자매 죽음의 파티(2023)', '에드거 앨런 포의 불안(2022)']},
 13: {'actor_name': '최화정',
  'masterpiece': ['SBS 파워FM 20주년 콘서트 POWER 20(2016)',
   '연극열전2 - 리타 길들이기(2008)']},
 14: {'actor_name': '김태훈',
  'masterpiece': ['14인 체홉(2017)', '세일즈맨의 죽음(2016)', '비극의 일인자(2016)']},
 15: {'actor_name': '이유린',
  'masterpiece': ['비뇨기과 미쓰리(2015)', '싸이코(2014)', '개인교수2(2014)']},
 16: {'actor_name': '이동수',
  'masterpiece': ['스페셜 라이어(2021)', '라이어 1탄(2018)', '라이어 1탄(2017)']},
 17: {'actor_name': '이항나',
  'masterpiece': ['갈매기(2022)', '스웨트(2020)', '가미카제 아리랑(2019)']},
 18: {'actor_name': '이성민',
  'masterpiece': ['스물스물 차이무 - 꼬리솜 이야기(2015)',
   '마르고 닳도록 - 고양(2014)',
   '거기(2012)']},
 19: {'actor_name': '김화영',
  'masterpiece': ['고목(2023)', '장녀들(2023)', '스카프와 나이프(2022)']},
 20: {'actor_name': '조민기',
  'masterpiece': ['산불(2011)', '여름과 연기(2007)', '갈매기(2007)']},
 21: {'actor_name': '최덕문',
  'masterpiece': ['기형도 플레이(2023)', '곁에 있어도 혼자(2019)', '14인 체홉(2017)']},
 22: {'actor_name': '김지성',
  'masterpiece': ['불(2019)', '2017 서울국제공연예술제 - 위대한 놀이(2017)', '타바스코(2015)']},
 23: {'actor_name': '이신성',
  'masterpiece': ['연애시대(2013)', '로미오와 줄리엣(2013)', '결혼(2013)']},
 24: {'actor_name': '유순웅',
  'masterpiece': ['염쟁이 유씨 - 김해(2022)',
   '조씨고아 복수의 씨앗(2021)',
   '염쟁이 유씨 - 평택(2020)']},
 25: {'actor_name': '이지현',
  'masterpiece': ['20세기 블루스(2023)', '조씨고아 복수의 씨앗(2021)', '이게 마지막이야(2020)']},
 26: {'actor_name': '조성지',
  'masterpiece': ['맨 오브 라만차(2021)', '스위니토드(2019)', '스위니토드(2016)']},
 27: {'actor_name': '권혁준',
  'masterpiece': ['도둑배우(2019)', '라이어 1탄(2018)', '라이어 1탄(2017)']},
 28: {'actor_name': '강신일',
  'masterpiece': ['광부화가들(2022)', '강신일과 흔들거리며(2020)', '한정림의 음악일기(2020)']},
 29: {'actor_name': '이승헌',
  'masterpiece': ['송이섬의 바람 - 제주(2019)', '수업(2018)', '백석우화(2017)']},
 30: {'actor_name': '윤석화',
  'masterpiece': ['햄릿(2022)', '자화상(2021)', '해롤드와 모드(2021)']},
 31: {'actor_name': '류덕환',
  'masterpiece': ['에쿠우스(2019)', '두산인문극장 2018 이타주의자 - 낫심(2018)', '에쿠우스(2015)']},
 32: {'actor_name': '류현경',
  'masterpiece': ['3일간의 비(2023)', '렁스(2021)', '올모스트 메인(2016)']},
 33: {'actor_name': '우상욱',
  'masterpiece': ['월명 - 경주(2020)', '얼쑤 - 여수(2019)', '쿵짝(2018)']},
 34: {'actor_name': '남권아',
  'masterpiece': ['갈매기(2023)', '불(2019)', '2017 서울국제공연예술제 - 위대한 놀이(2017)']},
 35: {'actor_name': '노진원',
  'masterpiece': ['늘근도둑 이야기 - 화성(2020)',
   '늘근도둑 이야기 - 경주(2019)',
   '늘근도둑 이야기(2017)']},
 36: {'actor_name': '윤정섭',
  'masterpiece': ['억척어멈과 그의 자식들(2017)', '길 떠나는 가족(2017)', '이 일을 어찌할꼬!(2017)']},
 37: {'actor_name': '고동업',
  'masterpiece': ['사로잡힌 꿈(2022)', '아버지 - 안양(2016)', '배꼽춤을 추는 허수아비(2016)']},
 38: {'actor_name': '백원길',
  'masterpiece': ['2013 명동예술극장 여름레퍼토리 - 휴먼코메디(2013)',
   '한꺼번에 두 주인을(2012)',
   '노이즈 오프 - 대전(2012)']},
 39: {'actor_name': '이호영',
  'masterpiece': ['셰익스피어 인 러브(2023)', '더 헬멧(2022)', '모토타운(2020)']},
 40: {'actor_name': '정경호',
  'masterpiece': ['화양연화(2023)', '필로우맨(2022)', '엄마의 레시피(2018)']},
 41: {'actor_name': '나경민',
  'masterpiece': ['우주 양자 마음(2023)', '오일(2021)', '산울림 고전극장 - 보들레르(2020)']},
 42: {'actor_name': '오동식',
  'masterpiece': ['씨걸(2022)', '우리 동네 동선동(2021)', '뤼송(2021)']},
 43: {'actor_name': '김경민',
  'masterpiece': ['우먼인블랙(2014)', '우먼인블랙(2013)', '부활 - 더 골든 데이즈(2012)']},
 44: {'actor_name': '박원상',
  'masterpiece': ['광부화가들(2022)',
   '달빛요정과 소녀(2019)',
   '스물스물 차이무 - 양덕원 이야기(2016)']},
 45: {'actor_name': '김수정',
  'masterpiece': ['부동산 오브 슈퍼맨(2023)',
   '국산예수(2023)',
   '2022 망각댄스 - 4.16편(2022)']},
 46: {'actor_name': '이도국',
  'masterpiece': ['스페셜 라이어(2021)',
   '브라더 포인트(2019)',
   '제5회 무죽 페스티벌 - 브라더 포인트(2019)']},
 47: {'actor_name': '정혜진',
  'masterpiece': ['개인의 취향(2013)', '작업의 정석 2탄(2012)', '작업의 정석 - 광주(2012)']},
 48: {'actor_name': '김늘메',
  'masterpiece': ['노르망디(2023)', '복길잡화점 - 성남(2023)', '면회(2023)']},
 49: {'actor_name': '하희라',
  'masterpiece': ['러브레터(2022)', '굿바이걸(2008)', '우리가 애인을 꿈꾸는 이유(2004)']},
 50: {'actor_name': '신문성',
  'masterpiece': ['심청전을 짓다(2022)',
   '76 페스티벌 - 심청전을 짓다(2021)',
   '이카이노의 눈(2020)']},
 51: {'actor_name': '박은영',
  'masterpiece': ['미리내 삼대 - 부천(2023)', '불편한 편의점(2023)', '마이 맘(2015)']},
 52: {'actor_name': '류태호',
  'masterpiece': ['멍(2020)', '언더스터디(2016)', '날 보러와요(2016)']},
 53: {'actor_name': '강태기',
  'masterpiece': ['눈꽃편지(2012)', '이뭣꼬(2011)', '그대를 사랑합니다 - 원주(2010)']},
 54: {'actor_name': '이상혁',
  'masterpiece': ['러브레터(2012)', '연애시대(2011)', '팻 피그(2011)']},
 55: {'actor_name': '최정우',
  'masterpiece': ['연극열전3 - 세상에서 가장 아름다운 이별(2010)',
   '연극열전2 - 블랙버드(2008)',
   '필로우맨(2007)']},
 56: {'actor_name': '홍은희',
  'masterpiece': ['돌아온다(2022)', '멜로드라마(2014)', '클로져(2008)']},
 57: {'actor_name': '신안진',
  'masterpiece': ['다크레이디X프랭클린(2023)',
   '제11회 서울미래연극제 공식참가작 - 햄버거 먹다가 생각날 이야기(2021)',
   '천만 개의 도시(2021)']},
 58: {'actor_name': '정인겸',
  'masterpiece': ['2015 서울연극제 - 불량청년(2015)',
   '비극의 일인자(2013)',
   '물탱크 정류장(2013)']},
 59: {'actor_name': '박광정',
  'masterpiece': ['부드러운 매장', '서울노트(2008)', '하이라이프 - 대구(2008)']},
 60: {'actor_name': '박시은', 'masterpiece': ['연애시대(2011)', 'JESUS JESUS(2008)']},
 61: {'actor_name': '안내상',
  'masterpiece': ['스페셜 라이어(2017)', '우리의 여자들(2016)', '너와 함께라면(2012)']},
 62: {'actor_name': '하용부',
  'masterpiece': ['아름다운 계절 - 창원(2015)', '오구 - 대구(2015)', '어머니 - 순천(2013)']},
 63: {'actor_name': '정성윤',
  'masterpiece': ['국화꽃향기(2016)', '국화꽃향기(2014)', '찍힌놈들(2014)']},
 64: {'actor_name': '조재윤',
  'masterpiece': ['아트(2020)', '정의의 사람들(2018)', '벽을 뚫는 남자(2015)']},
 65: {'actor_name': '조하나',
  'masterpiece': ['소년대로(2023)', '소년 대로(2022)', '산울림 고전극장 - 체험 삶의 현장(2022)']},
 66: {'actor_name': '송요셉',
  'masterpiece': ['라이어 2탄 - 평택(2018)', '라이어 1탄(2017)', '라이어 1탄 - 부산(2016)']},
 67: {'actor_name': '이강',
  'masterpiece': ['이원복의 먼나라 이웃나라 클래식 콘서트(2014)', '팝콘(2011)', '설공찬전(2010)']},
 68: {'actor_name': '김미숙',
  'masterpiece': ['햄릿 걷는 인간(2023)', '세자매 죽음의 파티(2023)', '백석우화(2017)']},
 69: {'actor_name': '김윤태',
  'masterpiece': ['누란누란(2023)', '디바(2022)', '니 부모 얼굴이 보고싶다(2022)']},
 70: {'actor_name': '김대건',
  'masterpiece': ['언더스터디(2016)', '잉여인간 이바노프(2015)', '잉여인간 이바노프(2014)']},
 71: {'actor_name': '배수빈',
  'masterpiece': ['컨택트(2017)', '프라이드(2017)', '카포네 트릴로지(2016)']},
 72: {'actor_name': '김성규',
  'masterpiece': ['디바(2022)', '골든타임(2018)', '프러포즈 못하는 남자(2018)']},
 73: {'actor_name': '이새별',
  'masterpiece': ['안녕 히틀러(2016)', '달아나라 편지야(2013)', '훈남들의 수다(2012)']},
 74: {'actor_name': '선욱현',
  'masterpiece': ['물고기 남자(2022)', '그때 변홍례(2019)', '카모마일과 비빔면(2019)']},
 75: {'actor_name': '최귀화',
  'masterpiece': ['투룸쇼(2012)', '오! 브라더스 - 대구 첫 공연(2010)', '오! 브라더스(2010)']},
 76: {'actor_name': '정한별',
  'masterpiece': ['나의 노래 - 과천(2018)',
   '2018 춘천연극제 - 바람이 불어오는 곳(2018)',
   '바람이 불어오는 곳 - 울산(2016)']},
 77: {'actor_name': '문예주',
  'masterpiece': ['스카팽(2022)', '금조 이야기(2022)', '로드킬 인 더 씨어터(2021)']},
 78: {'actor_name': '차희',
  'masterpiece': ['콤플렉스(2023)', '니 부모 얼굴이 보고싶다(2022)', '물의 정거장(2021)']},
 79: {'actor_name': '박준혁',
  'masterpiece': ['캐미스트리 래버토리(2018)', '결혼전야 - 경기 광주(2018)', '칸사이 주먹(2018)']},
 80: {'actor_name': '김홍근',
  'masterpiece': ['윤대성 X 윤대성(2019)', '궁전의 여인들(2019)', '궁전의 여인들(2018)']},
 81: {'actor_name': '김명수',
  'masterpiece': ['만선(2023)', '레 미제라블 - 고양(2022)', '레 미제라블(2022)']},
 82: {'actor_name': '김준삼',
  'masterpiece': ['의자고치는 여인(2020)',
   '제40회 서울연극제 공식선정작 - 벤트(2019)',
   '이혈(2018)']},
 83: {'actor_name': '이윤지',
  'masterpiece': ['언더스터디(2021)', '3일간의 비(2017)', '클로저(2013)']},
 84: {'actor_name': '김인경',
  'masterpiece': ['제39회 대한민국연극제 안동 - 알을 깨고 나온 새는 무엇으로 나는가(2021)',
   '제30회 대전연극제 - 알을 깨고 나온 새는 무엇으로 나는가(2021)',
   '알을 깨고 나온 새는 무엇으로 나는가 - 대전(2020)']},
 85: {'actor_name': '황승현',
  'masterpiece': ['달래이야기(2017)', '다시 한 달을 가서 설산을 넘으면(2013)', '더 프라이스(2012)']},
 86: {'actor_name': '김지희',
  'masterpiece': ['맥베스 - 수원(2023)',
   '죽음의 배 & 갈매기 - 수원(2023)',
   '죽음들 - 수원(2023)']},
 87: {'actor_name': '박경구',
  'masterpiece': ['그로토프스키 트레이닝(2023)', '해피투게더(2022)', '광장 너머(2022)']},
 88: {'actor_name': '추상록',
  'masterpiece': ['그대의 봄 - 하남(2011)', '그대의 봄(2011)', '하이라이프(2007)']},
 89: {'actor_name': '구시연',
  'masterpiece': ['스고파라갈(2023)', '스크루테이프(2023)', '스크루테이프(2023)']},
 90: {'actor_name': '이선민',
  'masterpiece': ['타악기야 놀자!(2018)', '셜록홈즈(2014)', '그놈을 잡아라(2013)']},
 91: {'actor_name': '김은경',
  'masterpiece': ['바다로 가는 기사들(2023)', '로미오와 줄리엣(2023)', '나는 꽃이 싫다(2019)']},
 92: {'actor_name': '전현아',
  'masterpiece': ['더 파더(2023)', '엄마 이야기(2018)', '엄마 이야기(2017)']},
 93: {'actor_name': '홍선주',
  'masterpiece': ['바보미소 - 부산(2017)', '춘향YO(2016)', '몽키댄스 - 부산(2016)']},
 94: {'actor_name': '빈혜경',
  'masterpiece': ['M.Butterfly(2015)', 'M.Butterfly(2014)', '블랙박스(2012)']},
 95: {'actor_name': '류승룡', 'masterpiece': ['연극열전2 - 장진의 서툰사람들(2008)']},
 96: {'actor_name': '윤진식',
  'masterpiece': ['자메이카 헬스클럽(2018)', '자메이카 헬스클럽(2018)', '엽기적인 그녀 - 수원(2017)']},
 97: {'actor_name': '윤토왕',
  'masterpiece': ['룸넘버13 - 부산(2020)', '룸넘버13(2016)', '죽여주는 이야기 - 대구(2016)']},
 98: {'actor_name': '유홍영',
  'masterpiece': ['게르니카(2011)', '게르니카(2011)', '극단 사다리 꼬방꼬방(2010)']},
 99: {'actor_name': '한채영', 'masterpiece': ['연극열전2 - 장진의 서툰사람들(2008)']}}

In [44]:
mus_actor_dic = actor_lanking("../data/raw/musical_actor_rank.csv")
mus_actor_dic

{0: {'actor_name': '임태경',
  'masterpiece': ['할란카운티(2023)', '지저스 크라이스트 수퍼스타(2022)', '나폴레옹 헌정 콘서트(2022)']},
 1: {'actor_name': '김다현',
  'masterpiece': ['루쓰(2023)',
   '더 그레이티스트 뮤지컬 콘서트 - 용인(2022)',
   '미세스 다웃파이어(2022)']},
 2: {'actor_name': '차지연',
  'masterpiece': ['컴프롬어웨이(2023)', '차지연 콘서트(2023)', '아마데우스(2023)']},
 3: {'actor_name': '김지현',
  'masterpiece': ['그날들 - 대구(2023)', '그날들(2023)', '스위니토드(2022)']},
 4: {'actor_name': '바다',
  'masterpiece': ['안양 시 승격 50주년 기념 신년음악회 - 안양(2023)',
   '제주신화월드 카운트다운 2023 - 제주(2022)',
   '드라뮤지션 바다 콘서트 - 하남(2022)']},
 5: {'actor_name': '규현',
  'masterpiece': ['규현 & HYNN 콘서트(2023)', '벤허(2023)', '2023 서울파크뮤직페스티벌(2023)']},
 6: {'actor_name': '박호산',
  'masterpiece': ['기형도 플레이(2023)', '오셀로(2023)', '무제의 시대(2022)']},
 7: {'actor_name': '주지훈',
  'masterpiece': ['주지훈 팬미팅(2019)', '생명의 항해(2010)', '돈 주앙(2009)']},
 8: {'actor_name': '강태을',
  'masterpiece': ['몬테크리스토(2023)', '엘리자벳(2022)', '엑스칼리버(2022)']},
 9: {'actor_name': '정민',
  'masterpiece': ['스모크(2023)', '사의찬미 콘서트(2023)', '구텐버그(2023)']},
 10: {'actor_name': '장승조',
  'masterpiece': ['킹아더(2019)', '더 데빌(2017)', '구텐버그(2014)']},
 11: {'actor_name': '이자람',
  'masterpiece': ['노인과 바다 - 평택(2023)', '순신(2023)', '노인과 바다 - 경기 광주(2023)']},
 12: {'actor_name': '김도현',
  'masterpiece': ['배니싱(2018)', '리차드3세(2018)', '금강 1894 - 성남(2017)']},
 13: {'actor_name': '송원근',
  'masterpiece': ['오페라의 유령(2023)', '레드북(2023)', '이프덴(2022)']},
 14: {'actor_name': '소냐',
  'masterpiece': ['포르테 디 콰트로 ＆ 소냐 콘서트 - 구미(2023)',
   '뮤지컬 갈라 콘서트 - 함양(2022)',
   '라비앙로즈 - 화성(2022)']},
 15: {'actor_name': '문혜원',
  'masterpiece': ['타오르는 어둠 속에서(2023)',
   '제15회 대구국제뮤지컬페스티벌 - 스페셜5(2021)',
   '인현왕후 - 김천(2019)']},
 16: {'actor_name': '이율',
  'masterpiece': ['트레이스 유(2023)', '모래시계(2022)', '트레이스 유(2021)']},
 17: {'actor_name': '박해미',
  'masterpiece': ['블루 블라인드 - 의정부(2023)',
   '박해미 콘서트 - 구리(2023)',
   '어게인 - 여고동창생(2023)']},
 18: {'actor_name': '이태원',
  'masterpiece': ['블루 블라인드 - 의정부(2023)', '헤다가블러(2023)', '엘리자벳(2018)']},
 19: {'actor_name': '김선경',
  'masterpiece': ['아몬드(2022)', '포미니츠(2021)', '메노포즈(2018)']},
 20: {'actor_name': '린아',
  'masterpiece': ['레미제라블(2023)', '스위니토드(2022)', '몬테크리스토(2020)']},
 21: {'actor_name': '인순이',
  'masterpiece': ['우드스탁 뮤직 & 아트 페어 - 포천(2023)',
   '인순이 콘서트 - 전주(2022)',
   '2022 춘천 팸팸 페스타(2022)']},
 22: {'actor_name': '이현수',
  'masterpiece': ['제11회 대구국제뮤지컬페스티벌 - 아름다운 슬픈 날(2017)',
   '화려한 싱글들(2012)',
   '순이야 사랑해(2012)']},
 23: {'actor_name': '김도형',
  'masterpiece': ['영웅(2022)', '명성황후(2021)', '스위니토드(2019)']},
 24: {'actor_name': '백주연',
  'masterpiece': ['할란카운티(2023)', '삼총사(2022)', '잭 더 리퍼(2021)']},
 25: {'actor_name': '이희정',
  'masterpiece': ['벤허(2023)', '루쓰(2023)', '프랑켄슈타인(2021)']},
 26: {'actor_name': '임강성',
  'masterpiece': ['다시 동물원(2023)', '은밀하게 위대하게', '오선지 걸어가는 작곡가(2022)']},
 27: {'actor_name': '오정해',
  'masterpiece': ['동백꽃 피는 날(2022)',
   '장사익 오정해 콘서트 - 고양(2022)',
   '오정해의 농담 - 정읍(2019)']},
 28: {'actor_name': '키',
  'masterpiece': ['디 아지트 - 키 랜드(2019)', '키 팬미팅(2018)', '지구를 지켜라(2017)']},
 29: {'actor_name': '김아선',
  'masterpiece': ['오페라의 유령(2023)', '드라큘라(2022)', '삼총사(2022)']},
 30: {'actor_name': '김수아',
  'masterpiece': ['비듬(2023)', '패션의 신 - 광명(2023)', '패션의 신 - 과천(2023)']},
 31: {'actor_name': '혜은이',
  'masterpiece': ['김승미 콘서트(2022)', '혜은이 콘서트(2020)', '혜은이 디너쇼(2019)']},
 32: {'actor_name': '송상은',
  'masterpiece': ['블랙메리포핀스(2023)', '눈을 뜻하는 수백 가지 단어들(2022)', '언성(2017)']},
 33: {'actor_name': '정준하',
  'masterpiece': ['시티오브엔젤(2019)', '청춘페스티벌 2016(2016)', '형제는 용감했다(2015)']},
 34: {'actor_name': '윤복희',
  'masterpiece': ['윤복희 콘서트 - 오산(2021)', '하모니(2021)', '39(2020)']},
 35: {'actor_name': '이상은',
  'masterpiece': ['영웅(2011)', '영웅(2011)', '명성황후(2011)']},
 36: {'actor_name': '이재환',
  'masterpiece': ['22년 2개월(2023)', '인간의 법정(2022)', '엑스칼리버(2022)']},
 37: {'actor_name': '소찬휘',
  'masterpiece': ['레트로슈퍼콘서트 - 대구(2023)',
   '박남정 소찬휘 콘서트 - 대구(2023)',
   '2022 구례 자연드림 락페스티벌(2022)']},
 38: {'actor_name': '조민아',
  'masterpiece': ['온에어 시즌 3(2009)', '렌트(2009)', '온에어(2008)']},
 39: {'actor_name': '황정민',
  'masterpiece': ['리차드3세(2022)', '김문정 콘서트(2019)', '오이디푸스(2019)']},
 40: {'actor_name': '려욱',
  'masterpiece': ['우드스탁 뮤직 & 아트 페어 - 포천(2023)',
   '팬레터(2021)',
   '썸데이 씨어터 라스트 칸타빌레(2021)']},
 41: {'actor_name': '박완규',
  'masterpiece': ['부활 콘서트(2023)',
   '김경호 박완규 소찬휘 콘서트(2019)',
   '포에버 콘서트 - 가평(2019)']},
 42: {'actor_name': '심규선',
  'masterpiece': ['심규선 콘서트(2023)', '심규선 콘서트(2022)', '심규선 유승우 콘서트 - 부산(2022)']},
 43: {'actor_name': '백재현',
  'masterpiece': ['오늘을 기억해 - 계룡(2022)',
   '슈퍼 루나틱 - 계룡(2021)',
   '슈퍼 루나틱 - 안동(2020)']},
 44: {'actor_name': '김성규',
  'masterpiece': ['김성규 콘서트(2023)', '레드북(2023)', '킹키부츠(2022)']},
 45: {'actor_name': '이동수',
  'masterpiece': ['스페셜 라이어(2021)', '라이어 1탄(2018)', '라이어 1탄(2017)']},
 46: {'actor_name': '정의욱',
  'masterpiece': ['설공찬(2023)', '스크루테이프(2023)', '스크루테이프(2023)']},
 47: {'actor_name': '김신의',
  'masterpiece': ['삼총사(2023)', '삼총사(2022)', '고래고래 콘서트(2018)']},
 48: {'actor_name': '온유',
  'masterpiece': ['태양의 노래(2022)', '태양의 노래(2021)', '태양의 노래(2021)']},
 49: {'actor_name': '이신성',
  'masterpiece': ['연애시대(2013)', '로미오와 줄리엣(2013)', '결혼(2013)']},
 50: {'actor_name': '김지현',
  'masterpiece': ['호프(2023)', '호프(2020)', '김미경 남경주 김지현의 토크 뮤직 - 수원(2014)']},
 51: {'actor_name': '유나영',
  'masterpiece': ['투모로우 모닝(2017)', '라카지(2014)', '라카지(2012)']},
 52: {'actor_name': '유정은',
  'masterpiece': ['청춘연가 - 목포(2022)', '영웅을 기다리며 - 부산(2016)', '그남자 그여자(2015)']},
 53: {'actor_name': '김세용',
  'masterpiece': ['2016 자라섬 뮤지컬 페스티벌(2016)', '빌리 엘리어트(2010)']},
 54: {'actor_name': '이용우',
  'masterpiece': ['제3회 이데일리 문화대상(2016)', '클럽 살로메(2015)', '댄싱9 시즌2 갈라쇼(2014)']},
 55: {'actor_name': '김원식',
  'masterpiece': ['청춘연가 - 목포(2022)', '스페셜 라이어(2021)', '라이어 1탄(2018)']},
 56: {'actor_name': '조성지',
  'masterpiece': ['맨 오브 라만차(2021)', '스위니토드(2019)', '스위니토드(2016)']},
 57: {'actor_name': '다나',
  'masterpiece': ['별이 빛나는 밤에(2016)', '위대한 캣츠비 RE', '위대한 캣츠비 RE']},
 58: {'actor_name': '소유진',
  'masterpiece': ['갈매기(2022)', '82년생 김지영(2022)', '리어왕(2021)']},
 59: {'actor_name': '양금석',
  'masterpiece': ['불효자는 웁니다 - 김해(2022)',
   '2018 평창동계올림픽 성공기원 콘서트 - 대전(2017)',
   '2017 새해음악회 - 음성(2017)']},
 60: {'actor_name': '선우',
  'masterpiece': ['트레이스 유(2023)', '젠틀맨스 가이드(2020)', '셜록홈즈(2020)']},
 61: {'actor_name': '김선영',
  'masterpiece': ['오필리어(2014)',
   '뮤지컬 배우 선영과 함께 하는 크리스마스 콘서트(2013)',
   '백야(2012)']},
 62: {'actor_name': '팀',
  'masterpiece': ['팀 콘서트 (2023)', '황태자 루돌프(2014)', '퍼밀리어 스토리(2014)']},
 63: {'actor_name': '이소정',
  'masterpiece': ['포미니츠(2022)',
   '베르나르다 알바(2021)',
   '이소정 with 조윤성 성민제 Paco - 부산(2017)']},
 64: {'actor_name': '이지명',
  'masterpiece': ['멸화군(2023)', '제16회 대구국제뮤지컬페스티벌 - 산들(2022)', '창업(2021)']},
 65: {'actor_name': '박진우',
  'masterpiece': ['레베카(2019)', '안나 카레니나(2019)', '오! 캐롤(2018)']},
 66: {'actor_name': '박지아',
  'masterpiece': ['마우스트랩(2023)', '76 페스티벌 - 심청전을 짓다(2021)', '엘리펀트 송(2019)']},
 67: {'actor_name': '강연종',
  'masterpiece': ['하트스트링스 - 부산(2023)', '강연종 콘서트 - 대전(2020)', '가야의 노래(2019)']},
 68: {'actor_name': '서현',
  'masterpiece': ['서현 팬미팅(2023)', '서현 팬미팅(2018)', '아니벌써 콘서트(2017)']},
 69: {'actor_name': '서현진', 'masterpiece': ['신데렐라(2015)', '궁(2010)']},
 70: {'actor_name': '최원준',
  'masterpiece': ['사랑은 비를 타고(2014)', '막돼먹은 영애씨(2012)', '막돼먹은 영애씨(2011)']},
 71: {'actor_name': '강인', 'masterpiece': ['궁(2012)', '제너두(2008)']},
 72: {'actor_name': '정진호',
  'masterpiece': ['2016 자라섬 뮤지컬 페스티벌(2016)', '아르센 루팡(2013)', '뮤지컬 13(2012)']},
 73: {'actor_name': '이광용',
  'masterpiece': ['외솔 겨레의 등불 최현배 - 울산(2016)', '레베카(2014)', '엘리자벳(2013)']},
 74: {'actor_name': '안두호',
  'masterpiece': ['마우스트랩(2023)', '아가사 - 공주(2022)', '서툰 사람들(2022)']},
 75: {'actor_name': '이연경',
  'masterpiece': ['알로하 나의 엄마들(2022)', '지붕위의 바이올린(2022)', '작은 아씨들(2021)']},
 76: {'actor_name': '최종선',
  'masterpiece': ['영웅(2022)', '지저스 크라이스트 수퍼스타(2020)', '마리 앙투아네트(2019)']},
 77: {'actor_name': '이도국',
  'masterpiece': ['스페셜 라이어(2021)',
   '브라더 포인트(2019)',
   '제5회 무죽 페스티벌 - 브라더 포인트(2019)']},
 78: {'actor_name': '하희라',
  'masterpiece': ['러브레터(2022)', '굿바이걸(2008)', '우리가 애인을 꿈꾸는 이유(2004)']},
 79: {'actor_name': '신문성',
  'masterpiece': ['심청전을 짓다(2022)',
   '76 페스티벌 - 심청전을 짓다(2021)',
   '이카이노의 눈(2020)']},
 80: {'actor_name': '벤',
  'masterpiece': ['벤 콘서트(2022)', '지소울 벤 콘서트 - 창원(2021)', '벤 콘서트(2020)']},
 81: {'actor_name': '김영지',
  'masterpiece': ['남진 콘서트 - 구리(2022)',
   '롤링 21주년 기념공연 vol.3(2016)',
   '라우더스 패밀리 콘서트(2015)']},
 82: {'actor_name': '김홍표',
  'masterpiece': ['대한민국전형적인살인청부업자이야기(2020)', '부장들(2019)', '서울서울서울(2018)']},
 83: {'actor_name': '박성훈',
  'masterpiece': ['알로하 나의 엄마들(2022)', '지붕위의 바이올린(2022)', '작은 아씨들(2021)']},
 84: {'actor_name': '박은영',
  'masterpiece': ['미리내 삼대 - 부천(2023)', '불편한 편의점(2023)', '마이 맘(2015)']},
 85: {'actor_name': '윤승욱',
  'masterpiece': ['신의 손을 빌린 남자 - 안산(2019)',
   '영웅(2017)',
   '에쿠스콘서트콰이어 26회 정기연주회(2015)']},
 86: {'actor_name': 'K2',
  'masterpiece': ['어떤가요 콘서트(2022)',
   'K2 김성면 콘서트(2019)',
   '김성면 & 에메랄드캐슬 콘서트(2018)']},
 87: {'actor_name': '김사은',
  'masterpiece': ['삼총사(2014)', '삼총사(2013)', '사랑은 비를 타고(2011)']},
 88: {'actor_name': '오상은',
  'masterpiece': ['월남스키부대(2014)', '김종욱 찾기(2013)', '캐치 미 이프 유 캔(2012)']},
 89: {'actor_name': '김학준',
  'masterpiece': ['언틸 더 데이(2012)', '언틸 더 데이(2011)', '언틸 더 데이(2011)']},
 90: {'actor_name': '이석',
  'masterpiece': ['지킬 앤 하이드 - 김해(2012)', '부니부니(2010)', '맘마미아 - 부산(2010)']},
 91: {'actor_name': '임재청',
  'masterpiece': ['더 스트레인지(2019)',
   '김구 가다보면 - 인천(2019)',
   '마리아 마리아 - 고양(2014)']},
 92: {'actor_name': '박혜경',
  'masterpiece': ['2017 대구포크페스티벌(2017)',
   '이안 행복드림콘서트(2015)',
   '파크 콘서트 - 성남(2015)']},
 93: {'actor_name': '박시은', 'masterpiece': ['연애시대(2011)', 'JESUS JESUS(2008)']},
 94: {'actor_name': '홍상진',
  'masterpiece': ['마마(2019)', '프린세스 프링(2018)', '갤럭시키즈(2017)']},
 95: {'actor_name': '김도원',
  'masterpiece': ['마리아 마리아(2016)', '락시터(2013)', '락시터(2012)']},
 96: {'actor_name': '박나래',
  'masterpiece': ['박나래의 농염주의보(2019)',
   '슈퍼 디셈버 페스티벌 - 의정부(2018)',
   '원더우먼 페스티벌(2017)']},
 97: {'actor_name': '최윤호',
  'masterpiece': ['십이야(2010)', '테너를 빌려줘 - 부산(2009)', '테너를 빌려줘(2009)']},
 98: {'actor_name': '이강',
  'masterpiece': ['이원복의 먼나라 이웃나라 클래식 콘서트(2014)', '팝콘(2011)', '설공찬전(2010)']},
 99: {'actor_name': '고미경',
  'masterpiece': ['순신(2023)', '신과 함께_저승편(2023)', '금란방(2022)']}}

## 인터파크 캐스팅 배우 불러오기


---

- inter_dic 딕셔너리 구조

{ 작품 제목 : { 배우 : [캐스팅 배우 리스트] } }

In [45]:
def cast_actor(excel):
  inter_actor = pd.read_excel(excel)
  inter_actor = inter_actor[['Title', 'cast_act']]

  # 문자열 형태로 되어 있는 cast_act 열을 리스트화 시켜서 다시 집어 넣을 예정
  inter_actor_cast = inter_actor['cast_act']

  inter_list = []
  for i in range(len(inter_actor)):
    string = inter_actor_cast[i]
    ch_string = string.split(', ')
    inter_list.append(ch_string)

  # Title 기준 딕셔너리화
  inter_dic = inter_actor.set_index('Title').T.to_dict()

  # key: Title, cast_act
  i = 0
  for key, value in inter_dic.items():
    value['cast_act'] = inter_list[i]
    i+=1
  return inter_dic, inter_actor

In [46]:
play_inter_dic, play_inter_actor = cast_actor("../data/raw/playTop77_casting.xlsx")
play_inter_dic

{'연극 〈운빨로맨스〉- 대학로': {'cast_act': ['김세울',
   '문재웅',
   '변가온',
   '한선우',
   '김지후',
   '장은서',
   '조은진',
   '최지선',
   '박병훈',
   '신광희',
   '이주영',
   '신서진',
   '민소현',
   '양혜민',
   '최로아']},
 '(리얼타임 코믹연극) 택시안에서 - 서울': {'cast_act': ['김로언',
   '전청일',
   '한상웅',
   '김나온',
   '한재우',
   '오하성',
   '이채연',
   '김진화',
   '서예선']},
 '(코믹연극) 달동네-부산': {'cast_act': ['조영준',
   '안애린',
   '한서아',
   '류현주',
   '양채은',
   '정유나',
   '곽희규',
   '김영신',
   '신희진',
   '이찬영',
   '이민진',
   '임유림',
   '오현석',
   '양준재',
   '정창운']},
 '10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀': {'cast_act': ['임채민',
   '정지호',
   '문지원',
   '정승지',
   '양시환',
   '황민환',
   '최지환',
   '장진호',
   '박지민',
   '심채아',
   '이주하',
   '정한슬',
   '김동진',
   '함원태',
   '김건하',
   '이선준']},
 '2023 연극 〈친정엄마와 2박 3일〉 - 고양': {'cast_act': ['해당없음']},
 '2시간탈출 졸탄쇼': {'cast_act': ['해당없음']},
 '4D공포연극 〈스위치〉': {'cast_act': ['김상훈',
   '엄민욱',
   '전재진',
   '이창주',
   '최하은',
   '정재희',
   '최유경',
   '김시원',
   '김정규',
   '나준영',
   '함우주',
   '김창우',
   '윤수아',
   '김단하',
   '박애림']},
 '★평점9.5★ 코미디의맛/쇼미더퍼니': {'cast_act': ['해당없음']},
 '공포연극 조각': {'cast_act': ['김주영',
   '이승원',
   '하진성',
   '이동규',
   '강영수',
   '김진현',
   '김훈민',
   '유승현',
   '김태린',
   '김하진',
   '장솔하',
   '유혜나']},
 '공포연극 ［자취］': {'cast_act': ['엄현호',
   '김주훤',
   '주귀룡',
   '홍세나',
   '김태린',
   '윤서정',
   '김보근',
   '최준식']},
 '괴물B': {'cast_act': ['이상홍',
   '이승혁',
   '최지혜',
   '지춘성',
   '이영주',
   '이은정',
   '조성현',
   '이두성',
   '류정문',
   '강연주']},
 '국민 코믹 연극 〈오백에삼십〉 - 대학로 세우아트센터 1관': {'cast_act': ['이세정',
   '이현정',
   '배상규',
   '도준영',
   '이다빈',
   '박지원',
   '이제민',
   '김단우',
   '임수영',
   '전세정',
   '정유진',
   '김솔',
   '정재훈',
   '차경훈',
   '전지환',
   '정아영']},
 '대학로 1위 연극 〈쉬어매드니스〉': {'cast_act': ['임정균',
   '김태성',
   '이승복',
   '석민주',
   '리재',
   '노다윗',
   '백재민',
   '김채율',
   '이른봄',
   '고동균',
   '김태환',
   '이규동',
   '손지완']},
 '러브 앤 인포메이션': {'cast_act': ['해당없음']},
 '메이드 인 제인': {'cast_act': ['이승우',
   '이상진',
   '안태준',
   '김태성',
   '정수현',
   '김정훈',
   '이채원',
   '손민준',
   '안진효',
   '조태영',
   '채승병',
   '전우용']},
 '뮤직드라마 〈불편한 편의점〉': {'cast_act': ['장우진',
   '김동박',
   '이강혁',
   '박은영',
   '조영임',
   '문상희',
   '정예지',
   '정이수',
   '서지영',
   '한윤서',
   '홍가경',
   '김은지',
   '김준희',
   '김윤희',
   '김서준',
   '차미연',
   '장희재',
   '임혜진',
   '지상록',
   '윤선근']},
 '연극 〈굿닥터〉': {'cast_act': ['김수현',
   '김귀선',
   '정원조',
   '문상희',
   '강지원',
   '김영경',
   '이승우',
   '박현민',
   '정다정']},
 '연극 〈극적인 하룻밤〉': {'cast_act': ['허욱',
   '김번영',
   '임현준',
   '차도윤',
   '이시원',
   '박수야',
   '공다임',
   '민하람']},
 '연극 〈기형도 플레이〉': {'cast_act': ['최덕문',
   '우현주',
   '이석준',
   '박호산',
   '이창훈',
   '이동하',
   '이은',
   '김세영',
   '김승은']},
 '연극 〈나의PS파트너〉': {'cast_act': ['김민주',
   '전승현',
   '이탁호',
   '고예현',
   '석민주',
   '홍채현',
   '최영광',
   '좌정우',
   '차형은',
   '정현진',
   '백송이',
   '이혜주']},
 '연극 〈바닷마을 다이어리〉': {'cast_act': ['박하선',
   '한혜진',
   '서예화',
   '임수향',
   '강해진',
   '류이재',
   '설가은',
   '유나',
   '오한결',
   '이윤서',
   '이정미',
   '이강욱']},
 '연극 〈뷰티풀라이프〉': {'cast_act': ['조준',
   '김진우',
   '김원진',
   '김진호',
   '정경식',
   '김사희',
   '박세영',
   '권순미',
   '강민주',
   '김다정',
   '김효진',
   '강보라']},
 '연극 〈수상한흥신소〉': {'cast_act': ['해당없음']},
 '연극 〈쉬어 매드니스(Shear Madness)〉 - 군포': {'cast_act': ['해당없음']},
 '연극 〈슈만〉': {'cast_act': ['박상민',
   '윤서현',
   '원기준',
   '이일화',
   '정재은',
   '채시현',
   '장도윤',
   '최성민',
   '최현상']},
 '연극 〈카페 쥬에네스〉': {'cast_act': ['차용학',
   '최정헌',
   '랑연',
   '조윤영',
   '이봉준',
   '지호림',
   '장서연',
   '신가은',
   '김다흰',
   '오의식',
   '박은석']},
 '연극 너의 목소리가 들려': {'cast_act': ['고영빈',
   '진승욱',
   '김정원',
   '피설아',
   '아인',
   '박선영',
   '김하늘',
   '윤계열',
   '박건엽',
   '정성화',
   '김일강',
   '배설하',
   '안예슬',
   '김예은',
   '조하연']},
 '연극 죽여주는 이야기': {'cast_act': ['남경화', '노진욱', '이연승', '최다운', '조웅희']},
 '연극 한뼘사이': {'cast_act': ['윤주희',
   '강단비',
   '주하영',
   '유이주',
   '박정윤',
   '최하은',
   '김시윤',
   '김현지',
   '김종훈',
   '정태영',
   '서도운',
   '구도진',
   '홍대권',
   '김도연',
   '성엽',
   '이수영',
   '이슬기',
   '고민지',
   '남은지',
   '문아연']},
 '연극 핫식스': {'cast_act': ['이대우',
   '정회형',
   '김호준',
   '김예지',
   '송다영',
   '김은수',
   '임종철',
   '김동섭',
   '김정원',
   '전상혁']},
 '연극〈늘근도둑이야기〉': {'cast_act': ['노진원',
   '전재형',
   '박철민',
   '태항호',
   '김상묵',
   '주우성',
   '유일한',
   '이호연',
   '안태영']},
 '이머시브씨어터 카지노': {'cast_act': ['안지현',
   '남지현',
   '문수민',
   '오자송',
   '최지우',
   '김유리',
   '박상혁',
   '장영웅',
   '박서연',
   '안예은',
   '김태균',
   '담우',
   '한민우',
   '박철연',
   '유지현',
   '김혜미',
   '최민석',
   '최규식',
   '이지현']},
 '제6회 1번출구 연극제 〈월드다방〉, 〈#정답을작성해주세요〉, 〈순례네 국밥〉': {'cast_act': ['기은수',
   '이태현',
   '유민주',
   '정진아',
   '문유란',
   '김호준',
   '유의봉']},
 '좀비연극 오마이갓': {'cast_act': ['이진욱',
   '한석희',
   '조하연',
   '이지혜',
   '김아율',
   '예윤주',
   '박건엽',
   '정성화',
   '고영빈']},
 '진짜나쁜소녀': {'cast_act': ['윤지원',
   '강현아',
   '이소연',
   '한이올',
   '조정원',
   '이유진',
   '남은지',
   '민재완',
   '문상준',
   '한상민',
   '정대경',
   '박소정',
   '정수미',
   '황승아',
   '김은찬',
   '장한길',
   '김민석']},
 '코미디 연극〈딜리버리〉': {'cast_act': ['정영성',
   '장경진',
   '김준혜',
   '안세미',
   '이수현',
   '이세진',
   '채다솜',
   '배윤정',
   '성희진',
   '안현',
   '신용빈',
   '서형덕']},
 '코믹감동 휴먼판타지 연극 〈2호선 세입자〉': {'cast_act': ['서해든',
   '민채우',
   '정은규',
   '임지우',
   '전지후',
   '박경진',
   '박호진',
   '최상태',
   '성보람',
   '이우진',
   '김은정',
   '허솔빈',
   '유우헌',
   '정진혁',
   '김건호']},
 '행오버': {'cast_act': ['최선량',
   '정현규',
   '조영광',
   '신재명',
   '손준표',
   '윤건웅',
   '최창빈',
   '김민우',
   '이도희',
   '이유진',
   '정하민',
   '이정은',
   '조병진',
   '유형욱',
   '김상일',
   '권희대',
   '유민주',
   '서지현',
   '채빈',
   '김민서']},
 '［2023 SPAF］ SPAF 연극 패키지': {'cast_act': ['해당없음']},
 '［2023 SPAF］ SPAF 하마티아 3부작 패키지': {'cast_act': ['해당없음']},
 '［2023 SPAF］ 거인아트랩 〈인.투〉': {'cast_act': ['해당없음']},
 '［2023 SPAF］ 구자하/캄포 〈하마티아 3부작: 롤링 앤 롤링〉': {'cast_act': ['해당없음']},
 '［2023 SPAF］ 구자하/캄포 〈하마티아 3부작: 쿠쿠〉': {'cast_act': ['해당없음']},
 '［2023 SPAF］ 구자하/캄포 〈하마티아 3부작: 한국 연극의 역사〉': {'cast_act': ['해당없음']},
 '［2023 SPAF］ 극단 골목길 〈이장〉': {'cast_act': ['해당없음']},
 '［2023 SPAF］ 극단 돌파구 〈지상의 여자들〉': {'cast_act': ['김시영',
   '김정호',
   '안병식',
   '김민하',
   '조어진',
   '윤미경',
   '한지수',
   '이진경']},
 '［2023 SPAF］ 데드센터 〈베케트의 방〉': {'cast_act': ['해당없음']},
 '［2023 SPAF］ 연극연습 프로젝트 〈연극연습3. 극작 연습-물고기로 죽기〉': {'cast_act': ['해당없음']},
 '［2023 SPAF］ 작당모의 〈싸움의 기술, 〈졸〉_2.0〉': {'cast_act': ['해당없음']},
 '［2023 SPAF］ 지연X전환 〈에너지_보이지 않는 언어〉': {'cast_act': ['해당없음']},
 '［2023 SPAF］ 파이브 아트 센터 〈노셔널 히스토리〉': {'cast_act': ['해당없음']},
 '［2023_셀러브리티 명품 로코］연극 이프온리 크리스마스특별 공연 - 대학로': {'cast_act': ['해당없음']},
 '［2023’셀러브리티 로코연극］러브액츄얼리 첫번째사연_크리스마스 특별공연 - 부산': {'cast_act': ['해당없음']},
 '［서울 대학로］연극 라면': {'cast_act': ['김기정',
   '이시운',
   '강종현',
   '이인규',
   '이윤경',
   '김민지',
   '박혜선',
   '민유리',
   '박승훈',
   '황요셉',
   '김지욱',
   '신광민',
   '고연경',
   '엄선영',
   '유채빈',
   '권현진',
   '박한솔',
   '임호성',
   '정지원',
   '최흥일']},
 '［연극 on stage］ 99% - 화성': {'cast_act': ['해당없음']},
 '［연극 on stage］ 띨뿌리 - 화성': {'cast_act': ['해당없음']},
 '［연애하기 좋은 날 : 당근거래］ - 전주': {'cast_act': ['해당없음']},
 '［장애인 선예매］ 러브 앤 인포메이션': {'cast_act': ['해당없음']},
 '대학로 청소년연극 〈사춘기메들리〉': {'cast_act': ['한규혁',
   '현동석',
   '김예나',
   '김태린',
   '최이슬',
   '박은선',
   '이재연',
   '양철진',
   '홍대교',
   '손형민',
   '최영준']},
 '로맨틱코미디 〈슬기로운 신혼생활〉': {'cast_act': ['오세영',
   '정대경',
   '김은지',
   '이슬기',
   '한재우',
   '서동현',
   '김세나',
   '이재희',
   '송민주',
   '이동규',
   '이종훈',
   '황수빈']},
 '공포스릴러연극〈두여자〉- 대구': {'cast_act': ['김미영',
   '김린아',
   '이다은',
   '엄영실',
   '이상아',
   '임성희',
   '이도윤',
   '최승환',
   '문다현',
   '박수정',
   '박다율',
   '장예림',
   '남채원',
   '김소희',
   '이루리',
   '서가흔',
   '김병현',
   '여동현',
   '이태민',
   '윤동주']},
 '모든 날 모든 순간': {'cast_act': ['해당없음']},
 '나의 장례식에 와줘': {'cast_act': ['해당없음']},
 '3대가 웃고 우는 연극 〈염쟁이 유씨〉': {'cast_act': ['해당없음']},
 '그곳에 있었다': {'cast_act': ['김현서', '정지원', '조민솔', '호천', '강우람', '김진현']}}

In [47]:
play_inter_actor

,Title,cast_act
0,연극 〈운빨로맨스〉- 대학로,"김세울, 문재웅, 변가온, 한선우, 김지후, 장은서, 조은진, 최지선, 박병훈, 신..."
1,(리얼타임 코믹연극) 택시안에서 - 서울,"김로언, 전청일, 한상웅, 김나온, 한재우, 오하성, 이채연, 김진화, 서예선"
2,(코믹연극) 달동네-부산,"조영준, 안애린, 한서아, 류현주, 양채은, 정유나, 곽희규, 김영신, 신희진, 이..."
3,10년 연속 1위 연극〈옥탑방고양이〉- 틴틴홀,"임채민, 정지호, 문지원, 정승지, 양시환, 황민환, 최지환, 장진호, 박지민, 심..."
4,2023 연극 〈친정엄마와 2박 3일〉 - 고양,해당없음
...,...,...
60,공포스릴러연극〈두여자〉- 대구,"김미영, 김린아, 이다은, 엄영실, 이상아, 임성희, 이도윤, 최승환, 문다현, 박..."
61,모든 날 모든 순간,해당없음
62,나의 장례식에 와줘,해당없음
63,3대가 웃고 우는 연극 〈염쟁이 유씨〉,해당없음
64,그곳에 있었다,"김현서, 정지원, 조민솔, 호천, 강우람, 김진현"

In [48]:
mus_inter_dic, mus_inter_actor = cast_actor("/content/drive/MyDrive/캡스톤/데이터/뮤지컬/musicalTop77_casting.xlsx")
mus_inter_dic

{'2023 〈스웨그에이지 : 외쳐, 조선〉 - 인천': {'cast_act': ['해당없음']},
 '2023 창작뮤지컬어워드 NEXT': {'cast_act': ['해당없음']},
 '2023 최현우 Answer - 성남': {'cast_act': ['최현우']},
 '2023~24 최현우 Answer': {'cast_act': ['최현우']},
 '2023송승환의 오리지널 난타(대전)': {'cast_act': ['해당없음']},
 '2024 최현우 Answer - 청주': {'cast_act': ['최현우']},
 '2023 매직쇼〈최현우의 미스틱커스〉 - 평택': {'cast_act': ['해당없음']},
 '국립창극단 〈패왕별희〉': {'cast_act': ['해당없음']},
 '난타(NANTA) - 명동공연': {'cast_act': ['해당없음']},
 '넌버벌 코미디 〈옹알스〉': {'cast_act': ['조수원',
   '조준우',
   '채경선',
   '최기섭',
   '하박',
   '이경섭',
   '최진영']},
 '더 맨 얼라이브 〈초이스〉': {'cast_act': ['이유청', '강청광', '김준석', '김성길', '박휘범', '강태욱']},
 '동구문화체육센터 뮤지컬 〈앤 ANNE〉 - 인천': {'cast_act': ['천우주']},
 '라면에 파송송': {'cast_act': ['김재선', '김슬기', '김태경']},
 '러스트(RUST) - 전주': {'cast_act': ['해당없음']},
 '런던레코드': {'cast_act': ['이채원', '해리 벤자민']},
 '뮤지컬 〈22년 2개월〉': {'cast_act': ['유승현',
   '양지원',
   '이재환',
   '최수진',
   '강혜인',
   '홍나현',
   '유성재',
   '안창용',
   '정호준',
   '이현재',
   '박세훈',
   '성재',
   '정종환',
   '박상선',
   '신요셉']},
 '뮤지컬 〈곤 투모로우〉': {'cast_act': ['강필석',
   '최재웅',
   '고훈정',
   '조형균',
   '김재범',
   '신성민',
   '백형훈',
   '윤소호',
   '고영빈',
   '박영수',
   '김준수',
   '김태한',
   '임별',
   '김민철',
   '차형도']},
 '뮤지컬 더데빌 : 에덴 (Musical THE DEVIL : EDEN)': {'cast_act': ['김찬호',
   '조형균',
   '김준영',
   '정동화',
   '박규원',
   '백인태',
   '여은',
   '이지연',
   '이재림',
   '이기현',
   '반정모',
   '김우성',
   '이효정',
   '김명지']},
 '뮤지컬 〈구텐버그〉': {'cast_act': ['정민', '최호승', '정욱진', '기세중', '선한국', '정휘']},
 '뮤지컬 〈그날들〉 10주년 기념 공연 - 대전': {'cast_act': ['유준상',
   '오만석',
   '엄기준',
   '이건명',
   '오종혁',
   '김건우',
   '김지현',
   '효은',
   '고창석',
   '서현철',
   '이정열',
   '이진희',
   '김보정',
   '최지호',
   '김산호',
   '손우민',
   '박정표',
   '곽나윤',
   '이정화',
   '김석영']},
 '뮤지컬 〈김종욱 찾기〉': {'cast_act': ['김시울',
   '이재형',
   '정현준',
   '홍차민',
   '김건영',
   '김소정',
   '김재희',
   '배다솜',
   '서지우',
   '심설빈',
   '문준혁',
   '박형석',
   '안지후',
   '윤병일',
   '이광진']},
 '뮤지컬 〈레미제라블〉 - 부산': {'cast_act': ['민우혁',
   '최재림',
   '김우형',
   '카이',
   '조정은',
   '린아',
   '임기홍',
   '육현욱',
   '박준면',
   '김영주',
   '김성식',
   '김진욱',
   '김수하',
   '루미나',
   '윤은오',
   '김경록',
   '이상아',
   '류인아',
   '이형준',
   '석현준']},
 '뮤지컬 〈레베카〉 10주년 기념공연': {'cast_act': ['류정한',
   '민영기',
   '에녹',
   '테이',
   '신영숙',
   '옥주현',
   '리사',
   '장은아',
   '김보경',
   '이지혜',
   '이지수',
   '웬디',
   '윤석원',
   '임정모',
   '윤사봉',
   '김지선',
   '이은율',
   '홍기주',
   '제병진',
   '김순택']},
 '뮤지컬 〈렛미플라이〉': {'cast_act': ['김태한',
   '김도빈',
   '이형훈',
   '방진의',
   '윤공주',
   '최수진',
   '안지환',
   '박보검',
   '신재범',
   '나하나',
   '홍지희',
   '임예진']},
 '뮤지컬 〈마리 퀴리〉': {'cast_act': ['김소현',
   '이정화',
   '유리아',
   '강혜인',
   '효은',
   '최지혜',
   '박영수',
   '김지철',
   '임별',
   '김찬호',
   '양승리',
   '안재영',
   '민정아',
   '옥경민',
   '이찬렬',
   '홍유정',
   '유낙원',
   '송상훈',
   '조배근',
   '윤수아']},
 '뮤지컬 〈맘마미아!〉 - 김해': {'cast_act': ['최정원',
   '신영숙',
   '김환희',
   '최태이',
   '김영주',
   '홍지민',
   '박준면',
   '김경선',
   '장현성',
   '김정민',
   '이현우',
   '민영기',
   '김진수',
   '송일국']},
 '뮤지컬 〈렌트〉': {'cast_act': ['백형훈',
   '장지후',
   '정원영',
   '배두훈',
   '김환희',
   '이지연',
   '전나영',
   '김수연',
   '정다희',
   '배수정',
   '김호영',
   '조권',
   '윤형렬',
   '임정모',
   '구준모']},
 '뮤지컬 〈멤피스〉': {'cast_act': ['박강현',
   '고은성',
   '이창섭',
   '정선아',
   '유리아',
   '손승연',
   '최민철',
   '심재현',
   '최정원',
   '류수화',
   '이종문',
   '유효진',
   '조성린',
   '이준용']},
 '뮤지컬 〈문스토리〉': {'cast_act': ['정상윤',
   '성연',
   '김진욱',
   '김준호',
   '소정화',
   '박새힘',
   '주다온',
   '장보람',
   '강찬',
   '김리현',
   '김지웅',
   '전민지',
   '조영화',
   '표바하',
   '이채원']},
 '뮤지컬 〈빨래〉': {'cast_act': ['해당없음']},
 '쇼 뮤지컬 〈시스터즈 (SheStars!)〉': {'cast_act': ['유연',
   '신의정',
   '선민',
   '황성현',
   '김려원',
   '하유진',
   '정유지',
   '이예은',
   '이서영',
   '정연',
   '홍서영']},
 '뮤지컬 〈비더슈탄트〉': {'cast_act': ['송유택',
   '안지환',
   '황순종',
   '정백선',
   '김바다',
   '김지온',
   '동현',
   '이진우',
   '김이담',
   '손지환',
   '김도현',
   '김방언',
   '이태이',
   '김민강',
   '박선영',
   '곽다인',
   '정선기',
   '한정훈',
   '이한솔',
   '류동휘']},
 '뮤지컬 〈사칠〉': {'cast_act': ['진태화', '변희상', '김찬종', '이종석', '박정혁', '홍기범']},
 '뮤지컬 〈셜록홈즈 : 앤더슨가의 비밀〉': {'cast_act': ['송용진',
   '김준현',
   '오종혁',
   '구민진',
   '방진의',
   '최우리',
   '조성윤',
   '김우진',
   '이석준',
   '정명은',
   '린지',
   '박새힘',
   '조남희',
   '김수정',
   '양희웅']},
 '뮤지컬 〈쇼맨_어느 독재자의 네 번째 대역배우〉': {'cast_act': ['윤나무',
   '신성민',
   '강기둥',
   '정운선',
   '박란주',
   '이수빈',
   '안창용',
   '장민수',
   '이현진',
   '김연진',
   '김대웅',
   '장두환',
   '이다정',
   '전성혜']},
 '뮤지컬 〈스모크〉': {'cast_act': ['김재범',
   '정민',
   '김경수',
   '박정원',
   '강찬',
   '손유동',
   '홍승안',
   '김지유',
   '김청아',
   '장보람',
   '최지혜']},
 '뮤지컬 〈스토리오브마이라이프〉': {'cast_act': ['최재웅', '이창용', '조성윤', '김종구', '정욱진', '신재범']},
 '뮤지컬 〈삼총사〉': {'cast_act': ['박장현',
   '후이',
   '렌',
   '유태양',
   '민규',
   '이건명',
   '최대철',
   '김형균',
   '김신의',
   '김현수',
   '신인선',
   '최오식',
   '장대웅',
   '조순창',
   '안유진',
   '류비',
   '이윤하',
   '지수연',
   '서범석',
   '강동우']},
 '뮤지컬 〈오페라의 유령〉 - 서울': {'cast_act': ['조승우',
   '최재림',
   '김주택',
   '전동석',
   '손지수',
   '송은혜',
   '송원근',
   '황건하',
   '윤영석',
   '이상준',
   '이지영',
   '한보라',
   '박회림',
   '김아선']},
 '뮤지컬 〈위윌락유〉': {'cast_act': ['곽동현',
   '박현규',
   '박준희',
   '동명',
   '연호',
   '이소정',
   '장연경',
   '정예인',
   '한유란',
   '황한나',
   '신현묵',
   '백승렬',
   '하웅환',
   '황인욱',
   '이재웅',
   '박신형',
   '유정우',
   '엄채윤',
   '박찬우',
   '장준환']},
 '뮤지컬 〈이토록 보통의〉': {'cast_act': ['최연우', '김예원', '강지혜', '임준혁', '정휘', '황휘']},
 '뮤지컬 〈인사이드 윌리엄〉 2023': {'cast_act': ['원종환',
   '최호중',
   '김아영',
   '임준혁',
   '임진섭',
   '정지우',
   '이아름솔',
   '김수연',
   '김이후',
   '주민진',
   '최민우',
   '유태율']},
 '뮤지컬 〈칠칠〉': {'cast_act': ['박규원',
   '안재영',
   '김준영',
   '조상웅',
   '송유택',
   '김현진',
   '홍기범',
   '김주호',
   '이시안']},
 '뮤지컬 〈컴프롬어웨이〉': {'cast_act': ['남경주',
   '서현철',
   '최정원',
   '이정열',
   '고창석',
   '정영주',
   '신영숙',
   '지현준',
   '최현주',
   '심재현',
   '장예원',
   '차지연',
   '김아영',
   '이정수',
   '주민진',
   '이현진',
   '정영아',
   '신창주',
   '김승용',
   '김지혜']},
 '뮤지컬 〈킴즈〉': {'cast_act': ['강성진',
   '김재만',
   '구옥분',
   '김사라',
   '표혜미',
   '정아인',
   '니엘',
   '김지범']},
 '뮤지컬 〈타오르는 어둠 속에서〉': {'cast_act': ['박정원',
   '양희준',
   '노윤',
   '한재아',
   '주다온',
   '정재환',
   '홍승안',
   '윤재호',
   '이영미',
   '문혜원',
   '이진혁',
   '황성재',
   '전해주',
   '선유하',
   '조민호',
   '박주혁',
   '김도원',
   '이지우',
   '김하연',
   '김동준']},
 '뮤지컬 〈판〉': {'cast_act': ['김지철',
   '문성일',
   '현석준',
   '원종환',
   '김지훈',
   '김국희',
   '박은미',
   '김지혜',
   '박란주',
   '송영미',
   '류경환',
   '김효성',
   '임소라',
   '서원',
   '최영석']},
 '뮤지컬 〈프리다〉': {'cast_act': ['김소향',
   '알리',
   '김히어라',
   '전수미',
   '리사',
   '스테파니',
   '임정희',
   '정영아',
   '이아름솔',
   '최서연',
   '박시인',
   '허혜진',
   '황우림']},
 '뮤지컬 〈후크〉': {'cast_act': ['손유동',
   '박상혁',
   '최호승',
   '김도빈',
   '동현',
   '김지온',
   '정우연',
   '김주연',
   '최미소']},
 '뮤지컬 드라큘라 (Dracula：The Musical)': {'cast_act': ['김준수',
   '전동석',
   '신성록',
   '임혜영',
   '정선아',
   '아이비',
   '손준호',
   '박은석',
   '진태화',
   '임준혁',
   '이예은',
   '최서연',
   '김도현',
   '김도하']},
 '뮤지컬 〈블랙메리포핀스〉': {'cast_act': ['김도빈',
   '김대현',
   '양승리',
   '윤승우',
   '황휘',
   '최재웅',
   '노윤',
   '김 수',
   '김서연',
   '이정화',
   '김서환',
   '김기택',
   '이준우',
   '홍성원',
   '임강희',
   '홍륜희',
   '전경수',
   '임찬민',
   '강연정',
   '송상은']},
 '뮤지컬 ＇벤허＇': {'cast_act': ['박은태',
   '신성록',
   '규현',
   '이지훈',
   '박민성',
   '서경수',
   '윤공주',
   '이정화',
   '최지혜',
   '이정열',
   '홍경수',
   '한지연',
   '류수화',
   '장혜린',
   '문은수',
   '김대종',
   '이희정',
   '문성혁',
   '공동환',
   '조용휘']},
 '어른이 뮤지컬 〈난쟁이들〉': {'cast_act': ['유현석',
   '기세중',
   '윤석호',
   '조풍래',
   '류제윤',
   '장민수',
   '정우연',
   '박슬기',
   '한보라',
   '안상은',
   '이경욱',
   '선한국',
   '서동진',
   '남민우',
   '주민우',
   '이건희']},
 '이은결 ［더 일루션 - 마스터피스］': {'cast_act': ['이은결']},
 '창작가무극 〈순신〉': {'cast_act': ['형남희',
   '최인형',
   '이자람',
   '윤제원',
   '권성찬',
   '송문선',
   '고미경',
   '금승훈',
   '김백현',
   '김용한',
   '유경아',
   '정지만',
   '박재은',
   '정유희',
   '김건혜',
   '이영규',
   '이홍모',
   '조근래',
   '최병규',
   '이종한']},
 '태양의서커스 〈루치아〉': {'cast_act': ['해당없음']},
 '［제주］뉴미디어뮤지컬(노형수퍼마켙)': {'cast_act': ['해당없음']},
 '［청주,세종］뮤지컬 빌의구둣방': {'cast_act': ['허선우', '박선령', '조재문', '이혜림', '김지원']},
 '뮤지컬 〈왓 이프〉': {'cast_act': ['유소나',
   '이정휘',
   '박하은',
   '정세지',
   '김하준',
   '박태준',
   '최우성',
   '표혜미',
   '전소민',
   '김진솔',
   '성민범',
   '윤진웅',
   '권현욱',
   '장경원',
   '김정혁']},
 '써니텐': {'cast_act': ['임재혁', '렉스', '한수인', '최하선', '배기성', '권도윤']},
 '뮤지컬 썸데이': {'cast_act': ['김여진',
   '서찬양',
   '김아름',
   '이채림',
   '구문회',
   '이제성',
   '김선오',
   '윤동환',
   '박소진',
   '조윤진',
   '김태린',
   '정영원',
   '강민석',
   '김호창',
   '이재현',
   '정지환',
   '최이재',
   '박소영',
   '엄대',
   '최미정']},
 '뮤지컬 프리즌': {'cast_act': ['손동진',
   '최승환',
   '홍차민',
   '안중현',
   '김세훈',
   '신연우',
   '하준석',
   '이강오',
   '김동훈',
   '추정민',
   '조웅희',
   '윤선우',
   '한미래',
   '장수빈',
   '강유진']},
 '뮤직드라마 당신만이': {'cast_act': ['장인혁',
   '박민승',
   '박준성',
   '이일진',
   '손예슬',
   '이민지',
   '박세웅',
   '차은진',
   '권성민',
   '이경수']},
 '뮤지컬 〈투모로우 모닝〉': {'cast_act': ['렉스',
   '정현준',
   '천관우',
   '김안젤라',
   '박혜원',
   '한수민',
   '문준혁',
   '임창민',
   '오태후',
   '이미경',
   '김소정',
   '김솔']},
 '뮤지컬 스크루테이프의 편지': {'cast_act': ['해당없음']}}

In [49]:
mus_inter_actor

,Title,cast_act
0,"2023 〈스웨그에이지 : 외쳐, 조선〉 - 인천",해당없음
1,2023 창작뮤지컬어워드 NEXT,해당없음
2,2023 최현우 Answer - 성남,최현우
3,2023~24 최현우 Answer,최현우
4,2023송승환의 오리지널 난타(대전),해당없음
...,...,...
60,뮤지컬 썸데이,"김여진, 서찬양, 김아름, 이채림, 구문회, 이제성, 김선오, 윤동환, 박소진, 조..."
61,뮤지컬 프리즌,"손동진, 최승환, 홍차민, 안중현, 김세훈, 신연우, 하준석, 이강오, 김동훈, 추..."
62,뮤직드라마 당신만이,"장인혁, 박민승, 박준성, 이일진, 손예슬, 이민지, 박세웅, 차은진, 권성민, 이경수"
63,뮤지컬 〈투모로우 모닝〉,"렉스, 정현준, 천관우, 김안젤라, 박혜원, 한수민, 문준혁, 임창민, 오태후, 이..."
64,뮤지컬 스크루테이프의 편지,해당없음

## 배우명 비교
* actor_dic : playDB 랭킹별 최근공연 딕셔너리
* inter_dic : 인터파크 작품별 캐스팅 배우 딕셔너리


---

> 찾는 배우 이름(인터파크 캐스팅 배우)이 actor_dic에 있을 경우, 해당 배우의 랭킹 도출

→ 해당 배우의 랭킹(인덱스)를 활용하여 최근 공연 리스트 불러오기

→ 최근 공연 리스트와 현재 찾는 배우의 공연 이름 비교

* 문제: 배우 최근 공연과 인터파크 제목이 다르므로 배우의 최근 공연을 " - "으로 split 한 후, 인터파크 제목.find(최근 공연) 하는 함수를 짜면 될 듯

In [50]:
# 프로토타입 (이건 playDB 동명이인이 있을 경우)
res = []
for key, value in play_actor_dic.items():
  if ('최성희'.find(value['actor_name']) > -1):
    res.append(key)
res

[0]

In [51]:
# 배우 이름 찾기 (랭킹 도출) 함수
def find_value(dictionary, finding_value):
    for key, value in dictionary.items():
        if (finding_value.find(value['actor_name']) > -1):
            return key

In [52]:
def search_actor(inter_dic, actor_dic):
  actor_mp = {}
  i = 0
  for key1, value1 in inter_dic.items():
      for name in value1['cast_act']:
          index = find_value(actor_dic, name)
          if index is not None:
              for key2, value2 in actor_dic.items():
                  if key2 == index:
                    # 여기서부터 짰음
                      recent_performances = value2['masterpiece']

                      for title in recent_performances:
                        title = title.split('(')
                        title = title[0]

                        # 인터파크 제목에서 최근 공연을 찾음
                        temp = key1.find(title)
                        if temp > -1:
                          print(f"배우 {name}의 최근 공연 '{key1}'이 인터파크 제목에 포함됨.")
                          actor_mp[i] = {'actor' : name, 'Title' : key1}
                          i+=1
  return actor_mp

### 밑 반복문 구조 설명

* for key1, value1 in inter_dic.items(): 인터파크 캐스팅 배우 딕셔너리를 key, value로 쪼갬

* for name in value1['cast_act']: 작품별 캐스팅배우의 이름 기준으로 반복

* index = find_value(actor_dic, name) : 배우 이름 찾기 함수로 배우 찾아서 랭킹을 인덱스에 저장

* if (index!=None): 인덱스가 None이면 랭킹에 없다는 뜻

* for key2, value2 in actor_dic.items(): 배우 랭킹 딕셔너리를 key, value로 쪼갬
        
* if (value2['index'] == index): 랭킹(인덱스)이 같다면

* print(value2['masterpiece']) : 작품명 출력 (여기부터 바꾸면 될 듯)



---


* 연극 배우

In [53]:
PSA = search_actor(play_inter_dic, play_actor_dic)

배우 박은영의 최근 공연 '뮤직드라마 〈불편한 편의점〉'이 인터파크 제목에 포함됨.
배우 최덕문의 최근 공연 '연극 〈기형도 플레이〉'이 인터파크 제목에 포함됨.
배우 박호산의 최근 공연 '연극 〈기형도 플레이〉'이 인터파크 제목에 포함됨.

In [54]:
MSA = search_actor(mus_inter_dic, mus_actor_dic)

배우 이재환의 최근 공연 '뮤지컬 〈22년 2개월〉'이 인터파크 제목에 포함됨.
배우 정민의 최근 공연 '뮤지컬 〈구텐버그〉'이 인터파크 제목에 포함됨.
배우 김지현의 최근 공연 '뮤지컬 〈그날들〉 10주년 기념 공연 - 대전'이 인터파크 제목에 포함됨.
배우 린아의 최근 공연 '뮤지컬 〈레미제라블〉 - 부산'이 인터파크 제목에 포함됨.
배우 정민의 최근 공연 '뮤지컬 〈스모크〉'이 인터파크 제목에 포함됨.
배우 김신의의 최근 공연 '뮤지컬 〈삼총사〉'이 인터파크 제목에 포함됨.
배우 김신의의 최근 공연 '뮤지컬 〈삼총사〉'이 인터파크 제목에 포함됨.
배우 송원근의 최근 공연 '뮤지컬 〈오페라의 유령〉 - 서울'이 인터파크 제목에 포함됨.
배우 김아선의 최근 공연 '뮤지컬 〈오페라의 유령〉 - 서울'이 인터파크 제목에 포함됨.
배우 차지연의 최근 공연 '뮤지컬 〈컴프롬어웨이〉'이 인터파크 제목에 포함됨.
배우 문혜원의 최근 공연 '뮤지컬 〈타오르는 어둠 속에서〉'이 인터파크 제목에 포함됨.
배우 송상은의 최근 공연 '뮤지컬 〈블랙메리포핀스〉'이 인터파크 제목에 포함됨.
배우 규현의 최근 공연 '뮤지컬 ＇벤허＇'이 인터파크 제목에 포함됨.
배우 이희정의 최근 공연 '뮤지컬 ＇벤허＇'이 인터파크 제목에 포함됨.
배우 이자람의 최근 공연 '창작가무극 〈순신〉'이 인터파크 제목에 포함됨.
배우 고미경의 최근 공연 '창작가무극 〈순신〉'이 인터파크 제목에 포함됨.

In [55]:
for key1, value1 in play_inter_dic.items():
    for name in value1['cast_act']:
        index = find_value(play_actor_dic, name)
        if index is not None:
            for key2, value2 in play_actor_dic.items():
                if key2 == index:
                  # 여기서부터 짰음
                    recent_performances = value2['masterpiece']

                    for title in recent_performances:
                      title = title.split('(')
                      title = title[0]

                      # 인터파크 제목에서 최근 공연을 찾음
                      temp = key1.find(title)
                      if temp > -1:
                        print(f"배우 {name}의 최근 공연 '{key1}'이 인터파크 제목에 포함됨.")

    #print(name + " : " + str(index))

배우 박은영의 최근 공연 '뮤직드라마 〈불편한 편의점〉'이 인터파크 제목에 포함됨.
배우 최덕문의 최근 공연 '연극 〈기형도 플레이〉'이 인터파크 제목에 포함됨.
배우 박호산의 최근 공연 '연극 〈기형도 플레이〉'이 인터파크 제목에 포함됨.



---

* 뮤지컬 배우

In [56]:
for key1, value1 in mus_inter_dic.items():
    for name in value1['cast_act']:
        index = find_value(mus_actor_dic, name)
        if index is not None:
            for key2, value2 in mus_actor_dic.items():
                if key2 == index:
                  # 여기서부터 짰음
                    recent_performances = value2['masterpiece']

                    for title in recent_performances:
                      title = title.split('(')
                      title = title[0]

                      # 인터파크 제목에서 최근 공연을 찾음
                      temp = key1.find(title)
                      if temp > -1:
                        print(f"배우 {name}의 최근 공연 '{key1}'이 인터파크 제목에 포함됨.")

    #print(name + " : " + str(index))

배우 이재환의 최근 공연 '뮤지컬 〈22년 2개월〉'이 인터파크 제목에 포함됨.
배우 정민의 최근 공연 '뮤지컬 〈구텐버그〉'이 인터파크 제목에 포함됨.
배우 김지현의 최근 공연 '뮤지컬 〈그날들〉 10주년 기념 공연 - 대전'이 인터파크 제목에 포함됨.
배우 린아의 최근 공연 '뮤지컬 〈레미제라블〉 - 부산'이 인터파크 제목에 포함됨.
배우 정민의 최근 공연 '뮤지컬 〈스모크〉'이 인터파크 제목에 포함됨.
배우 김신의의 최근 공연 '뮤지컬 〈삼총사〉'이 인터파크 제목에 포함됨.
배우 김신의의 최근 공연 '뮤지컬 〈삼총사〉'이 인터파크 제목에 포함됨.
배우 송원근의 최근 공연 '뮤지컬 〈오페라의 유령〉 - 서울'이 인터파크 제목에 포함됨.
배우 김아선의 최근 공연 '뮤지컬 〈오페라의 유령〉 - 서울'이 인터파크 제목에 포함됨.
배우 차지연의 최근 공연 '뮤지컬 〈컴프롬어웨이〉'이 인터파크 제목에 포함됨.
배우 문혜원의 최근 공연 '뮤지컬 〈타오르는 어둠 속에서〉'이 인터파크 제목에 포함됨.
배우 송상은의 최근 공연 '뮤지컬 〈블랙메리포핀스〉'이 인터파크 제목에 포함됨.
배우 규현의 최근 공연 '뮤지컬 ＇벤허＇'이 인터파크 제목에 포함됨.
배우 이희정의 최근 공연 '뮤지컬 ＇벤허＇'이 인터파크 제목에 포함됨.
배우 이자람의 최근 공연 '창작가무극 〈순신〉'이 인터파크 제목에 포함됨.
배우 고미경의 최근 공연 '창작가무극 〈순신〉'이 인터파크 제목에 포함됨.

## 배우 가중치

* 연극 배우 가중치

* 동명이인 제거 전 : 702명

* 현재는 동명이인의 경우 이름1, 이름2 와 같이 개별적으로 구분
* 만약 이게 필요없다면, 원래 원본 파일을 가지고 실행하면 됨

In [57]:
def actor_name_dic(actor_dic, inter_dic, SA):
  dic = {}
  for key1, value1 in actor_dic.items():
    dic[key1] = value1['actor_name']


  index = 100  # 순위권 이후 배우 추가용
  for key1, value1 in inter_dic.items():
    for i in value1['cast_act']:  # 공연별 캐스팅 배우 딕셔너리화
      ret = 0 # 순위권 배우 이름 중복 추가 방지용
      for key2, value2 in SA.items(): # 순위권 배우 판별
        if (value2['Title'] == key1 and value2['actor'] == i) or (i == '해당없음'): # 순위권 배우거나, 배우명이 없는 경우 추가 제외
          ret = 1
          break
      if(ret == 0):
        for ran in range(100, index):  # 동명이인 찾기
          if(dic[ran] == i ):
            ret = 1
            break
          else:
            ret = 0

      if(ret == 0): # 그 외 전부 추가
        dic[index] = i
        index += 1
  dic_t = {v:k for k,v in dic.items()}
  return dic, dic_t

In [58]:
pt_actor_dic, pt_actor_dic_t = actor_name_dic(play_actor_dic, play_inter_dic, PSA)

* 랭킹 배우의 최근 공연작 중 데이터에 해당하는 것이 있다면, 배우 이름 -> 인덱스

In [59]:
def change_index(search, dic):
  ret_dic = {}
  for key, value in search.items():
    index = dic[value['actor']]
    ret_dic[index] = value['Title']
  return ret_dic

* 모든 배우의 이름을 인덱스로 교체 + 공연별 배우 리스트 생성

In [60]:
def cast_list(dic1, dic2, dic_t):
  cast_dic = {}
  for key1, value1 in dic2.items():
    cast_act = value1['cast_act']
    cast_index = []
    # 배우 인덱스 저장
    for name in cast_act:
      cast_index.append(dic_t.get(name))
    cast_dic[key1] = cast_index
  return cast_dic

* 배우의 가중치 구하는 함수
  * 사용자가 입력한 공연의 배우가 다른 공연에 있을 경우 +1점
  * 유명한 배우의 공연은 무조건 +2.5점

* 나중에 별점 등의 가중치들과 더하거나 곱할 예정

In [61]:
def actor_rate(cast_dic, title_name, ci):
  score_list = []
  cast_list = cast_dic[title_name]
  for key, value in cast_dic.items():
    score = 0
    for index in cast_list:
      # 이 공연의 배우가 있을 경우 추천점수 +1점
      if((key != title_name) and (index in value)):
        score += 1
      # 유명한 배우가 있을 경우 추천점수 +2.5점
    for name, title in ci.items():
      if(key == title):
        score += 2.5
    score_list.append(score)
  return score_list

In [62]:
play_ci = change_index(PSA, pt_actor_dic_t) # 랭킹배우의 이름->인덱스
play_ci

{51: '뮤직드라마 〈불편한 편의점〉', 21: '연극 〈기형도 플레이〉', 3: '연극 〈기형도 플레이〉'}

In [63]:
play_cast_list = cast_list(pt_actor_dic, play_inter_dic, pt_actor_dic_t)
score_list = actor_rate(play_cast_list, '진짜나쁜소녀', play_ci)
play_inter_actor['actor_score'] = score_list
play_inter_actor.sort_values(by=['actor_score'], ascending=False)

,Title,cast_act,actor_score
18,연극 〈기형도 플레이〉,"최덕문, 우현주, 이석준, 박호산, 이창훈, 이동하, 이은, 김세영, 김승은",5.0
15,뮤직드라마 〈불편한 편의점〉,"장우진, 김동박, 이강혁, 박은영, 조영임, 문상희, 정예지, 정이수, 서지영, 한...",2.5
37,행오버,"최선량, 정현규, 조영광, 신재명, 손준표, 윤건웅, 최창빈, 김민우, 이도희, 이...",1.0
59,로맨틱코미디 〈슬기로운 신혼생활〉,"오세영, 정대경, 김은지, 이슬기, 한재우, 서동현, 김세나, 이재희, 송민주, 이...",1.0
28,연극 한뼘사이,"윤주희, 강단비, 주하영, 유이주, 박정윤, 최하은, 김시윤, 김현지, 김종훈, 정...",1.0
...,...,...,...
27,연극 죽여주는 이야기,"남경화, 노진욱, 이연승, 최다운, 조웅희",0.0
29,연극 핫식스,"이대우, 정회형, 김호준, 김예지, 송다영, 김은수, 임종철, 김동섭, 김정원, 전상혁",0.0
30,연극〈늘근도둑이야기〉,"노진원, 전재형, 박철민, 태항호, 김상묵, 주우성, 유일한, 이호연, 안태영",0.0
31,이머시브씨어터 카지노,"안지현, 남지현, 문수민, 오자송, 최지우, 김유리, 박상혁, 장영웅, 박서연, 안...",0.0
64,그곳에 있었다,"김현서, 정지원, 조민솔, 호천, 강우람, 김진현",0.0



---


* 뮤지컬 배우 가중치

In [64]:
mt_actor_dic, mt_actor_dic_t = actor_name_dic(mus_actor_dic, mus_inter_dic, MSA)

In [65]:
mus_ci = change_index(MSA, mt_actor_dic_t) # 랭킹배우의 이름->인덱스
mus_ci

{36: '뮤지컬 〈22년 2개월〉',
 9: '뮤지컬 〈스모크〉',
 50: '뮤지컬 〈그날들〉 10주년 기념 공연 - 대전',
 20: '뮤지컬 〈레미제라블〉 - 부산',
 47: '뮤지컬 〈삼총사〉',
 13: '뮤지컬 〈오페라의 유령〉 - 서울',
 29: '뮤지컬 〈오페라의 유령〉 - 서울',
 2: '뮤지컬 〈컴프롬어웨이〉',
 15: '뮤지컬 〈타오르는 어둠 속에서〉',
 32: '뮤지컬 〈블랙메리포핀스〉',
 5: '뮤지컬 ＇벤허＇',
 25: '뮤지컬 ＇벤허＇',
 11: '창작가무극 〈순신〉',
 99: '창작가무극 〈순신〉'}

In [66]:
mus_cast_list = cast_list(mt_actor_dic, mus_inter_dic, mt_actor_dic_t)
score_list = actor_rate(mus_cast_list, '뮤지컬 〈오페라의 유령〉 - 서울', mus_ci)
mus_inter_actor['actor_score'] = score_list
mus_inter_actor.sort_values(by=['actor_score'], ascending=False)

,Title,cast_act,actor_score
38,뮤지컬 〈오페라의 유령〉 - 서울,"조승우, 최재림, 김주택, 전동석, 손지수, 송은혜, 송원근, 황건하, 윤영석, 이...",5.0
51,뮤지컬 ＇벤허＇,"박은태, 신성록, 규현, 이지훈, 박민성, 서경수, 윤공주, 이정화, 최지혜, 이정...",5.0
54,창작가무극 〈순신〉,"형남희, 최인형, 이자람, 윤제원, 권성찬, 송문선, 고미경, 금승훈, 김백현, 김...",5.0
21,뮤지컬 〈레미제라블〉 - 부산,"민우혁, 최재림, 김우형, 카이, 조정은, 린아, 임기홍, 육현욱, 박준면, 김영주...",3.5
35,뮤지컬 〈스모크〉,"김재범, 정민, 김경수, 박정원, 강찬, 손유동, 홍승안, 김지유, 김청아, 장보람...",2.5
...,...,...,...
28,뮤지컬 〈문스토리〉,"정상윤, 성연, 김진욱, 김준호, 소정화, 박새힘, 주다온, 장보람, 강찬, 김리현...",0.0
29,뮤지컬 〈빨래〉,해당없음,0.0
30,쇼 뮤지컬 〈시스터즈 (SheStars!)〉,"유연, 신의정, 선민, 황성현, 김려원, 하유진, 정유지, 이예은, 이서영, 정연,...",0.0
31,뮤지컬 〈비더슈탄트〉,"송유택, 안지환, 황순종, 정백선, 김바다, 김지온, 동현, 이진우, 김이담, 손지...",0.0
64,뮤지컬 스크루테이프의 편지,해당없음,0.0

# 가중치 총합 함수

In [67]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler((0,5))
def weight_calc(weighted_ratings):
  weighted_df = pd.DataFrame(weighted_ratings, index = ['StarScore']).T
  weighted_df[:] = scaler.fit_transform(weighted_df[:])
  return weighted_df

In [68]:
def castscore_calc(title, actor_dic, inter_dic, actor_dic_t, ci, inter_actor):
  casting_list = cast_list(actor_dic, inter_dic, actor_dic_t)
  score_list = actor_rate(casting_list, title, ci)
  inter_actor['actor_score'] = score_list
  casting = inter_actor.sort_values(by=['actor_score'], ascending=False)
  casting = casting[['Title', 'actor_score']]
  casting = casting.reset_index(drop=True)

  cast = {}
  for i in range(len(casting)):
    key = casting['Title'][i]
    value = casting['actor_score'][i]
    cast[key] = value
    castscore_df = pd.DataFrame(cast, index = ['CastScore']).T
    castscore_df[:] = scaler.fit_transform(castscore_df[:])

  return castscore_df

In [69]:
## 연극
def plot_genre_calc(title):
  plot_genre = semantic_search(title)
  if plot_genre is not None:
    plot_genre_weight = plot_genre[['Title', 'Score']]
    plot_genre_weight = plot_genre_weight.set_index(keys=['Title'])
    plot_genre_weight[:] = scaler.fit_transform(plot_genre_weight[:])

    return plot_genre_weight
  else:
    # plot_genre가 None인 경우에 대한 처리
    print("검색 결과를 찾을 수 없습니다.")
    return None

In [70]:
## 뮤지컬
def plot_genre_calc_1(title):
  plot_genre = semantic_search_1(title)
  if plot_genre is not None:
    plot_genre_weight = plot_genre[['Title', 'Score']]
    plot_genre_weight = plot_genre_weight.set_index(keys=['Title'])
    plot_genre_weight[:] = scaler.fit_transform(plot_genre_weight[:])

    return plot_genre_weight
  else:
    # plot_genre가 None인 경우에 대한 처리
    print("검색 결과를 찾을 수 없습니다.")
    return None

In [71]:
def merge_calc(weighted_df, castscore_df, plot_genre_df, pm = 0):
  func_list = []
  play_w = pd.concat([weighted_df, castscore_df, plot_genre_df], axis=1, join='inner')
  for row in play_w.iterrows():
    #print(row[1]['Weight'])
    ss = row[1]['StarScore']
    cs = row[1]['CastScore']
    pg = row[1]['Score']
    if (pm == 0): # 연극일 경우
      func = pg * 0.65 + cs * 0.2 + ss * 0.15
    else:
      func = cs * 0.35 + pg * 0.5 + ss * 0.15
    func_list.append([row[0], func])
    print(f"Title: {row[0]}, Weighted Rating: {func}")
  return func_list

In [72]:
def play_score(title):
  weighted_df = weight_calc(play_weighted_ratings)
  castscore_df = castscore_calc(title, pt_actor_dic, play_inter_dic, pt_actor_dic_t, play_ci, play_inter_actor)
  plot_genre_df = plot_genre_calc(title)
  func_list = merge_calc(weighted_df, castscore_df, plot_genre_df)
  play_score = pd.DataFrame(func_list, columns=['Title', 'Score']).sort_values('Score', ascending=False)
  return play_score

In [73]:
def musical_score(title):
  weighted_df = weight_calc(musical_weighted_ratings)
  castscore_df = castscore_calc(title, mt_actor_dic, mus_inter_dic, mt_actor_dic_t, mus_ci, mus_inter_actor)
  plot_genre_df = plot_genre_calc_1(title)
  func_list = merge_calc(weighted_df, castscore_df, plot_genre_df, pm=1)
  musical_score = pd.DataFrame(func_list, columns=['Title', 'Score']).sort_values('Score', ascending=False)
  return musical_score

In [77]:
title = "뮤지컬 〈문스토리〉"
musical_score(title).head(10)
# 0개 겹침

======================
    TOP RESULTS
======================

Title: 난타(NANTA) - 명동공연, Weighted Rating: 0.2366255975405214
Title: 더 맨 얼라이브 〈초이스〉, Weighted Rating: 1.0765398333193374
Title: 뮤지컬 〈22년 2개월〉, Weighted Rating: 2.55531217624176
Title: 뮤지컬 〈곤 투모로우〉, Weighted Rating: 1.1359825573939764
Title: 뮤지컬 〈구텐버그〉, Weighted Rating: 1.0431579213652271
Title: 뮤지컬 〈김종욱 찾기〉, Weighted Rating: 0.9118863681119965
Title: 뮤지컬 〈레미제라블〉 - 부산, Weighted Rating: 2.10053726742386
Title: 뮤지컬 〈레베카〉 10주년 기념공연, Weighted Rating: 2.028147420627959
Title: 뮤지컬 〈렛미플라이〉, Weighted Rating: 2.9954398025397153
Title: 뮤지컬 〈멤피스〉, Weighted Rating: 1.8490205148001206
Title: 뮤지컬 〈블랙메리포핀스〉, Weighted Rating: 2.696585346598388
Title: 뮤지컬 〈비더슈탄트〉, Weighted Rating: 1.0696236015468994
Title: 뮤지컬 〈사칠〉, Weighted Rating: 1.3781115205346977
Title: 뮤지컬 〈삼총사〉, Weighted Rating: 1.814248891336353
Title: 뮤지컬 〈셜록홈즈 : 앤더슨가의 비밀〉, Weighted Rating: 1.8997183901551025
Title: 뮤지컬 〈쇼맨_어느 독재자의 네 번째 대역배우〉, Weighted Rating: 1.571623913466388
Title: 뮤지컬 〈오페라의 유령〉 - 서울, Weighted Rating: 2.089696400756575
Title: 뮤지컬 〈왓 이프〉, Weighted Rating: 1.5975772212156492
Title: 뮤지컬 〈위윌락유〉, Weighted Rating: 1.3093996593598918
Title: 뮤지컬 〈이토록 보통의〉, Weighted Rating: 1.8762453673549366
Title: 뮤지컬 〈인사이드 윌리엄〉 2023, Weighted Rating: 1.8532938376315162
Title: 뮤지컬 〈칠칠〉, Weighted Rating: 1.8666346402443112
Title: 뮤지컬 〈킴즈〉, Weighted Rating: 1.4292662395074502
Title: 뮤지컬 〈타오르는 어둠 속에서〉, Weighted Rating: 3.17534225508567
Title: 뮤지컬 〈투모로우 모닝〉, Weighted Rating: 1.6355689874102264
Title: 뮤지컬 〈판〉, Weighted Rating: 2.394302142218476
Title: 뮤지컬 〈프리다〉, Weighted Rating: 1.3982858710108563
Title: 뮤지컬 〈후크〉, Weighted Rating: 2.025566231047476
Title: 뮤지컬 더데빌 : 에덴 (Musical THE DEVIL : EDEN), Weighted Rating: 1.3188931066929752
Title: 뮤지컬 드라큘라 (Dracula：The Musical), Weighted Rating: 1.85687002146393
Title: 뮤지컬 스크루테이프의 편지, Weighted Rating: 0.8768423640323956
Title: 뮤지컬 썸데이, Weighted Rating: 1.2873078683999721
Title: 뮤지컬 프리즌, Weighted Rating: 0.14916043893755057
Title: 뮤지컬 ＇벤허＇, Weighted Rating: 3.055866924998169
Title: 뮤직드라마 당신만이, Weighted Rating: 0.4512021449591898
Title: 쇼 뮤지컬 〈시스터즈 (SheStars!)〉, Weighted Rating: 2.0103485365220517
Title: 써니텐, Weighted Rating: 0.7916810768197056
Title: 이은결 ［더 일루션 - 마스터피스］, Weighted Rating: 0.6939707659701885
Title: ［청주,세종］뮤지컬 빌의구둣방, Weighted Rating: 0.37543879805351926

                  Title     Score
23    뮤지컬 〈타오르는 어둠 속에서〉  3.175342
33             뮤지컬 ＇벤허＇  3.055867
8           뮤지컬 〈렛미플라이〉  2.995440
10        뮤지컬 〈블랙메리포핀스〉  2.696585
2         뮤지컬 〈22년 2개월〉  2.555312
25              뮤지컬 〈판〉  2.394302
6      뮤지컬 〈레미제라블〉 - 부산  2.100537
16   뮤지컬 〈오페라의 유령〉 - 서울  2.089696
7   뮤지컬 〈레베카〉 10주년 기념공연  2.028147
27             뮤지컬 〈후크〉  2.025566

In [ ]:
title = "연극 〈운빨로맨스〉- 대학로"
play_score(title).head(5)
# 1개 겹침

In [ ]:
title = "연극 너의 목소리가 들려"
play_score(title).head(5)
# 1개 겹침

In [ ]:
title = "뮤지컬 〈문스토리〉"
musical_score(title).head(5)
# 2개 겹침

In [ ]:
title = "뮤지컬 〈칠칠〉"
musical_score(title).head(5)
# 1개 겹침

In [ ]:
title = "뮤지컬 〈22년 2개월〉"
musical_score(title).head(5)
# 0개 겹침

# 작품테스트

In [ ]:
# 작품을 넣으면 나오는 작품들이 정말로 관련이 있는지
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(play_star, test_size=0.2, random_state=42)

In [ ]:
print(train_df.shape)
print(test_df.shape)

In [ ]:
 # True라고 예측한 것들 가운데 실제 True 비율
def get_precision(relevant, recommend):
     _intersection = set(recommend).intersection(set(relevant)) # set(recommend) & set(relevant)
     return len(_intersection) / len(recommend)

# 전체 True 가운데 True라고 예측한 비율
def get_recall(relevant, recommend):
    _intersection = set(recommend).intersection(set(relevant))
    return len(_intersection) / len(relevant)

# Precision@1부터 Precision@K 까지의 평균값
def get_avergae_precision(relevant, recommend):
    _precisions = []

    for i in range(len(recommend)):
        _recommend = recommend[:i+1]
        _precisions.append(get_precision(relevant, _recommend))

    return np.mean(_precisions)

## 기타(테스트용)

In [ ]:
for title, weighted_rating in weighted_ratings.items():
    print(f"Title: {title}, Weighted Rating: {weighted_rating}")

weighted_ratings.items()

In [ ]:
print(weighted_ratings.items())

In [ ]:
play_casting['Title'][22]

* 리스트 = [ 별점 가중치, 배우가중치 ]
* 이후 장르, 줄거리 가중치 생기면 추가해야 함

In [ ]:
import copy
play_weight = copy.deepcopy(weighted_ratings)
for title, weighted_rating in play_weight.items():
  lst = []
  for key, value in play_cast.items():
    if (title == key):
      lst.append(weighted_rating)
      lst.append(value)
      play_weight[title] = lst

play_weight

In [ ]:
for key, value in play_weight.items():
  #print(value[0], value[1])
  v = value[0] * 0.5 + value[1] * 0.1
  print(v)

In [ ]:
weighted_df = weight_calc()
castscore_df = castscore_calc("연극 〈운빨로맨스〉- 대학로")
func_list = merge_calc(weighted_df, castscore_df)
pd.DataFrame(func_list).sort_values(1, ascending=False)